// Operators and firms, entered once and referenced wherever they're relevant.
//
//   kind      "operator" runs the scheduled routes in routes.js and is named
//             by them. "transfer" will drive you or your bags on request, has
//             no timetable, and is offered by coverage instead.
//   services  ["passenger", "baggage"] — a firm may do either or both. Baggage
//             firms earn their place when they also carry people, as Lyn
//             Valley Taxi does; a bags-only courier is no use on a van-based
//             walk, which is why Luggage Transfers Ltd isn't here.
//   covers    { lat, lon, radiusKm } for a local firm, or { everywhere: true }
//             for one working the whole path. Only meaningful for "transfer".
//   dogs      true | false | null. Same rule as anywhere else: never guessed.
export default [
  {
    slug: "stagecoach-south-west",
    name: "Stagecoach South West",
    kind: "operator",
    url: "https://www.stagecoachbus.com/",
    phone: null,
    // Attribution for the Exmoor coast service had moved around — Exmoor
    // National Park's 2025 timetable still called it "EX1 Exmoor Explorer,
    // First Bus". Stagecoach's own 2026 timetables settle it.
    notes: "Dogs usually carried, at the driver's discretion",
    verified: "2026-09-13",
  },
  {
    slug: "atwest",
    name: "Atwest",
    kind: "operator",
    url: null,
    phone: null,
    notes: "Community transport operator around Minehead and Porlock",
    verified: null,
  },
  {
    slug: "lyn-valley-taxi",
    name: "Lyn Valley Taxi",
    kind: "transfer",
    services: ["passenger", "baggage"],
    // Based in Lynton. 20 km reaches Lynmouth, County Gate and Porlock Weir
    // but stops short of Minehead, which matches the areas they list.
    covers: { lat: 51.22942, lon: -3.83651, radiusKm: 20 },
    dogs: true,
    hours: "7am – 11pm, other times by arrangement",
    url: "https://www.lynvalleytaxi.co.uk/",
    phone: null,
    dogs_note: "Well behaved dogs",
    notes: "Drop-offs and pick-ups for walkers as well as luggage transfers, around Lynton, Lynmouth, Porlock, Brendon, County Gate, Simonsbath and Combe Martin. Five and seven seaters",
    verified: "2026-09-13",
  },
  {
    slug: "riverside-taxis-lynton",
    name: "Riverside Taxis",
    kind: "transfer",
    services: ["passenger"],
    // 4 Park Street, Lynton. 20 km reaches Combe Martin, which they list.
    covers: { lat: 51.22890, lon: -3.83798, radiusKm: 20 },
    dogs: null,
    url: "https://riversidetaxis-lynton.co.uk/",
    phone: "01598 753442",
    email: "riverside-taxis1@btconnect.com",
    notes: "Family firm, 4, 6 and 8 seaters, covering Lynton, Brendon, Porlock, Minehead and Combe Martin. The site also shows Brighton numbers left over from a template — use the 01598 one. Walker drop-offs not mentioned on their own pages",
    verified: "2026-09-13",
  },
  {
    slug: "go2-taxi-ilfracombe",
    name: "GO2 Taxi",
    kind: "transfer",
    services: ["passenger", "baggage"],
    // Ilfracombe. 25 km reaches Lynmouth; they claim Minehead to Westward Ho!
    // but say peak times may be local only.
    covers: { lat: 51.20767, lon: -4.12547, radiusKm: 25 },
    dogs: true,
    url: "http://www.go2taxi.co.uk/SWCPwalking.html",
    phone: "01271 545007",
    email: "go2taxi@mail.com",
    notes: "Six-seater. Coast path walker and luggage transfers, dog friendly, possibly local only at peak times. Mobile 07393 876629. The site hasn't changed since 2019, so whether it's still trading needs a call",
    verified: null,
  },
  {
    slug: "beach-runner-taxi",
    name: "Beach Runner Taxi",
    kind: "transfer",
    services: ["passenger", "baggage"],
    // Woolacombe. They cover Minehead to Bideford; 30 km from Woolacombe
    // reaches Lynmouth but not Porlock or Minehead.
    covers: { lat: 51.17282, lon: -4.20515, radiusKm: 30 },
    dogs: true,
    dogs_note: "Welcome with owners, no extra charge",
    hours: "Any reasonable time",
    url: "https://www.woolacombetaxi.co.uk/south-west-coastal-path",
    phone: "07825 163284",
    notes: "Coast path transfers all year, Minehead to Bideford, groups up to 14 with luggage",
    verified: "2026-09-13",
  },
  {
    slug: "ycet",
    name: "Yealm Community Electric Transport",
    kind: "operator",
    url: "https://www.ycet.co.uk/",
    phone: "07399 067942",
    email: "etaxi@ycet.co.uk",
    notes: "Electric foot ferry and water taxi between Wembury, Noss Mayo and Newton Ferrers. Also on VHF channel 69",
    verified: null,
  },
  {
    slug: "taw-and-torridge",
    name: "Taw & Torridge Coaches",
    kind: "operator",
    url: "https://www.tawandtorridge.co.uk/Service-Routes",
    phone: "01271 859533",
    notes: "Runs the Monday–Saturday 31, Ilfracombe to Woolacombe. Also on 01805 603400",
    verified: "2026-09-13",
  },
  {
    slug: "independent-coach-company",
    name: "Independent Coach Company",
    kind: "operator",
    url: null,
    phone: null,
    notes: "Runs Ilfracombe's town and village services 33–36, some only twice a week",
    verified: null,
  },
  {
    slug: "woolacombe-taxis",
    name: "Woolacombe Taxis",
    kind: "transfer",
    services: ["passenger", "baggage"],
    // EX34 7AN via postcodes.io. 20 km reaches Combe Martin; they don't list Lynton.
    covers: { lat: 51.17153, lon: -4.18317, radiusKm: 20 },
    dogs: true,
    dogs_note: "Pooch friendly",
    hours: "Day or night; book late journeys ahead",
    url: "https://www.woolacombetaxis.co.uk/",
    phone: "01271 871444",
    email: "hello@woolacombetaxis.co.uk",
    notes: "Family firm. Covers Woolacombe, Mortehoe, Ilfracombe, Combe Martin, Braunton, Croyde and Barnstaple. Coast path luggage transfers; walker drop-offs not mentioned as such",
    verified: "2026-09-13",
  },
  {
    slug: "ezee-cabs",
    name: "Ezee Cabs",
    kind: "transfer",
    services: ["passenger", "baggage"],
    // No address on the site; the OSM place node for Woolacombe. They list
    // Ilfracombe, Lynton, Lynmouth, Braunton, Instow and Westward Ho!.
    covers: { lat: 51.17282, lon: -4.20515, radiusKm: 30 },
    dogs: true,
    url: "https://ezeecabs.co.uk/",
    phone: "01271 871000",
    email: "hello@ezeecabs.co.uk",
    notes: "Taxis and minibuses from Woolacombe. Walker drop-offs along the North Devon coast and luggage transfers. Mobile 07966 548303",
    verified: "2026-09-13",
  },
  {
    slug: "a-taxi-ilfracombe",
    name: "A Taxi Ilfracombe",
    kind: "transfer",
    services: ["passenger"],
    // EX34 8LU via postcodes.io.
    covers: { lat: 51.20075, lon: -4.13007, radiusKm: 20 },
    dogs: null,
    hours: "Mon–Fri 8am – 5pm, Sun 9am – 5pm. Closed Saturdays",
    url: "https://www.ataxiilfracombe.co.uk/",
    phone: "01271 865321",
    notes: "Covers anywhere in North Devon. Nothing on walkers, luggage or dogs. Site last updated 2022",
    verified: "2026-09-13",
  },
  {
    slug: "saunton-taxis",
    name: "Saunton Taxis",
    kind: "transfer",
    services: ["passenger"],
    // 23 Saunton Road, EX33 1HD via postcodes.io. They claim all of North
    // Devon; 25 km reaches Ilfracombe and Westward Ho!.
    covers: { lat: 51.10906, lon: -4.17048, radiusKm: 25 },
    dogs: null,
    hours: "24 hours when pre-booked",
    url: "http://sauntontaxis.co.uk/",
    phone: "07890 543136",
    notes: "Drop-offs and pick-ups at coast path start and finish points. Up to six passengers. Braunton Taxis (07840 648766) shares the address and website, so appears to be the same firm",
    verified: "2026-09-13",
  },
  {
    slug: "braunton-croyde-taxis",
    name: "Braunton & Croyde Taxis",
    kind: "transfer",
    services: ["passenger"],
    // No street address on the site; OSM place node 206388734 for Braunton.
    covers: { lat: 51.10833, lon: -4.16114, radiusKm: 20 },
    dogs: null,
    url: "http://www.brauntonandcroydetaxis.co.uk/",
    phone: "01271 440450",
    notes: "Local taxis around Braunton and Croyde, plus station and airport runs. Mobile and WhatsApp 07788 726660. Nothing on walkers or luggage",
    verified: "2026-09-13",
  },
  {
    slug: "knowle-taxi-service",
    name: "Knowle Taxi Service",
    kind: "transfer",
    services: ["passenger"],
    // Greencote, Knowle, EX33 2LY from directories; position via postcodes.io.
    covers: { lat: 51.12518, lon: -4.15493, radiusKm: 20 },
    dogs: null,
    url: "https://www.facebook.com/KTSKnowle/",
    phone: "01271 815666",
    notes: "Private hire from Knowle, just north of Braunton. No website of its own; details from directories, so ring to check it's still trading",
    verified: null,
  },
  {
    slug: "appledore-instow-ferry",
    name: "Appledore & Instow Ferry",
    kind: "operator",
    url: "https://www.appledoreinstowferry.com/",
    // The site's contact page returns a server error; no phone or email found.
    phone: null,
    notes: "Not-for-profit, run by volunteers. Doesn't run in bad weather or during amber heat warnings. Status on the site, Facebook and Instagram",
    verified: "2026-09-13",
  },
  {
    slug: "all-area-taxis-bideford",
    name: "All Area Taxis",
    kind: "transfer",
    services: ["passenger"],
    // 4a Bridgeland Street, EX39 2PS via postcodes.io. 20 km reaches Braunton
    // and Barnstaple.
    covers: { lat: 51.01975, lon: -4.20486, radiusKm: 20 },
    dogs: null,
    hours: "Mon–Thu 7am – midnight, Fri–Sat 24 hours, Sun 7am – midnight",
    url: "https://www.allareataxis.co.uk/taxis-for-walkers",
    phone: "01237 470211",
    email: "allareataxis@live.co.uk",
    notes: "Bideford. Coast path drop-offs and pick-ups, with room for rucksacks. Nothing on luggage-only transfers or dogs. Not to be confused with Number 6 Taxis (01237 666666), also in Bideford",
    verified: "2026-09-13",
  },
  {
    slug: "a1-taxi-barnstaple",
    name: "A1 Taxi Service",
    kind: "transfer",
    services: ["passenger"],
    // 96 Boutport Street, EX31 1SX via postcodes.io. 20 km reaches Instow,
    // Braunton and Westward Ho!.
    covers: { lat: 51.08028, lon: -4.05837, radiusKm: 20 },
    dogs: null,
    url: "https://www.a1taxibarnstaple.com/",
    phone: "01271 322922",
    email: "info@a1taxibarnstaple.com",
    notes: "Barnstaple, over 30 years. Hybrids including six-seaters; office on Boutport Street. Also books by app. Nothing on walkers, luggage or dogs",
    verified: "2026-09-13",
  },
  {
    slug: "number-4-taxi",
    name: "Number 4 Taxi",
    kind: "transfer",
    services: ["passenger"],
    // No address on the site; OSM place node 18578704 for Barnstaple.
    covers: { lat: 51.08041, lon: -4.06005, radiusKm: 25 },
    dogs: null,
    hours: "24 hours",
    url: "https://number4taxi.co.uk/",
    phone: "01271 444444",
    email: "info@number4taxi.co.uk",
    notes: "Barnstaple private hire, formed May 2025. Names Instow, Fremington, Braunton, Appledore and Westward Ho! among the places it covers. Nothing on walkers, luggage or dogs",
    verified: "2026-09-13",
  },
  {
    slug: "number-6-taxis",
    name: "Number 6 Taxis",
    kind: "transfer",
    services: ["passenger"],
    // 2 Queen Street, EX39 2JG via postcodes.io. 20 km reaches Instow,
    // Westward Ho! and Barnstaple.
    covers: { lat: 51.01900, lon: -4.20486, radiusKm: 20 },
    dogs: null,
    url: "https://www.number6taxi.co.uk/",
    phone: "01237 666666",
    notes: "Bideford. Claims the town's largest fleet; fixed prices on pre-booked longer journeys. Nothing on walkers, luggage or dogs",
    verified: "2026-09-13",
  },
  {
    slug: "cj-taxis-northam",
    name: "CJ Taxis",
    kind: "transfer",
    services: ["passenger", "baggage"],
    // "Northam, Bideford"; OSM place node 33795483 for Northam.
    covers: { lat: 51.04011, lon: -4.21360, radiusKm: 20 },
    dogs: null,
    hours: "Until the early hours most days",
    url: "http://www.cjtaxi.co.uk/",
    phone: "07971 111843",
    email: "info@cjtaxi.co.uk",
    notes: "Caroline & Jim's Taxi, Northam. Bideford, Westward Ho!, Northam and Barnstaple; baggage transfers for walkers. The site is dated 2020, so ring to check it's still trading",
    verified: null,
  },
  {
    slug: "silverline-cabs",
    name: "Silverline Cabs",
    kind: "transfer",
    services: ["passenger"],
    // Westward Ho!; OSM place node 531657045. They claim Minehead to Newquay;
    // 30 km reaches Instow, Braunton and Hartland Quay.
    covers: { lat: 51.04117, lon: -4.23151, radiusKm: 30 },
    dogs: null,
    hours: "24 hours",
    url: "https://silverlinecabs.taxi/south-west-coast-path/",
    phone: "01237 722044",
    notes: "Westward Ho!. Coast path drop-offs and pick-ups between Minehead and Newquay; 8-seater with luggage space. Nothing on luggage-only transfers or dogs",
    verified: "2026-09-13",
  },
  {
    slug: "go-cornwall-bus",
    name: "Go Cornwall Bus",
    kind: "operator",
    url: "https://www.transportforcornwall.co.uk/",
    phone: null,
    notes: "Runs Transport for Cornwall buses, including the 95, 96, 217, 218 and 219",
    verified: "2026-09-14",
  },
  {
    slug: "trevs-taxi-bude",
    name: "Trev's Taxi",
    kind: "transfer",
    services: ["passenger"],
    // Usually at the rank by The Triangle, Bude; centre of OSM way 960723554.
    // 25 km reaches Clovelly and Hartland Quay, not Westward Ho!.
    covers: { lat: 50.82944, lon: -4.54462, radiusKm: 25 },
    dogs: true,
    dogs_note: "Well-behaved dogs welcome; say when booking",
    url: "https://trevstaxi.co.uk/",
    phone: "07799 663217",
    email: "hello@trevstaxi.co.uk",
    notes: "One-man firm in Bude since 2011; Coast Path passport stamper. Walker drop-offs at the start (preferred) or pick-ups at the end, including Clovelly and Hartland Quay. One hybrid car. Cash preferred, most cards taken. Nothing on luggage-only transfers",
    verified: "2026-09-13",
  },
  {
    slug: "barbary-cars",
    name: "Barbary Cars",
    kind: "transfer",
    services: ["passenger", "baggage"],
    // "Based at Morwenstow"; OSM place node 1758201377. 30 km reaches
    // Westward Ho! and Bude, the ends of the runs listed.
    covers: { lat: 50.90900, lon: -4.55225, radiusKm: 30 },
    dogs: true,
    dogs_note: "Well-behaved dogs welcome; mention when booking",
    hours: "Daytime; evenings and early starts by prior arrangement",
    url: "https://barbarycoast.uk/private-hire-taxi-morwenstow-welcombe/",
    phone: "07968 728354",
    email: "lee@barbarycoast.uk",
    notes: "One car, up to four passengers, pre-booked only. Mostly coast path walkers: Appledore to Clovelly from £50, Clovelly to Hartland Quay from £30, Hartland Quay to Morwenstow and Morwenstow to Bude from £40. Luggage moved between B&Bs on request. WhatsApp on the same number is quickest. Summer weekends and school holidays fill up",
    verified: "2026-09-13",
  },
  {
    slug: "cabaroo-bude",
    name: "Cabaroo",
    kind: "transfer",
    services: ["passenger"],
    // Taxi Line, Lansdown Road, EX23 8BH from a directory; position via
    // postcodes.io. 20 km reaches Hartland Quay and Crackington Haven.
    covers: { lat: 50.82983, lon: -4.54374, radiusKm: 20 },
    dogs: null,
    url: null,
    phone: "01288 683088",
    notes: "Bude. 4, 6 and 8 seaters, any distance, stations and airports. Visit Bude's listing says dogs welcome; the firm has no site of its own to confirm it. Older directories list the same number as Bayside Taxis. Nothing on walkers or luggage",
    verified: null,
  },
  {
    slug: "indigo-taxis-bude",
    name: "Indigo Taxis",
    kind: "transfer",
    services: ["passenger"],
    // 2 Surf Rise, Maer Down, EX23 8NG from a directory; position via
    // postcodes.io. 20 km reaches Hartland Quay.
    covers: { lat: 50.83668, lon: -4.55080, radiusKm: 20 },
    dogs: null,
    url: "https://www.facebook.com/p/Indigo-Taxis-100068861974432/",
    phone: "07811 969844",
    notes: "Bude. An 8-seater with plenty of luggage space, dog friendly, on Visit Bude's listing. Facebook only, so nothing confirmed by the firm; a directory says it's now part of the Cabaroo group. Worth asking about coast path drop-offs and bags",
    verified: null,
  },
  {
    slug: "edds-taxi-bude",
    name: "Edd's Taxi",
    kind: "transfer",
    services: ["passenger"],
    // No address on the site; OSM place node 33795930 for Bude.
    covers: { lat: 50.82853, lon: -4.54694, radiusKm: 20 },
    dogs: null,
    url: "http://www.edds.taxi/",
    phone: "07486 868636",
    notes: "Bude and surrounding areas. 4 and 6 seaters, airport transfers. Nothing on walkers, luggage or dogs",
    verified: "2026-09-14",
  },
  {
    slug: "d-and-d-taxis-bude",
    name: "D&D Taxis",
    kind: "transfer",
    services: ["passenger"],
    // No address on the site; OSM place node 33795930 for Bude.
    covers: { lat: 50.82853, lon: -4.54694, radiusKm: 20 },
    dogs: null,
    url: "https://www.danddtaxisbude.co.uk/",
    phone: "07895 527605",
    notes: "Bude, three taxis. Airport and station runs, nights out, school runs; prebook, weekends fill fast. Nothing on walkers, luggage or dogs",
    verified: "2026-09-14",
  },
  {
    slug: "echo-north-cornwall-taxi",
    name: "Echo North Cornwall Taxi",
    kind: "transfer",
    services: ["passenger"],
    // No address on the site; OSM place node 33795930 for Bude.
    covers: { lat: 50.82853, lon: -4.54694, radiusKm: 20 },
    dogs: null,
    url: "https://echonorthcornwalltaxicom.wordpress.com/",
    phone: "07432 074306",
    notes: "Bude. Local taxi; mentions trips out along the North Cornwall coast. Also on WhatsApp. Nothing on walkers, luggage or dogs",
    verified: "2026-09-14",
  },
  {
    slug: "avida-taxis",
    name: "Avida Taxis",
    kind: "transfer",
    services: ["passenger"],
    // No address on the site; OSM place node 287252752 for Camelford. 30 km
    // reaches Crackington Haven and Bude, both named, and Tintagel.
    covers: { lat: 50.62098, lon: -4.68033, radiusKm: 30 },
    dogs: null,
    url: "https://www.avidataxis.com/",
    phone: "07802 194153",
    email: "avida.taxis@btinternet.com",
    notes: "Camelford. Names Tintagel, Camelford, Port Isaac, Bude and Padstow among the places it covers; a review on the site mentions a run from Otterham to Crackington Haven and back. Six-seaters, station and airport runs. WhatsApp on the same number. £5 for cancelling with less than 24 hours' notice. Nothing on walkers, luggage or dogs",
    verified: "2026-09-14",
  },
  {
    slug: "boscars",
    name: "BosCars",
    kind: "transfer",
    services: ["passenger"],
    // Penally Hill, Boscastle, on Visit Boscastle's listing; OSM place node
    // 401881392 for Boscastle. 20 km reaches Crackington Haven, Tintagel and Bude.
    covers: { lat: 50.68954, lon: -4.69237, radiusKm: 20 },
    dogs: null,
    url: null,
    phone: "07790 983911",
    notes: "Boscastle. One car, a saloon with a good boot, on Visit Boscastle's 2021 listing. Its site, boscars.uk, no longer resolves; directories and a Facebook page still list it, so ring to check it's still trading. Nothing on walkers, luggage or dogs",
    verified: null,
  },
  {
    slug: "dela-cabs",
    name: "Dela Cabs",
    kind: "transfer",
    services: ["passenger", "baggage"],
    // No address on the site; OSM node 6138275491 for Delabole. 30 km reaches
    // Crackington Haven, Tintagel and Bude, all named on the site.
    covers: { lat: 50.62336, lon: -4.73234, radiusKm: 30 },
    dogs: true,
    dogs_note: "Dogs welcome, £2 extra",
    hours: "Mon–Thu 7am – 11pm, Fri–Sat 7am – late, Sun 9am – 11pm; outside those by booking",
    url: "http://www.delacabs.co.uk/",
    phone: "07929 220567",
    email: "johnslobb@hotmail.com",
    notes: "Delabole, formerly Slate Cabs. An 8-seat minibus: private hire, station and airport runs, courier work, baggage transfers and tours. Says it's in easy reach of the coast path for walks. Second number 07739 950092 on the contact page. The site looks unchanged for years, so ring to check it's still running",
    verified: "2026-09-14",
  },
  {
    slug: "camelot-taxis-tintagel",
    name: "Camelot Taxis",
    kind: "transfer",
    services: ["passenger"],
    // 31 Westground Way, PL34 0BH from a directory; position via postcodes.io.
    // 20 km reaches Crackington Haven.
    covers: { lat: 50.66656, lon: -4.74180, radiusKm: 20 },
    dogs: null,
    url: null,
    phone: "01840 770172",
    notes: "Tintagel. Directory listings only, with no site of its own and nothing recent to show it's still trading, so ring first. Nothing on walkers, luggage or dogs",
    verified: null,
  },
  {
    slug: "jais-private-hire",
    name: "Jais Private Hire",
    kind: "transfer",
    services: ["passenger"],
    // PL34 0AQ from a directory, which calls it Bossiney; postcodes.io puts the
    // postcode in Tintagel village. 20 km reaches Crackington Haven.
    covers: { lat: 50.66278, lon: -4.74428, radiusKm: 20 },
    dogs: null,
    url: null,
    phone: "07446 206280",
    notes: "Tintagel. Yell's listing says dog friendly, luggage transfers and train and coach pickups; no site of its own to confirm any of it. Worth asking about walkers and bags",
    verified: null,
  },
  {
    slug: "star-taxis-port-isaac",
    name: "Star Taxis",
    kind: "transfer",
    services: ["passenger"],
    // No address; OSM place node 280487798 for Port Isaac. 20 km reaches Tintagel.
    covers: { lat: 50.59388, lon: -4.82999, radiusKm: 20 },
    dogs: null,
    url: "https://www.facebook.com/p/STAR-TAXIS-61570456231053/",
    phone: "07376 987073",
    notes: "Port Isaac. Independent owner-driver, up to four passengers, short and long journeys, stations and airports. Facebook only; the number is from the Old School Hotel's list of local taxis. Search results quoting the page say well-behaved dogs ride in the boot, not confirmed by the firm. Nothing on walkers or luggage",
    verified: null,
  },
  {
    slug: "abby-taxis-wadebridge",
    name: "Abby Taxis",
    kind: "transfer",
    services: ["passenger"],
    // PL27 7EX on the contact page; position via postcodes.io. 25 km reaches
    // Port Isaac, Tintagel and Boscastle, all named on the site.
    covers: { lat: 50.51901, lon: -4.85000, radiusKm: 25 },
    dogs: null,
    url: "https://www.abbytaxiswadebridge.co.uk/wadebridge-taxis/",
    phone: "01208 815399",
    email: "info@parnellstaxis.co.uk",
    notes: "Wadebridge, run by Parnells Taxis, which also has a Bodmin base. Says it returns coast path walkers to their car or accommodation after the day's walk, and takes those on 4 or 5 day walks as far as Minehead. 4 to 8 seaters, pre-book; WhatsApp too. The site also gives 01726 212120. Nothing on luggage-only transfers or dogs",
    verified: "2026-09-14",
  },
  {
    slug: "midas-taxis-wadebridge",
    name: "Midas Taxis",
    kind: "transfer",
    services: ["passenger"],
    // "The Taxi Rank, Wadebridge"; OSM place node 287252204 for Wadebridge.
    // 25 km reaches Port Isaac, Tintagel and Boscastle, all named on the site.
    covers: { lat: 50.51714, lon: -4.83402, radiusKm: 25 },
    dogs: null,
    url: "https://www.wadebridgetaxis.co.uk/",
    phone: "01208 812345",
    notes: "Wadebridge. Names Port Isaac, Camelford, Tintagel and Boscastle among the places it covers, and mentions hikers on the coast. Electric cars; stations and airports. Second number 07425 629830. Nothing on luggage or dogs. Not Wadebridge Taxis, whose site is wadebridgetaxis.com",
    verified: "2026-09-14",
  },
  {
    slug: "wadebridge-taxis",
    name: "Wadebridge Taxis",
    kind: "transfer",
    services: ["passenger"],
    // No address on the site; OSM place node 287252204 for Wadebridge. 20 km
    // reaches Port Isaac, named on the site, and Tintagel.
    covers: { lat: 50.51714, lon: -4.83402, radiusKm: 20 },
    dogs: null,
    url: "https://www.wadebridgetaxis.com/",
    phone: "01208 812725",
    email: "wadebridgetaxis@talktalk.net",
    notes: "Wadebridge, family run. 4, 6 and 8 seaters; Port Isaac among its most popular runs. Stations, airports, restaurants. Cash or bank transfer. Nothing on walkers, luggage or dogs",
    verified: "2026-09-14",
  },
  {
    slug: "marks-taxis-wadebridge",
    name: "Mark's Taxis",
    kind: "transfer",
    services: ["passenger"],
    // 19 Trevanion Close, PL27 7PU on the contact page; position via
    // postcodes.io. 25 km reaches Port Isaac and Boscastle, both named.
    covers: { lat: 50.51152, lon: -4.83697, radiusKm: 25 },
    dogs: null,
    url: "https://www.markstaxis.co.uk/",
    phone: "07976 968011",
    email: "markhebburn011@btinternet.com",
    notes: "Wadebridge. 4 and 8 seaters; day trips, stations and airports. Names Port Isaac and Boscastle among the places it covers. Landline 01208 815264. Nothing on walkers, luggage or dogs",
    verified: "2026-09-14",
  },
  {
    slug: "mid-cornwall-taxis",
    name: "Mid Cornwall Taxis",
    kind: "transfer",
    services: ["passenger", "baggage"],
    // No address on the site; OSM place node 29289583 for Padstow. 15 km
    // reaches Port Isaac, the furthest place it names, not Tintagel.
    covers: { lat: 50.54038, lon: -4.93699, radiusKm: 15 },
    dogs: true,
    dogs_note: "Dog friendly: blankets and treats in every car, a loading ramp, and a bed in the Berlingo",
    url: "https://www.midcornwalltaxis.co.uk/",
    phone: "07785 233777",
    email: "info@midcornwalltaxis.co.uk",
    notes: "Padstow. Lists Port Isaac, Polzeath, Rock and Wadebridge among its regular runs. 4, 7 and 8 seaters, cash and card. Offers luggage transfers; Padstow's tourist information site says they're aimed at coast path walkers. Call or WhatsApp",
    verified: "2026-09-14",
  },
];
