// Where sections begin and end. A section references these by slug, so the end
// of one section and the start of the next are the same record rather than the
// same words typed twice — and `npm run validate` can check the GPX really
// does start where the section claims.
//
// Coordinates beyond Lynmouth are the node where OpenStreetMap's stage
// relations for the two sections meet (super-relation 2376086), not a town
// centre — the boundary as the path itself draws it. The one exception is the
// Yealm, where no node is shared: the two sides are the ends of the ferry way.
export default [
  {
    slug: "minehead",
    name: "Minehead",
    kind: "endpoint",
    lat: 51.21104, lon: -3.47360,
    notes: "The official start of the path, on the seafront",
  },
  {
    slug: "porlock-weir",
    name: "Porlock Weir",
    kind: "endpoint",
    lat: 51.21911, lon: -3.62809,
    notes: "Small harbour; pebble beach, pub and a public car park",
  },
  {
    slug: "lynmouth",
    name: "Lynmouth",
    kind: "endpoint",
    lat: 51.23080, lon: -3.83058,
    notes: "Harbour village at the foot of the cliff railway up to Lynton",
  },
  {
    slug: "combe-martin",
    name: "Combe Martin",
    kind: "endpoint",
    lat: 51.20658, lon: -4.03783,
  },
  {
    slug: "woolacombe",
    name: "Woolacombe",
    kind: "endpoint",
    lat: 51.17244, lon: -4.20768,
  },
  {
    slug: "braunton",
    name: "Braunton",
    kind: "endpoint",
    lat: 51.10135, lon: -4.16258,
  },
  {
    slug: "instow",
    name: "Instow",
    kind: "endpoint",
    lat: 51.06258, lon: -4.17849,
  },
  {
    slug: "westward-ho",
    name: "Westward Ho!",
    kind: "endpoint",
    lat: 51.04004, lon: -4.24724,
  },
  {
    slug: "clovelly",
    name: "Clovelly",
    kind: "endpoint",
    lat: 50.99879, lon: -4.40093,
  },
  {
    slug: "hartland-quay",
    name: "Hartland Quay",
    kind: "endpoint",
    lat: 50.99429, lon: -4.53386,
  },
  {
    slug: "bude",
    name: "Bude",
    kind: "endpoint",
    lat: 50.82873, lon: -4.54684,
  },
  {
    slug: "crackington-haven",
    name: "Crackington Haven",
    kind: "endpoint",
    lat: 50.74114, lon: -4.63196,
  },
  {
    slug: "tintagel",
    name: "Tintagel",
    kind: "endpoint",
    lat: 50.66783, lon: -4.75770,
  },
  {
    slug: "port-isaac",
    name: "Port Isaac",
    kind: "endpoint",
    lat: 50.59193, lon: -4.83220,
  },
  {
    slug: "padstow",
    name: "Padstow",
    kind: "endpoint",
    lat: 50.54257, lon: -4.93619,
  },
  {
    slug: "porthcothan",
    name: "Porthcothan",
    kind: "endpoint",
    lat: 50.50823, lon: -5.02219,
  },
  {
    slug: "newquay",
    name: "Newquay",
    kind: "endpoint",
    lat: 50.41338, lon: -5.08655,
  },
  {
    slug: "perranporth",
    name: "Perranporth",
    kind: "endpoint",
    lat: 50.34593, lon: -5.15491,
  },
  {
    slug: "portreath",
    name: "Portreath",
    kind: "endpoint",
    lat: 50.26120, lon: -5.28850,
  },
  {
    slug: "hayle",
    name: "Hayle",
    kind: "endpoint",
    lat: 50.18482, lon: -5.42111,
  },
  {
    slug: "st-ives",
    name: "St Ives",
    kind: "endpoint",
    lat: 50.21453, lon: -5.48716,
  },
  {
    slug: "pendeen",
    name: "Pendeen",
    kind: "endpoint",
    lat: 50.16467, lon: -5.67033,
  },
  {
    slug: "sennen-cove",
    name: "Sennen Cove",
    kind: "endpoint",
    lat: 50.07802, lon: -5.69947,
  },
  {
    slug: "lamorna",
    name: "Lamorna",
    kind: "endpoint",
    lat: 50.06270, lon: -5.56431,
  },
  {
    slug: "marazion",
    name: "Marazion",
    kind: "endpoint",
    lat: 50.12391, lon: -5.45916,
  },
  {
    slug: "porthleven",
    name: "Porthleven",
    kind: "endpoint",
    lat: 50.08534, lon: -5.31777,
  },
  {
    slug: "the-lizard",
    name: "The Lizard",
    kind: "endpoint",
    lat: 49.95958, lon: -5.20667,
  },
  {
    slug: "coverack",
    name: "Coverack",
    kind: "endpoint",
    lat: 50.02277, lon: -5.09550,
  },
  {
    slug: "helford",
    name: "Helford",
    kind: "endpoint",
    lat: 50.10034, lon: -5.12835,
  },
  {
    slug: "falmouth",
    name: "Falmouth",
    kind: "endpoint",
    lat: 50.15672, lon: -5.06976,
  },
  {
    slug: "portloe",
    name: "Portloe",
    kind: "endpoint",
    lat: 50.21834, lon: -4.89175,
  },
  {
    slug: "mevagissey",
    name: "Mevagissey",
    kind: "endpoint",
    lat: 50.26946, lon: -4.78705,
  },
  {
    slug: "par",
    name: "Par",
    kind: "endpoint",
    lat: 50.35119, lon: -4.70229,
  },
  {
    slug: "polperro",
    name: "Polperro",
    kind: "endpoint",
    lat: 50.33147, lon: -4.51840,
  },
  {
    slug: "portwrinkle",
    name: "Portwrinkle",
    kind: "endpoint",
    lat: 50.36235, lon: -4.30689,
  },
  {
    slug: "plymouth",
    name: "Plymouth",
    kind: "endpoint",
    lat: 50.36562, lon: -4.16352,
  },
  {
    slug: "yealm-wembury",
    name: "River Yealm, Wembury side",
    kind: "endpoint",
    lat: 50.31249, lon: -4.05343,
    notes: "Warren Point, where the path meets the Yealm ferry. The Noss Mayo landing is 180 m across the water and a long way round by road",
  },
  {
    slug: "yealm-noss-mayo",
    name: "River Yealm, Noss Mayo side",
    kind: "endpoint",
    lat: 50.31219, lon: -4.05096,
    notes: "Passage Road, where the Yealm ferry lands from Warren Point",
  },
  {
    slug: "bigbury-on-sea",
    name: "Bigbury-on-Sea",
    kind: "endpoint",
    lat: 50.28264, lon: -3.89248,
  },
  {
    slug: "salcombe",
    name: "Salcombe",
    kind: "endpoint",
    lat: 50.23479, lon: -3.76352,
  },
  {
    slug: "torcross",
    name: "Torcross",
    kind: "endpoint",
    lat: 50.26628, lon: -3.65238,
  },
  {
    slug: "dartmouth",
    name: "Dartmouth",
    kind: "endpoint",
    lat: 50.34838, lon: -3.57317,
  },
  {
    slug: "brixham",
    name: "Brixham",
    kind: "endpoint",
    lat: 50.39616, lon: -3.51291,
  },
  {
    slug: "babbacombe",
    name: "Babbacombe",
    kind: "endpoint",
    lat: 50.48405, lon: -3.52161,
  },
  {
    slug: "exmouth",
    name: "Exmouth",
    kind: "endpoint",
    lat: 50.61684, lon: -3.42290,
  },
  {
    slug: "sidmouth",
    name: "Sidmouth",
    kind: "endpoint",
    lat: 50.68047, lon: -3.23130,
  },
  {
    slug: "seaton",
    name: "Seaton",
    kind: "endpoint",
    lat: 50.70352, lon: -3.06160,
  },
  {
    slug: "seatown",
    name: "Seatown",
    kind: "endpoint",
    lat: 50.72208, lon: -2.82238,
  },
  {
    slug: "abbotsbury",
    name: "Abbotsbury",
    kind: "endpoint",
    lat: 50.65987, lon: -2.59883,
  },
  {
    slug: "ferrybridge",
    name: "Ferrybridge",
    kind: "endpoint",
    lat: 50.58546, lon: -2.47222,
  },
  {
    slug: "lulworth-cove",
    name: "Lulworth Cove",
    kind: "endpoint",
    lat: 50.61868, lon: -2.24980,
  },
  {
    slug: "worth-matravers",
    name: "Worth Matravers",
    kind: "endpoint",
    lat: 50.59975, lon: -2.05565,
  },
  {
    slug: "south-haven-point",
    name: "South Haven Point",
    kind: "endpoint",
    lat: 50.68304, lon: -1.94876,
    notes: "The end of the path, at the Sandbanks chain ferry",
  },
];
