// Food, drink and supplies.
//
// The selection problem: there are over a hundred cafés, pubs and shops within
// reach of these first two sections, and almost all of them are in Minehead or
// Lynmouth where you don't need telling. What matters is the isolated ones —
// Kitnors at Bossington has nothing within a mile and a half of it.
//
// So sections rank these by *isolation* (how far to the next food stop) rather
// than by distance from the route, and show the most isolated few. Town
// clusters sort themselves to the bottom; a lone tea room on a headland rises
// to the top. Record generously on remote stretches and sparingly in towns.
//
//   food: { type: "cafe" | "pub" | "restaurant" }
//   shop: { type: "convenience" | "supermarket" | "butcher" | "bakery" }
//
// A pub that also has rooms carries both a `stay` and a `food` block — the
// Bottom Ship and the Blue Ball are both, and appear in both lists.
export default [
  {
    slug: "kitnors",
    name: "Kitnors Tea Room",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.22002, lon: -3.57943,
    address: "Bossington",
    notes: "On the path at Bossington, with nothing else for a mile and a half either side",
    verified: null,
  },
  {
    slug: "porlock-weir-cafe",
    name: "The Cafe, Porlock Weir",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.21832, lon: -3.62703,
    address: "Porlock Weir",
    verified: null,
  },
  {
    slug: "millers-porlock-weir",
    name: "Millers at the Anchor",
    kind: "food",
    food: { type: "restaurant" },
    lat: 51.21885, lon: -3.62774,
    address: "Porlock Weir",
    verified: null,
  },
  {
    slug: "harbour-house-coffee",
    name: "Harbour House Coffee Shop",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.21923, lon: -3.62813,
    address: "Porlock Weir",
    verified: null,
  },
  {
    slug: "harbour-stores",
    name: "Harbour Stores",
    kind: "shop",
    shop: { type: "convenience" },
    lat: 51.21920, lon: -3.62818,
    address: "Porlock Weir",
    notes: "Effectively on the path at the Weir — the only supplies between Minehead and Porlock village",
    verified: null,
  },
  {
    slug: "corner-house-stores",
    name: "Corner House Stores",
    kind: "shop",
    shop: { type: "convenience" },
    lat: 51.20190, lon: -3.48102,
    address: "Minehead",
    verified: null,
  },
  {
    slug: "stuart-lowen-butchers",
    name: "Stuart Lowen Butchers",
    kind: "shop",
    shop: { type: "butcher" },
    lat: 51.20189, lon: -3.46510,
    address: "Alcombe, Minehead",
    verified: null,
  },
  {
    slug: "whortleberry-tearoom",
    name: "Whortleberry Tearoom",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.20900, lon: -3.59771,
    address: "Porlock",
    verified: null,
  },
  {
    slug: "lyndale-tea-rooms",
    name: "Lyndale Tea Rooms",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.22950, lon: -3.82863,
    address: "Lynmouth",
    verified: null,
  },
  {
    slug: "lynmouth-bay-cafe",
    name: "Lynmouth Bay Café",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.23019, lon: -3.83011,
    address: "Lynmouth",
    verified: null,
  },
  {
    slug: "cliff-top-cafe",
    name: "Cliff Top Cafe",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.23123, lon: -3.83535,
    address: "Lynton, by the cliff railway",
    verified: null,
  },
  {
    slug: "mother-meldrums",
    name: "Mother Meldrum's Tea Garden",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.23271, lon: -3.85135,
    address: "Valley of Rocks, Lynton, EX35 6JH",
    phone: "01598 753667",
    notes: "Outdoor seating only, so it closes in bad weather as well as out of season. Reported dog friendly. Whether it's still trading needs a call",
    verified: null,
  },
  {
    slug: "lee-abbey-tea-cottage",
    name: "Lee Abbey Tea Cottage",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.22564, lon: -3.87097,
    address: "Lee Bay, Lynton, EX35 6JJ",
    phone: "01598 752621",
    email: "bookings@leeabbey.org.uk",
    url: "https://leeabbeydevon.org.uk/visit/tea-cottage/",
    notes: "Closed for the whole of 2026; Lee Abbey says it expects to reopen next summer. Summer only when open",
    verified: "2026-09-13",
  },
  {
    slug: "focsle-inn",
    name: "Fo'c'sle Inn",
    kind: "food",
    food: { type: "pub" },
    lat: 51.20688, lon: -4.03786,
    address: "Combe Martin seafront",
    verified: null,
  },
  {
    slug: "dolphin-inn-combe-martin",
    name: "Dolphin Inn",
    kind: "food",
    food: { type: "pub" },
    lat: 51.20661, lon: -4.03892,
    address: "Combe Martin seafront",
    verified: null,
  },
  {
    slug: "galleon-tea-rooms",
    name: "Galleon Tea Rooms",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.20606, lon: -4.03795,
    address: "Combe Martin",
    verified: null,
  },
  {
    slug: "black-and-white-chips",
    name: "The Black & White Fish and Chip Shop",
    kind: "food",
    food: { type: "restaurant" },
    lat: 51.20608, lon: -4.03741,
    address: "Combe Martin",
    notes: "Fish and chips",
    verified: null,
  },
  {
    slug: "londis-lynton",
    name: "Londis",
    kind: "shop",
    shop: { type: "convenience" },
    lat: 51.23001, lon: -3.83518,
    address: "Lee Road, Lynton",
    notes: "Lynton is the last shop before Combe Martin",
    verified: null,
  },
  {
    slug: "costcutter-lynton",
    name: "Costcutter (Lynton Store)",
    kind: "shop",
    shop: { type: "convenience" },
    lat: 51.22998, lon: -3.83643,
    address: "Lee Road, Lynton",
    verified: null,
  },
  {
    slug: "premier-combe-martin",
    name: "Premier Seaside Stores",
    kind: "shop",
    shop: { type: "convenience" },
    lat: 51.20635, lon: -4.03851,
    address: "Combe Martin seafront",
    url: "https://www.premier-stores.co.uk/our-stores/seaside-stores",
    verified: null,
  },
  {
    slug: "central-combe-martin",
    name: "Central Convenience Store",
    kind: "shop",
    shop: { type: "convenience" },
    lat: 51.20590, lon: -4.03635,
    address: "Cross Street, Combe Martin, EX34 0DD",
    phone: "01271 882214",
    verified: null,
  },
  {
    slug: "village-bakery-combe-martin",
    name: "The Village Bakery",
    kind: "shop",
    shop: { type: "bakery" },
    lat: 51.20547, lon: -4.03543,
    address: "King Street, Combe Martin",
    verified: null,
  },
  {
    slug: "sawmills-watermouth",
    name: "The Sawmills",
    kind: "food",
    food: { type: "pub" },
    lat: 51.20929, lon: -4.06436,
    address: "Watermouth, Berrynarbor",
    notes: "Freehouse on the A399 at the Berrynarbor turn, inland of Watermouth Cove",
    verified: null,
  },
  {
    slug: "hele-bay-pub",
    name: "The Hele Bay",
    kind: "food",
    food: { type: "pub" },
    lat: 51.20938, lon: -4.09804,
    address: "Watermouth Road, Hele Bay, Ilfracombe",
    url: "https://helebaypub.co.uk/",
    verified: null,
  },
  {
    slug: "hele-bay-cafe",
    name: "The Bay Café",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.21041, lon: -4.09787,
    address: "Hele Beach, Ilfracombe",
    notes: "On the beach at Hele",
    verified: null,
  },
  {
    slug: "premier-hele-bay",
    name: "Premier Hele Bay Garage",
    kind: "shop",
    shop: { type: "convenience" },
    lat: 51.20886, lon: -4.09839,
    address: "Watermouth Road, Hele Bay, Ilfracombe",
    notes: "The garage shop on the main road above the beach",
    verified: null,
  },
  {
    slug: "lime-kiln-cafe",
    name: "The Lime Kiln Café",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.20895, lon: -4.11073,
    address: "Ilfracombe harbour",
    url: "https://www.thelimekilncafe.co.uk/",
    verified: null,
  },
  {
    slug: "lidl-ilfracombe",
    name: "Lidl",
    kind: "shop",
    shop: { type: "supermarket" },
    lat: 51.20841, lon: -4.12758,
    address: "Wilder Road, Ilfracombe",
    notes: "Just inland of the path on the way out of Ilfracombe. The last big shop before Woolacombe",
    verified: null,
  },
  {
    slug: "coop-ilfracombe",
    name: "Co-op",
    kind: "shop",
    shop: { type: "convenience" },
    lat: 51.20647, lon: -4.12603,
    address: "High Street, Ilfracombe",
    verified: null,
  },
  {
    slug: "grampus-inn",
    name: "The Grampus Inn",
    kind: "food",
    food: { type: "pub" },
    lat: 51.19597, lon: -4.17101,
    address: "Lee, Ilfracombe, EX34 8LR",
    url: "http://thegrampusinn.co.uk",
    notes: "In the village, a short way up the lane from Lee Bay. Says walkers and dogs are always welcome. The Old Schoolroom café is by the church, 150 m away",
    verified: null,
  },
  {
    slug: "chichester-arms",
    name: "Chichester Arms",
    kind: "food",
    food: { type: "pub" },
    lat: 51.18479, lon: -4.20925,
    address: "Mortehoe",
    notes: "By the church in Mortehoe, a short walk inland from the path. The Ship Aground and Miss Fea's Café are next door",
    verified: null,
  },
  {
    slug: "barricane-beach-cafe",
    name: "Barricane Beach Café",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.17618, lon: -4.21270,
    address: "Barricane Beach, Woolacombe",
    notes: "Above the cove, just before Woolacombe. Sri Lankan curries in the evenings, per OSM's name for it. Seasonal hours not confirmed",
    verified: null,
  },
  {
    slug: "red-barn-woolacombe",
    name: "The Red Barn",
    kind: "food",
    food: { type: "pub" },
    lat: 51.17264, lon: -4.20699,
    address: "Barton Road, Woolacombe",
    verified: null,
  },
  {
    slug: "spar-woolacombe",
    name: "Spar",
    kind: "shop",
    shop: { type: "convenience" },
    lat: 51.17242, lon: -4.20582,
    address: "Woolacombe",
    verified: null,
  },
  {
    slug: "porthole-woolacombe",
    name: "The Porthole",
    kind: "food",
    food: { type: "cafe" },
    // OSM node 6814184086.
    lat: 51.16127, lon: -4.20885,
    address: "Marine Drive, Woolacombe",
    url: "https://www.theportholewoolacombe.co.uk/",
    notes: "Kiosk above the dunes in a converted National Trust toilet block, outdoor seating only. Dog-friendly",
    verified: null,
  },
  {
    slug: "putsborough-beach-shop",
    name: "Putsborough Sands Beach Shop",
    kind: "food",
    food: { type: "cafe" },
    shop: { type: "convenience" },
    // Centre of OSM way 1070652768.
    lat: 51.14517, lon: -4.22170,
    address: "Putsborough, Georgeham, EX33 1LB",
    phone: "01271 890327",
    url: "https://www.putsborough.com/beach-shop/",
    notes: "Café and beach shop at the top of the sands, open every day all year. Mobile 07810 127342",
    verified: "2026-09-13",
  },
  {
    slug: "sandleigh-tea-room",
    name: "Sandleigh Tea Room",
    kind: "food",
    food: { type: "cafe" },
    // Centre of OSM way 973498482.
    lat: 51.13470, lon: -4.24097,
    address: "Baggy Point, Croyde",
    phone: "01271 891230",
    url: "https://www.nationaltrust.org.uk/visit/devon/baggy-point/eating-at-baggy-point",
    notes: "National Trust, in a garden below Baggy Point, indoor and outdoor seating. Ruda's fish and chip shop is 400 m on at Croyde Bay; Croyde village, 800 m inland, has three pubs",
    verified: null,
  },
  {
    slug: "saunton-break-cafe",
    name: "Saunton Break Café",
    kind: "food",
    food: { type: "cafe" },
    // OSM node 2455719815, where it's named "Sands".
    lat: 51.11730, lon: -4.22021,
    address: "Saunton Sands beach car park, Saunton",
    notes: "At the beach car park, with the Beachside Grill restaurant and a beach shop alongside",
    verified: null,
  },
  {
    slug: "brimbles-sandy-lane",
    name: "Brimbles, Sandy Lane car park",
    kind: "food",
    food: { type: "cafe" },
    // OSM node 11948821569.
    lat: 51.09419, lon: -4.19584,
    address: "Sandy Lane, Braunton Burrows, EX33 2NX",
    notes: "Takeaway drinks, ice creams and snacks from the car park's entrance hut. Outdoor seating only. Season and hours not confirmed",
    verified: null,
  },
  {
    slug: "quay-cafe-braunton",
    name: "The Quay Café",
    kind: "food",
    food: { type: "cafe" },
    // Centre of OSM way 237048277.
    lat: 51.10148, lon: -4.16291,
    address: "Velator Quay, Braunton",
    url: "https://thequaycafe.com/",
    notes: "At the quay where the section ends. Dog-friendly",
    verified: null,
  },
  {
    slug: "brook-stores-croyde",
    name: "Brook Stores",
    kind: "shop",
    shop: { type: "convenience" },
    // OSM node 542162882.
    lat: 51.13081, lon: -4.22417,
    address: "Croyde",
    notes: "In Croyde village, 800 m inland of the bay. Ruda Holiday Park, on the path, has a Nisa; whether it serves non-residents isn't confirmed",
    verified: null,
  },
  {
    slug: "tesco-braunton",
    name: "Tesco",
    kind: "shop",
    shop: { type: "supermarket" },
    // Centre of OSM way 29237601.
    lat: 51.10304, lon: -4.16452,
    address: "Vellator Way, Braunton, EX33 2FB",
    url: "https://www.tesco.com/store-locator/braunton/vellator-way",
    notes: "200 m from Velator Quay",
    verified: null,
  },
];
