// Food, drink and supplies.
//
// The selection problem: there are over a hundred cafés, pubs and shops within
// reach of these first two sections, and almost all of them are in Minehead or
// Lynmouth where you don't need telling. What matters is the isolated ones —
// Kitnors at Bossington has nothing within a mile and a half of it.
//
// So sections rank these by *isolation* (how far to the next food stop) rather
// than by distance from the route, and show the most isolated few. Town
// clusters sort themselves to the bottom; a lone tea room on a headland rises
// to the top. Record generously on remote stretches and sparingly in towns.
//
//   food: { type: "cafe" | "pub" | "restaurant" }
//   shop: { type: "convenience" | "supermarket" | "butcher" | "bakery" }
//
// A pub that also has rooms carries both a `stay` and a `food` block — the
// Bottom Ship and the Blue Ball are both, and appear in both lists.
export default [
  {
    slug: "kitnors",
    name: "Kitnors Tea Room",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.22002, lon: -3.57943,
    address: "Bossington",
    notes: "On the path at Bossington, with nothing else for a mile and a half either side",
    verified: null,
  },
  {
    slug: "porlock-weir-cafe",
    name: "The Cafe, Porlock Weir",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.21832, lon: -3.62703,
    address: "Porlock Weir",
    verified: null,
  },
  {
    slug: "millers-porlock-weir",
    name: "Millers at the Anchor",
    kind: "food",
    food: { type: "restaurant" },
    lat: 51.21885, lon: -3.62774,
    address: "Porlock Weir",
    verified: null,
  },
  {
    slug: "harbour-house-coffee",
    name: "Harbour House Coffee Shop",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.21923, lon: -3.62813,
    address: "Porlock Weir",
    verified: null,
  },
  {
    slug: "harbour-stores",
    name: "Harbour Stores",
    kind: "shop",
    shop: { type: "convenience" },
    lat: 51.21920, lon: -3.62818,
    address: "Porlock Weir",
    notes: "Effectively on the path at the Weir — the only supplies between Minehead and Porlock village",
    verified: null,
  },
  {
    slug: "corner-house-stores",
    name: "Corner House Stores",
    kind: "shop",
    shop: { type: "convenience" },
    lat: 51.20190, lon: -3.48102,
    address: "Minehead",
    verified: null,
  },
  {
    slug: "stuart-lowen-butchers",
    name: "Stuart Lowen Butchers",
    kind: "shop",
    shop: { type: "butcher" },
    lat: 51.20189, lon: -3.46510,
    address: "Alcombe, Minehead",
    verified: null,
  },
  {
    slug: "whortleberry-tearoom",
    name: "Whortleberry Tearoom",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.20900, lon: -3.59771,
    address: "Porlock",
    verified: null,
  },
  {
    slug: "lyndale-tea-rooms",
    name: "Lyndale Tea Rooms",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.22950, lon: -3.82863,
    address: "Lynmouth",
    verified: null,
  },
  {
    slug: "lynmouth-bay-cafe",
    name: "Lynmouth Bay Café",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.23019, lon: -3.83011,
    address: "Lynmouth",
    verified: null,
  },
  {
    slug: "cliff-top-cafe",
    name: "Cliff Top Cafe",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.23123, lon: -3.83535,
    address: "Lynton, by the cliff railway",
    verified: null,
  },
  {
    slug: "mother-meldrums",
    name: "Mother Meldrum's Tea Garden",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.23271, lon: -3.85135,
    address: "Valley of Rocks, Lynton, EX35 6JH",
    phone: "01598 753667",
    notes: "Outdoor seating only, so it closes in bad weather as well as out of season. Reported dog friendly. Whether it's still trading needs a call",
    verified: null,
  },
  {
    slug: "lee-abbey-tea-cottage",
    name: "Lee Abbey Tea Cottage",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.22564, lon: -3.87097,
    address: "Lee Bay, Lynton, EX35 6JJ",
    phone: "01598 752621",
    email: "bookings@leeabbey.org.uk",
    url: "https://leeabbeydevon.org.uk/visit/tea-cottage/",
    notes: "Closed for the whole of 2026; Lee Abbey says it expects to reopen next summer. Summer only when open",
    verified: "2026-09-13",
  },
  {
    slug: "focsle-inn",
    name: "Fo'c'sle Inn",
    kind: "food",
    food: { type: "pub" },
    lat: 51.20688, lon: -4.03786,
    address: "Combe Martin seafront",
    verified: null,
  },
  {
    slug: "dolphin-inn-combe-martin",
    name: "Dolphin Inn",
    kind: "food",
    food: { type: "pub" },
    lat: 51.20661, lon: -4.03892,
    address: "Combe Martin seafront",
    verified: null,
  },
  {
    slug: "galleon-tea-rooms",
    name: "Galleon Tea Rooms",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.20606, lon: -4.03795,
    address: "Combe Martin",
    verified: null,
  },
  {
    slug: "black-and-white-chips",
    name: "The Black & White Fish and Chip Shop",
    kind: "food",
    food: { type: "restaurant" },
    lat: 51.20608, lon: -4.03741,
    address: "Combe Martin",
    notes: "Fish and chips",
    verified: null,
  },
  {
    slug: "londis-lynton",
    name: "Londis",
    kind: "shop",
    shop: { type: "convenience" },
    lat: 51.23001, lon: -3.83518,
    address: "Lee Road, Lynton",
    notes: "Lynton is the last shop before Combe Martin",
    verified: null,
  },
  {
    slug: "costcutter-lynton",
    name: "Costcutter (Lynton Store)",
    kind: "shop",
    shop: { type: "convenience" },
    lat: 51.22998, lon: -3.83643,
    address: "Lee Road, Lynton",
    verified: null,
  },
  {
    slug: "premier-combe-martin",
    name: "Premier Seaside Stores",
    kind: "shop",
    shop: { type: "convenience" },
    lat: 51.20635, lon: -4.03851,
    address: "Combe Martin seafront",
    url: "https://www.premier-stores.co.uk/our-stores/seaside-stores",
    verified: null,
  },
  {
    slug: "central-combe-martin",
    name: "Central Convenience Store",
    kind: "shop",
    shop: { type: "convenience" },
    lat: 51.20590, lon: -4.03635,
    address: "Cross Street, Combe Martin, EX34 0DD",
    phone: "01271 882214",
    verified: null,
  },
  {
    slug: "village-bakery-combe-martin",
    name: "The Village Bakery",
    kind: "shop",
    shop: { type: "bakery" },
    lat: 51.20547, lon: -4.03543,
    address: "King Street, Combe Martin",
    verified: null,
  },
];
