// Food, drink and supplies.
//
// The selection problem: there are over a hundred cafés, pubs and shops within
// reach of these first two sections, and almost all of them are in Minehead or
// Lynmouth where you don't need telling. What matters is the isolated ones —
// Kitnors at Bossington has nothing within a mile and a half of it.
//
// So sections rank these by *isolation* (how far to the next food stop) rather
// than by distance from the route, and show the most isolated few. Town
// clusters sort themselves to the bottom; a lone tea room on a headland rises
// to the top. Record generously on remote stretches and sparingly in towns.
//
//   food: { type: "cafe" | "pub" | "restaurant" }
//   shop: { type: "convenience" | "supermarket" | "butcher" | "bakery" }
//
// A pub that also has rooms carries both a `stay` and a `food` block — the
// Bottom Ship and the Blue Ball are both, and appear in both lists.
export default [
  {
    slug: "kitnors",
    name: "Kitnors Tea Room",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.22002, lon: -3.57943,
    address: "Bossington",
    notes: "On the path at Bossington, with nothing else for a mile and a half either side",
    verified: null,
  },
  {
    slug: "porlock-weir-cafe",
    name: "The Cafe, Porlock Weir",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.21832, lon: -3.62703,
    address: "Porlock Weir",
    verified: null,
  },
  {
    slug: "millers-porlock-weir",
    name: "Millers at the Anchor",
    kind: "food",
    food: { type: "restaurant" },
    lat: 51.21885, lon: -3.62774,
    address: "Porlock Weir",
    verified: null,
  },
  {
    slug: "harbour-house-coffee",
    name: "Harbour House Coffee Shop",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.21923, lon: -3.62813,
    address: "Porlock Weir",
    verified: null,
  },
  {
    slug: "harbour-stores",
    name: "Harbour Stores",
    kind: "shop",
    shop: { type: "convenience" },
    lat: 51.21920, lon: -3.62818,
    address: "Porlock Weir",
    notes: "Effectively on the path at the Weir — the only supplies between Minehead and Porlock village",
    verified: null,
  },
  {
    slug: "corner-house-stores",
    name: "Corner House Stores",
    kind: "shop",
    shop: { type: "convenience" },
    lat: 51.20190, lon: -3.48102,
    address: "Minehead",
    verified: null,
  },
  {
    slug: "stuart-lowen-butchers",
    name: "Stuart Lowen Butchers",
    kind: "shop",
    shop: { type: "butcher" },
    lat: 51.20189, lon: -3.46510,
    address: "Alcombe, Minehead",
    verified: null,
  },
  {
    slug: "whortleberry-tearoom",
    name: "Whortleberry Tearoom",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.20900, lon: -3.59771,
    address: "Porlock",
    verified: null,
  },
  {
    slug: "lyndale-tea-rooms",
    name: "Lyndale Tea Rooms",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.22950, lon: -3.82863,
    address: "Lynmouth",
    verified: null,
  },
  {
    slug: "lynmouth-bay-cafe",
    name: "Lynmouth Bay Café",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.23019, lon: -3.83011,
    address: "Lynmouth",
    verified: null,
  },
  {
    slug: "cliff-top-cafe",
    name: "Cliff Top Cafe",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.23123, lon: -3.83535,
    address: "Lynton, by the cliff railway",
    verified: null,
  },
  {
    slug: "mother-meldrums",
    name: "Mother Meldrum's Tea Garden",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.23271, lon: -3.85135,
    address: "Valley of Rocks, Lynton, EX35 6JH",
    phone: "01598 753667",
    notes: "Outdoor seating only, so it closes in bad weather as well as out of season. Reported dog friendly. Whether it's still trading needs a call",
    verified: null,
  },
  {
    slug: "lee-abbey-tea-cottage",
    name: "Lee Abbey Tea Cottage",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.22564, lon: -3.87097,
    address: "Lee Bay, Lynton, EX35 6JJ",
    phone: "01598 752621",
    email: "bookings@leeabbey.org.uk",
    url: "https://leeabbeydevon.org.uk/visit/tea-cottage/",
    notes: "Closed for the whole of 2026; Lee Abbey says it expects to reopen next summer. Summer only when open",
    verified: "2026-09-13",
  },
  {
    slug: "focsle-inn",
    name: "Fo'c'sle Inn",
    kind: "food",
    food: { type: "pub" },
    lat: 51.20688, lon: -4.03786,
    address: "Combe Martin seafront",
    verified: null,
  },
  {
    slug: "dolphin-inn-combe-martin",
    name: "Dolphin Inn",
    kind: "food",
    food: { type: "pub" },
    lat: 51.20661, lon: -4.03892,
    address: "Combe Martin seafront",
    verified: null,
  },
  {
    slug: "galleon-tea-rooms",
    name: "Galleon Tea Rooms",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.20606, lon: -4.03795,
    address: "Combe Martin",
    verified: null,
  },
  {
    slug: "black-and-white-chips",
    name: "The Black & White Fish and Chip Shop",
    kind: "food",
    food: { type: "restaurant" },
    lat: 51.20608, lon: -4.03741,
    address: "Combe Martin",
    notes: "Fish and chips",
    verified: null,
  },
  {
    slug: "londis-lynton",
    name: "Londis",
    kind: "shop",
    shop: { type: "convenience" },
    lat: 51.23001, lon: -3.83518,
    address: "Lee Road, Lynton",
    notes: "Lynton is the last shop before Combe Martin",
    verified: null,
  },
  {
    slug: "costcutter-lynton",
    name: "Costcutter (Lynton Store)",
    kind: "shop",
    shop: { type: "convenience" },
    lat: 51.22998, lon: -3.83643,
    address: "Lee Road, Lynton",
    verified: null,
  },
  {
    slug: "premier-combe-martin",
    name: "Premier Seaside Stores",
    kind: "shop",
    shop: { type: "convenience" },
    lat: 51.20635, lon: -4.03851,
    address: "Combe Martin seafront",
    url: "https://www.premier-stores.co.uk/our-stores/seaside-stores",
    verified: null,
  },
  {
    slug: "central-combe-martin",
    name: "Central Convenience Store",
    kind: "shop",
    shop: { type: "convenience" },
    lat: 51.20590, lon: -4.03635,
    address: "Cross Street, Combe Martin, EX34 0DD",
    phone: "01271 882214",
    verified: null,
  },
  {
    slug: "village-bakery-combe-martin",
    name: "The Village Bakery",
    kind: "shop",
    shop: { type: "bakery" },
    lat: 51.20547, lon: -4.03543,
    address: "King Street, Combe Martin",
    verified: null,
  },
  {
    slug: "sawmills-watermouth",
    name: "The Sawmills",
    kind: "food",
    food: { type: "pub" },
    lat: 51.20929, lon: -4.06436,
    address: "Watermouth, Berrynarbor",
    notes: "Freehouse on the A399 at the Berrynarbor turn, inland of Watermouth Cove",
    verified: null,
  },
  {
    slug: "hele-bay-pub",
    name: "The Hele Bay",
    kind: "food",
    food: { type: "pub" },
    lat: 51.20938, lon: -4.09804,
    address: "Watermouth Road, Hele Bay, Ilfracombe",
    url: "https://helebaypub.co.uk/",
    verified: null,
  },
  {
    slug: "hele-bay-cafe",
    name: "The Bay Café",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.21041, lon: -4.09787,
    address: "Hele Beach, Ilfracombe",
    notes: "On the beach at Hele",
    verified: null,
  },
  {
    slug: "premier-hele-bay",
    name: "Premier Hele Bay Garage",
    kind: "shop",
    shop: { type: "convenience" },
    lat: 51.20886, lon: -4.09839,
    address: "Watermouth Road, Hele Bay, Ilfracombe",
    notes: "The garage shop on the main road above the beach",
    verified: null,
  },
  {
    slug: "lime-kiln-cafe",
    name: "The Lime Kiln Café",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.20895, lon: -4.11073,
    address: "Ilfracombe harbour",
    url: "https://www.thelimekilncafe.co.uk/",
    verified: null,
  },
  {
    slug: "lidl-ilfracombe",
    name: "Lidl",
    kind: "shop",
    shop: { type: "supermarket" },
    lat: 51.20841, lon: -4.12758,
    address: "Wilder Road, Ilfracombe",
    notes: "Just inland of the path on the way out of Ilfracombe. The last big shop before Woolacombe",
    verified: null,
  },
  {
    slug: "coop-ilfracombe",
    name: "Co-op",
    kind: "shop",
    shop: { type: "convenience" },
    lat: 51.20647, lon: -4.12603,
    address: "High Street, Ilfracombe",
    verified: null,
  },
  {
    slug: "grampus-inn",
    name: "The Grampus Inn",
    kind: "food",
    food: { type: "pub" },
    lat: 51.19597, lon: -4.17101,
    address: "Lee, Ilfracombe, EX34 8LR",
    url: "http://thegrampusinn.co.uk",
    notes: "In the village, a short way up the lane from Lee Bay. Says walkers and dogs are always welcome. The Old Schoolroom café is by the church, 150 m away",
    verified: null,
  },
  {
    slug: "chichester-arms",
    name: "Chichester Arms",
    kind: "food",
    food: { type: "pub" },
    lat: 51.18479, lon: -4.20925,
    address: "Mortehoe",
    notes: "By the church in Mortehoe, a short walk inland from the path. The Ship Aground and Miss Fea's Café are next door",
    verified: null,
  },
  {
    slug: "barricane-beach-cafe",
    name: "Barricane Beach Café",
    kind: "food",
    food: { type: "cafe" },
    lat: 51.17618, lon: -4.21270,
    address: "Barricane Beach, Woolacombe",
    notes: "Above the cove, just before Woolacombe. Sri Lankan curries in the evenings, per OSM's name for it. Seasonal hours not confirmed",
    verified: null,
  },
  {
    slug: "red-barn-woolacombe",
    name: "The Red Barn",
    kind: "food",
    food: { type: "pub" },
    lat: 51.17264, lon: -4.20699,
    address: "Barton Road, Woolacombe",
    verified: null,
  },
  {
    slug: "spar-woolacombe",
    name: "Spar",
    kind: "shop",
    shop: { type: "convenience" },
    lat: 51.17242, lon: -4.20582,
    address: "Woolacombe",
    verified: null,
  },
  {
    slug: "porthole-woolacombe",
    name: "The Porthole",
    kind: "food",
    food: { type: "cafe" },
    // OSM node 6814184086.
    lat: 51.16127, lon: -4.20885,
    address: "Marine Drive, Woolacombe",
    url: "https://www.theportholewoolacombe.co.uk/",
    notes: "Kiosk above the dunes in a converted National Trust toilet block, outdoor seating only. Dog-friendly",
    verified: null,
  },
  {
    slug: "putsborough-beach-shop",
    name: "Putsborough Sands Beach Shop",
    kind: "food",
    food: { type: "cafe" },
    shop: { type: "convenience" },
    // Centre of OSM way 1070652768.
    lat: 51.14517, lon: -4.22170,
    address: "Putsborough, Georgeham, EX33 1LB",
    phone: "01271 890327",
    url: "https://www.putsborough.com/beach-shop/",
    notes: "Café and beach shop at the top of the sands, open every day all year. Mobile 07810 127342",
    verified: "2026-09-13",
  },
  {
    slug: "sandleigh-tea-room",
    name: "Sandleigh Tea Room",
    kind: "food",
    food: { type: "cafe" },
    // Centre of OSM way 973498482.
    lat: 51.13470, lon: -4.24097,
    address: "Baggy Point, Croyde",
    phone: "01271 891230",
    url: "https://www.nationaltrust.org.uk/visit/devon/baggy-point/eating-at-baggy-point",
    notes: "National Trust, in a garden below Baggy Point, indoor and outdoor seating. Ruda's fish and chip shop is 400 m on at Croyde Bay; Croyde village, 800 m inland, has three pubs",
    verified: null,
  },
  {
    slug: "saunton-break-cafe",
    name: "Saunton Break Café",
    kind: "food",
    food: { type: "cafe" },
    // OSM node 2455719815, where it's named "Sands".
    lat: 51.11730, lon: -4.22021,
    address: "Saunton Sands beach car park, Saunton",
    notes: "At the beach car park, with the Beachside Grill restaurant and a beach shop alongside",
    verified: null,
  },
  {
    slug: "brimbles-sandy-lane",
    name: "Brimbles, Sandy Lane car park",
    kind: "food",
    food: { type: "cafe" },
    // OSM node 11948821569.
    lat: 51.09419, lon: -4.19584,
    address: "Sandy Lane, Braunton Burrows, EX33 2NX",
    notes: "Takeaway drinks, ice creams and snacks from the car park's entrance hut. Outdoor seating only. Season and hours not confirmed",
    verified: null,
  },
  {
    slug: "quay-cafe-braunton",
    name: "The Quay Café",
    kind: "food",
    food: { type: "cafe" },
    // Centre of OSM way 237048277.
    lat: 51.10148, lon: -4.16291,
    address: "Velator Quay, Braunton",
    url: "https://thequaycafe.com/",
    notes: "At the quay where the section ends. Dog-friendly",
    verified: null,
  },
  {
    slug: "brook-stores-croyde",
    name: "Brook Stores",
    kind: "shop",
    shop: { type: "convenience" },
    // OSM node 542162882.
    lat: 51.13081, lon: -4.22417,
    address: "Croyde",
    notes: "In Croyde village, 800 m inland of the bay. Ruda Holiday Park, on the path, has a Nisa; whether it serves non-residents isn't confirmed",
    verified: null,
  },
  {
    slug: "tesco-braunton",
    name: "Tesco",
    kind: "shop",
    shop: { type: "supermarket" },
    // Centre of OSM way 29237601.
    lat: 51.10304, lon: -4.16452,
    address: "Vellator Way, Braunton, EX33 2FB",
    url: "https://www.tesco.com/store-locator/braunton/vellator-way",
    notes: "200 m from Velator Quay",
    verified: null,
  },
  {
    slug: "spar-chivenor",
    name: "Spar, Chivenor Cross",
    kind: "shop",
    shop: { type: "convenience" },
    // OSM node 4623796891.
    lat: 51.09419, lon: -4.13710,
    address: "Chivenor Cross, Braunton Road",
    url: "https://www.spar.co.uk/store-locator/awl27722-spar-chivenor-cross",
    notes: "Beside the Tarka Trail at the Chivenor roundabout",
    verified: null,
  },
  {
    slug: "heanton-court",
    name: "Heanton Court",
    kind: "food",
    food: { type: "pub" },
    // Centre of OSM way 142871716.
    lat: 51.09463, lon: -4.12442,
    address: "Braunton Road, Barnstaple, EX31 4AT",
    phone: "01271 816547",
    url: "https://www.vintageinn.co.uk/restaurants/south-west/heantoncourtbarnstaple",
    notes: "Vintage Inns pub in an old manor house, on the estuary side of the Tarka Trail",
    verified: null,
  },
  {
    // Three places on the Strand, recorded together so Barnstaple ranks as the
    // town it is rather than as one isolated café.
    slug: "cafe-on-the-strand-barnstaple",
    name: "The Café on the Strand",
    kind: "food",
    food: { type: "cafe" },
    // OSM node 319117827.
    lat: 51.07917, lon: -4.06148,
    address: "Queen Anne's Walk, The Strand, Barnstaple",
    notes: "In Queen Anne's Walk, on the route by the Long Bridge. The High Street and Pannier Market, 200 m inland, have dozens more",
    verified: null,
  },
  {
    slug: "strand-social-barnstaple",
    name: "The Strand Social",
    kind: "food",
    food: { type: "pub" },
    // Centre of OSM way 1544006524.
    lat: 51.07868, lon: -4.05985,
    address: "The Strand, Barnstaple",
    url: "https://ambertaverns.co.uk/pub/the-strand-social/",
    verified: null,
  },
  {
    slug: "tesco-express-barnstaple",
    name: "Tesco Express",
    kind: "shop",
    shop: { type: "convenience" },
    // Centre of OSM way 1142312396.
    lat: 51.07914, lon: -4.05960,
    address: "100–101 High Street, Barnstaple",
    url: "https://www.tesco.com/store-locator/barnstaple/100-101-high-st",
    notes: "At the foot of the High Street, 100 m from the route",
    verified: null,
  },
  {
    slug: "asda-barnstaple",
    name: "Asda",
    kind: "shop",
    shop: { type: "supermarket" },
    // Centre of OSM way 799046577.
    lat: 51.07761, lon: -4.06643,
    address: "Anchorwood Retail Park, Taw Wharf, Barnstaple",
    url: "https://storelocator.asda.com/south-west/barnstaple/anchorwood-retail-park-taw-wharf",
    notes: "Beside the Tarka Trail just west of the Long Bridge. Has a café",
    verified: null,
  },
  {
    slug: "fremington-quay-cafe",
    name: "Fremington Quay Café",
    kind: "food",
    food: { type: "cafe" },
    // Centre of OSM way 187941408.
    lat: 51.07972, lon: -4.12008,
    address: "Fremington Quay, Fremington, EX31 3AR",
    phone: "01271 378783",
    notes: "In the old station on the Tarka Trail. Dogs welcome outside. Directories give Mon–Fri 9am–4pm, weekends to 5.30pm. Fremington village, 900 m up the lane, has two pubs and a Chinese restaurant",
    verified: null,
  },
  {
    slug: "costcutter-fremington",
    name: "Costcutter, Fremington",
    kind: "shop",
    shop: { type: "convenience" },
    // OSM node 1743759479.
    lat: 51.07203, lon: -4.12626,
    address: "2 Higher Road, Fremington, EX31 3BG",
    phone: "01271 375192",
    notes: "In the village, 600 m inland of the Tarka Trail. Also the post office. Costcutter's locator now links a Co-op here, so the name may have changed",
    verified: null,
  },
  {
    slug: "johns-of-instow",
    name: "Johns of Instow",
    kind: "shop",
    shop: { type: "convenience" },
    food: { type: "cafe" },
    // OSM node 3811358533.
    lat: 51.05097, lon: -4.18050,
    address: "4–5 Marine Parade, Instow, EX39 4HY",
    phone: "01271 860310",
    url: "https://johnsofinstow.co.uk/locations/instow/",
    notes: "Deli and café by Instow quay. Deli 8.15am–5.30pm daily; café kitchen until 4pm. Dog-friendly. A deli, not a grocer: bread, cheese, wine, no basics to speak of",
    verified: "2026-09-13",
  },
  {
    slug: "cafe-du-parc-bideford",
    name: "Café du Parc",
    kind: "food",
    food: { type: "cafe" },
    // OSM node 4382766809.
    lat: 51.02140, lon: -4.20503,
    address: "The Burton, Kingsley Road, Bideford, EX39 2QQ",
    phone: "01237 429317",
    notes: "French café in the Burton gallery, by Victoria Park: crêpes and galettes at lunch, cakes all day. No dogs inside; there's a terrace",
    verified: null,
  },
  {
    slug: "coop-bideford",
    name: "Co-op, Bideford",
    kind: "shop",
    shop: { type: "supermarket" },
    // Centre of OSM way 279585963.
    lat: 51.01833, lon: -4.20540,
    address: "62–63 Mill Street, Bideford, EX39 2JT",
    url: "https://www.coop.co.uk/store-finder/EX39-2JT/62-63-mill-street",
    notes: "50 m up from the Quay. OSM gives Mon–Sat 7am–10pm, Sun 10am–4pm. Morrisons is 250 m further north on Kingsley Road",
    verified: null,
  },
  {
    slug: "johns-of-appledore",
    name: "Johns of Appledore",
    kind: "shop",
    shop: { type: "convenience" },
    // Centre of OSM way 1177290317.
    lat: 51.05249, lon: -4.19111,
    address: "4–7 The Quay, Appledore, EX39 1QS",
    phone: "01237 429065",
    url: "https://johnsofinstow.co.uk/locations/appledore/",
    notes: "Deli, grocer and café on the quay, sister to Johns of Instow. Deli 8.30am–5.30pm daily; café kitchen until 4pm. Dog-friendly. Mostly deli goods; the only shop on the path between Bideford and Westward Ho!",
    verified: "2026-09-13",
  },
  {
    slug: "tesco-express-westward-ho",
    name: "Tesco Express, Westward Ho!",
    kind: "shop",
    shop: { type: "convenience" },
    // Centre of OSM way 609347714.
    lat: 51.04215, lon: -4.23597,
    address: "Golf Links Road, Westward Ho!, EX39 1LH",
    url: "https://www.tesco.com/store-locator/westward-ho/golf-links-rd",
    notes: "7am–10pm daily. Spar and Londis within 150 m",
    verified: null,
  },
  {
    slug: "coach-and-horses-horns-cross",
    name: "Coach and Horses",
    kind: "food",
    food: { type: "pub" },
    // OSM node 1151311880.
    lat: 50.98511, lon: -4.30282,
    address: "A39, Horns Cross, EX39 5DH",
    phone: "01237 451214",
    notes: "Village pub on the A39, up the valley path from Peppercombe. Directories say no food Mondays and Tuesdays. Listed as dog-friendly, though a recent review says dogs are no longer allowed",
    verified: null,
  },
  {
    slug: "clovelly-visitor-centre-cafe",
    name: "Clovelly Visitor Centre café",
    kind: "food",
    food: { type: "cafe" },
    // Centre of OSM way 5899467, the Visitor Centre building.
    lat: 50.99887, lon: -4.40240,
    address: "Clovelly Visitor Centre, EX39 5TA",
    phone: "01237 431781",
    url: "https://www.clovelly.co.uk/",
    notes: "Café-restaurant with a terrace over Bideford Bay, at the top of the village. Summer hours 9am–6pm per Visit Devon; shorter in winter. The Red Lion and New Inn are down in the village, and the Cottage Tearooms on the street",
    verified: null,
  },
  {
    slug: "lower-brownsham-tea-room",
    name: "Lower Brownsham Farm Tea Room",
    kind: "food",
    food: { type: "cafe" },
    // Centre of OSM way 894642321.
    lat: 51.00760, lon: -4.44378,
    address: "Lower Brownsham Farm, Hartland, EX39 6AN",
    phone: "01237 441353",
    notes: "Tea room on a working farm by the National Trust's Brownsham car park, up the woodland paths from Mouth Mill or Windbury Head. Homemade cakes, scones, cream teas, ice cream. Outdoor seating. Days and season not published; ring first",
    verified: null,
  },
  {
    slug: "hartland-point-kiosk",
    name: "The Point Kiosk, Hartland Point",
    kind: "food",
    food: { type: "cafe" },
    // Centre of OSM way 1054843500.
    lat: 51.01937, lon: -4.51803,
    address: "Hartland Point car park, EX39 6AU",
    phone: "07771 590083",
    url: "https://hartlandpointrefreshments.co.uk/",
    notes: "Kiosk on the path by the Hartland Point car park: coffee, sandwiches, soup, cream teas, ice cream, including one for dogs. Outdoor tables only. April to September per the Hartland Peninsula Association; the owner's site gives no season",
    verified: "2026-09-13",
  },
  {
    slug: "bucks-cross-post-office",
    name: "Bucks Cross Post Office",
    kind: "shop",
    shop: { type: "convenience" },
    // Centre of OSM way 308480142.
    lat: 50.98189, lon: -4.35462,
    address: "A39, Bucks Cross, EX39 5DP",
    notes: "Village post office and shop on the A39, up the lane from Bucks Mills. Directories give Mon–Fri 8am–5.30pm, Sat 8am–1pm. What groceries it carries isn't confirmed",
    verified: null,
  },
  {
    slug: "wreckers-retreat",
    name: "Wreckers' Retreat",
    kind: "food",
    food: { type: "pub" },
    // Centre of OSM way 175460868.
    lat: 50.99453, lon: -4.53377,
    address: "Hartland Quay Hotel, Hartland Quay, EX39 6DU",
    phone: "01237 441218",
    url: "https://hartlandquayhotel.co.uk/visit/",
    notes: "The Hartland Quay Hotel's bar, open all year: Mon–Sat 11am–10.30pm, Sun 11am–10pm. Lunch 12–2.30pm, dinner 6–8.30pm; walk-ins taken but booking recommended. Dogs welcome in the bar. The hotel's shop, Easter to October half term, sells ice cream",
    verified: "2026-09-14",
  },
];
