// Hospitals and vets.
//
// Unlike everything else these are matched by "the nearest few, however far" —
// there is always a nearest A&E and you always want to know which it is, even
// when it's an hour away. They get pins, but never widen the map: the nearest
// A&E to this stretch is in Taunton, and fitting it in would zoom the route
// out to nothing.
//
//   hospital.type   "ae"  a full 24/7 emergency department
//                   "utc" urgent treatment centre — the old minor injuries
//                         unit, right for a sprain or a gash, not for a
//                         serious injury
//                   "minor" a GP practice's minor injuries service — nurse-led,
//                         weekdays, ring first. Worth knowing on the doorstep,
//                         but not somewhere you can simply turn up
//   vet.emergency   true | false | null — whether they cover out of hours
export default [
  {
    slug: "minehead-utc",
    name: "Minehead Community Hospital",
    kind: "hospital",
    hospital: { type: "utc" },
    lat: 51.20011, lon: -3.46191,
    address: "Luttrell Way, Minehead, TA24 6DF",
    phone: "01643 701701",
    hours: "8am – 9pm daily, last patient 8.30pm",
    notes: "Urgent treatment centre, not an A&E — right for sprains and cuts. NHS 111 first if you're unsure it's the right place",
    verified: null,
  },
  {
    slug: "musgrove-park",
    name: "Musgrove Park Hospital",
    kind: "hospital",
    hospital: { type: "ae" },
    lat: 51.01157, lon: -3.12170,
    address: "Parkfield Drive, Taunton, TA1 5DA",
    phone: "01823 333444",
    hours: "24 hours, every day",
    notes: "Nearest full A&E to the Somerset end of the path",
    verified: null,
  },
  {
    slug: "north-devon-district",
    name: "North Devon District Hospital",
    kind: "hospital",
    hospital: { type: "ae" },
    lat: 51.09217, lon: -4.05046,
    address: "Raleigh Park, Barnstaple, EX31 4JB",
    phone: "01271 322577",
    hours: "24 hours, every day",
    notes: "Nearest full A&E once you're into Devon; also a designated trauma unit",
    verified: "2026-09-13",
  },
  {
    slug: "white-lodge-minehead",
    name: "White Lodge Veterinary Centre",
    kind: "vet",
    vet: { emergency: true },
    lat: 51.20092, lon: -3.46509,
    address: "Stephenson Road, Alcombe, Minehead",
    phone: "01643 703649",
    url: "https://www.whitelodgevetclinic.co.uk/",
    hours: "Emergencies 24 hours on the same number",
    notes: "8am–7pm handled by the Minehead or Williton practice; 7pm–8am by Somerset Veterinary Emergency Clinic at Bridgwater. Registered clients first — others seen at their discretion, possibly for a higher fee",
    verified: "2026-09-13",
  },
  {
    slug: "charter-barnstaple",
    name: "Charter Veterinary Hospital (CVS Vets 24/7)",
    kind: "vet",
    vet: { emergency: true },
    lat: 51.06500, lon: -4.09262,
    address: "Charter Court, Roundswell, Barnstaple, EX31 3FG",
    phone: "01271 371115",
    url: "https://www.cvsvets.com/south-west/charter-veterinary-hospital",
    hours: "Emergencies 24 hours, every day",
    notes: "Formerly MiNightVet, whose site now redirects to CVS; other practices still send out-of-hours cases to \"MiNightVet Barnstaple\" at this address. Out-of-hours cover for the Ilfracombe practice too",
    verified: "2026-09-13",
  },
  {
    slug: "lyn-health-lynton",
    name: "Lyn Health minor injury service",
    kind: "hospital",
    hospital: { type: "minor" },
    lat: 51.22921, lon: -3.83722,
    address: "Burvill Street, Lynton, EX35 6HA",
    phone: "01598 753226",
    hours: "Mon–Fri, appointments 9am – 5pm. Not at weekends",
    notes: "Nurse-led, at the GP surgery: wounds, burns, bites and stings, sprains, minor head injuries. No walk-ins; ring first or use NHS 111",
    verified: "2026-09-13",
  },
  {
    slug: "combe-coastal-ilfracombe",
    name: "Combe Coastal Practice minor injuries",
    kind: "hospital",
    hospital: { type: "minor" },
    lat: 51.20374, lon: -4.12687,
    address: "Ilfracombe Medical Centre, St Brannocks Road, Ilfracombe, EX34 8EG",
    phone: "01271 863119",
    hours: "Mon–Fri only. 8am – 6.30pm on the practice's site, 8.30am – 6pm in Royal Devon's 2024 notice",
    notes: "Ilfracombe's minor injuries service while the Tyrrell Hospital unit is closed, which Royal Devon calls temporary. Ring first; the duty clinician calls back with a same-day slot. Whether visitors are seen isn't stated",
    verified: "2026-09-13",
  },
  {
    slug: "charter-mullacott",
    name: "Charter Veterinary Centre – Mullacott",
    kind: "vet",
    vet: { emergency: false },
    lat: 51.17762, lon: -4.14603,
    address: "Bickenbridge Farm, Mullacott, Ilfracombe, EX34 8NZ",
    phone: "01271 866770",
    url: "https://www.cvsvets.com/south-west/charter-veterinary-centre-mullacott",
    notes: "Small animals, CVS group. Nights, weekends and bank holidays go to Charter Veterinary Hospital, Barnstaple. Street address from OSM, not the CVS page",
    verified: "2026-09-13",
  },
  {
    slug: "argyll-braunton",
    name: "Argyll Veterinary Centre – Braunton",
    kind: "vet",
    vet: { emergency: false },
    // EX33 2JL via postcodes.io; OSM has no node for it.
    lat: 51.10695, lon: -4.16053,
    address: "28 Exeter Road, Braunton, EX33 2JL",
    phone: "01271 812405",
    url: "https://www.cvsvets.com/south-west/argyll-veterinary-centre-braunton",
    hours: "Mon–Fri 8.30am – 7pm, Sat 9am – 12.30pm",
    notes: "Small animals, CVS group. Nights, weekends and bank holidays go to Charter Veterinary Hospital, Barnstaple. Position is the postcode's, not the building's. Argyll's Ilfracombe branch, still on OSM, closed in 2021",
    verified: "2026-09-13",
  },
  {
    // Centre of OSM way 180169336.
    slug: "torrington-health-centre",
    name: "Torrington Health Centre minor injuries",
    kind: "hospital",
    hospital: { type: "minor" },
    lat: 50.95207, lon: -4.14004,
    address: "New Road, Torrington, EX38 8EL",
    phone: "01805 622247",
    url: "https://torringtonhc.nhs.uk/services/medical-services-and-clinics",
    hours: "Weekdays 8.30am – 6pm, closed 12.15 – 1.15pm. Not at weekends",
    notes: "A GP practice's minor injuries service. Nearest to Instow while Bideford Community Hospital's unit is temporarily closed. Whether visitors are seen, and whether to ring first, isn't stated. Castle Gardens Surgery, 50 m away (01805 623222), runs one too, a sit-down-and-wait service; the two cover each other's lunch hour",
    verified: "2026-09-13",
  },
  {
    slug: "vets4pets-barnstaple",
    name: "Vets4Pets Barnstaple",
    kind: "vet",
    vet: { emergency: false },
    // EX31 2AU via postcodes.io, the station's postcode; OSM has no node.
    lat: 51.07472, lon: -4.06215,
    address: "Inside Pets at Home, Barnstaple Retail Park, Station Road, Barnstaple, EX31 2AU",
    phone: "01271 335520",
    url: "https://www.vets4pets.com/practices/vets4pets-barnstaple/",
    hours: "Mon–Fri 9am – 7pm, Sat 9am – 6pm, closed Sundays",
    notes: "By Barnstaple station, near the path. Out of hours goes to Charter Veterinary Hospital. Position is the postcode's, not the building's",
    verified: "2026-09-13",
  },
  {
    slug: "tarka-vets-barnstaple",
    name: "Tarka Vets",
    kind: "vet",
    vet: { emergency: true },
    // EX32 7AS via postcodes.io; OSM has no node.
    lat: 51.08548, lon: -4.05856,
    address: "St George's House, St George's Road, Barnstaple, EX32 7AS",
    phone: "01271 452660",
    url: "https://www.tarkavets.org/",
    hours: "Mon–Fri 8am – 6pm, Sat 8.30am – 12.30pm. Emergencies 24 hours on the same number",
    notes: "Independent; covers its own emergencies rather than sending them to Charter. Text or WhatsApp 07476 947981. Whether it sees non-clients out of hours isn't stated. Position is the postcode's",
    verified: "2026-09-13",
  },
  {
    slug: "medivet-northam",
    name: "Medivet Northam (Witten Park Vets)",
    kind: "vet",
    vet: { emergency: false },
    // EX39 3QA via postcodes.io; OSM has no node.
    lat: 51.03150, lon: -4.21716,
    address: "Heywood Road, Northam, EX39 3QA",
    phone: "01237 473278",
    url: "https://www.medivetgroup.com/vet-practices/northam/",
    hours: "Mon–Fri 8.30am – 6pm, Sat 9am – 12pm",
    notes: "Emergencies seen here until 7pm every day, then at Charter Veterinary Hospital, Barnstaple; ring this number for a call-back either way. Medivet East-the-Water, Bideford (01237 422657), is weekdays only. Position is the postcode's",
    verified: "2026-09-13",
  },
  {
    slug: "torbridge-bideford",
    name: "Torbridge Veterinary Centre – Bideford",
    kind: "vet",
    vet: { emergency: false },
    // EX39 3DX via postcodes.io; OSM has no node.
    lat: 51.00719, lon: -4.23368,
    address: "7 Caddsdown Industrial Park, Clovelly Road, Bideford, EX39 3DX",
    phone: "01237 472075",
    url: "https://www.cvsvets.com/south-west/torbridge-veterinary-centre-bideford",
    hours: "Mon–Fri 8am – 7pm, Sat 8.30am – 5pm",
    notes: "Small animals, CVS group. Open Saturday afternoons, when Medivet Northam isn't. When closed, Charter Veterinary Hospital, Barnstaple (01271 371115). Position is the postcode's",
    verified: "2026-09-13",
  },
  {
    // Centre of OSM way 175283262.
    slug: "hartland-surgery",
    name: "Hartland Surgery minor injuries",
    kind: "hospital",
    hospital: { type: "minor" },
    lat: 50.99236, lon: -4.48230,
    address: "66 The Square, Hartland, EX39 6BL",
    phone: "01237 441200",
    url: "https://hartlandsurgery.co.uk/about/",
    hours: "Mon–Fri 8am – 6.30pm, Thu until 8pm; reception shut 1–2pm but phones answered. Phones 8.30am – 6pm. Not at weekends",
    notes: "A GP practice's minor injury service: doctors and a nurse see injuries from the last 48 hours — cuts, sprains, bites, minor burns, eye injuries. Ring or call in, for anyone in the Hartland area; seen as soon as possible",
    verified: "2026-09-13",
  },
  {
    // OSM node 984261739.
    slug: "stratton-miu",
    name: "Stratton Community Hospital minor injury unit",
    kind: "hospital",
    hospital: { type: "utc" },
    lat: 50.83055, lon: -4.51761,
    address: "Hospital Road, Stratton, Bude, EX23 9BR",
    phone: "01288 287700",
    // The trust's page also gives 01288 287722.
    url: "https://www.cornwallft.nhs.uk/stratton-community/",
    hours: "24 hours every day on Cornwall's live status page, which also posts closures. 8pm – 8am by calling 111 first",
    notes: "Minor injury unit, not an A&E. Walk in by day; from 8pm to 8am a community treatment centre on the site takes patients through NHS 111. Holsworthy's GP practice calls the unit 111-only, so ring 111 first if in doubt. X-ray Mon, Tue, Wed and Fri 9am – 5pm. Live status: cornwallft.nhs.uk/miu-waiting-times",
    verified: "2026-09-13",
  },
  {
    slug: "tamar-vets-hartland",
    name: "Tamar Vets – Hartland",
    kind: "vet",
    vet: { emergency: true },
    // EX39 6AG via postcodes.io; OSM has no node.
    lat: 50.99009, lon: -4.46936,
    address: "Unit 7, Hartland Industrial Estate, Hartland, EX39 6AG",
    phone: "01288 354796",
    url: "https://www.tamarvets.co.uk/hartland-vets/",
    hours: "Mon, Wed and Fri 4pm – 6pm, by appointment. Emergencies 24 hours on 01288 354796",
    notes: "Branch of Tamar Vets, Bude, which takes the bookings: Mon–Fri 8.30am – 7pm, Sat 9am – 1pm. Branch line 01237 441741. Independent, with its own 24-hour emergency service and nurses on site round the clock; where night cases are seen, and whether non-clients are taken, isn't stated. Position is the postcode's",
    verified: "2026-09-13",
  },
  {
    slug: "tamar-vets-bude",
    name: "Tamar Vets – Bude",
    kind: "vet",
    vet: { emergency: true },
    // Centre of OSM way 722865229, which OSM addresses as Howards Way, EX23 8DY.
    lat: 50.82875, lon: -4.54385,
    address: "9 The Strand, Bude, EX23 8QU",
    phone: "01288 354796",
    url: "https://www.tamarvets.co.uk/contact/",
    hours: "Mon–Fri 8.30am – 7pm, Sat 9am – 1pm. Emergencies 24 hours on the same number",
    notes: "Independent, with branches in Holsworthy and Hartland. Its own vets cover emergencies, with nurses on site 24 hours. Whether non-clients are seen out of hours isn't stated. Second line 01288 355784",
    verified: "2026-09-13",
  },
  {
    slug: "penbode-stratton",
    name: "Penbode Vets – Stratton",
    kind: "vet",
    vet: { emergency: true },
    // OSM node 11009334145.
    lat: 50.82741, lon: -4.52112,
    address: "A39 Hillhead, Stratton, Bude, EX23 9AB",
    phone: "01288 359500",
    url: "https://www.penbodevets.co.uk/contact-us/stratton-branch",
    hours: "Mon–Fri 8am – 6pm, Sat 9am – 5pm. Emergencies 24 hours on the same number",
    notes: "VetPartners group. Its own 24-hour service: out-of-hours calls are passed to a vet, and pets from every Penbode branch are usually seen here, where staff are on site at all times. Whether non-clients are seen isn't stated",
    verified: "2026-09-13",
  },
  {
    slug: "penbode-bradworthy",
    name: "Penbode Vets – Bradworthy",
    kind: "vet",
    vet: { emergency: true },
    // EX22 7SZ via postcodes.io; OSM has no node.
    lat: 50.90123, lon: -4.38554,
    address: "Ashleigh House, Bradworthy, EX22 7SZ",
    phone: "01409 241241",
    url: "https://www.penbodevets.co.uk/contact-us/bradworthy-branch",
    hours: "Mon–Fri 8am – 5pm, alternate Saturdays 8.30am – 1pm. Emergencies 24 hours on the same number or 01288 359500",
    notes: "Small branch, pets and farm. Out of hours a Penbode vet answers, and pets are usually seen at Stratton, near Bude, not here. Position is the postcode's",
    verified: "2026-09-13",
  },
  {
    // Centre of OSM way 1336913592.
    slug: "launceston-miu",
    name: "Launceston Community Hospital minor injury unit",
    kind: "hospital",
    hospital: { type: "utc" },
    lat: 50.62792, lon: -4.35915,
    address: "Link Road, Launceston, PL15 9JD",
    phone: "01566 765600",
    url: "https://www.cornwallft.nhs.uk/launceston-hospital/",
    hours: "Usually 8am – 8pm every day, X-ray Sunday to Friday 9am – 5pm, on the trust's live status page",
    notes: "Minor injury unit, not an A&E: walk in, no appointment. Live waiting times and hours: cornwallft.nhs.uk/miu-waiting-times. Stratton, near Bude, is nearer and open 24 hours",
    verified: "2026-09-14",
  },
  {
    // Emergency department entrance, OSM node 8151096985.
    slug: "derriford",
    name: "University Hospitals Plymouth (Derriford)",
    kind: "hospital",
    hospital: { type: "ae" },
    lat: 50.41680, lon: -4.11320,
    address: "Derriford Road, Crownhill, Plymouth, PL6 8DH",
    phone: "01752 202082",
    url: "https://www.plymouthhospitals.nhs.uk/emergency-department",
    hours: "24 hours, every day",
    notes: "Major trauma centre for the South West peninsula: severe injuries, strokes, heart attacks, neurosurgery. Phone is the switchboard. The 34 from Stonehouse, Cremyll Street, to Derriford Hospital Stand 2 in about 40 minutes, every 30 minutes Mon–Sat and hourly on Sundays",
    verified: "2026-09-14",
  },
  {
    // Emergency entrance, OSM node 10016851800.
    slug: "royal-cornwall-hospital",
    name: "Royal Cornwall Hospital (Treliske)",
    kind: "hospital",
    hospital: { type: "ae" },
    lat: 50.26601, lon: -5.09201,
    address: "Treliske, Truro, TR1 3LJ",
    phone: "01872 250000",
    url: "https://royalcornwallhospitals.nhs.uk/services/emergency-department-ed/",
    hours: "24 hours, every day",
    notes: "Cornwall's emergency department. Walk-in patients use the Minors entrance: the department is on the right of the Trelawny Wing with its own entrance, signed in red. Phone is the switchboard; the department's lines, 01872 253111 and 253113, are for patients already there",
    verified: "2026-09-14",
  },
  {
    // Centre of OSM way 279708712.
    slug: "bodmin-miu",
    name: "Bodmin Community Hospital minor injury unit",
    kind: "hospital",
    hospital: { type: "utc" },
    lat: 50.46762, lon: -4.74216,
    address: "Boundary Road, Bodmin, PL31 2QT",
    phone: "01208 251300",
    url: "https://www.cornwallft.nhs.uk/bodmin-community",
    hours: "Usually 8am – 10pm every day, X-ray 8am – 8pm, on the trust's live status page, which also posts pauses in service",
    notes: "Minor injury unit, not an A&E: walk in, no appointment, injuries from the last 14 days. Live status: cornwallft.nhs.uk/miu-waiting-times",
    verified: "2026-09-14",
  },
  {
    slug: "penbode-camelford",
    name: "Penbode Vets – Camelford",
    kind: "vet",
    vet: { emergency: true },
    // Centre of OSM way 988762867.
    lat: 50.61533, lon: -4.68527,
    address: "Inns Park, Valley Truckle, Camelford, PL32 9RX",
    phone: "01840 213277",
    url: "https://www.penbodevets.co.uk/contact-us/camelford-branch",
    hours: "Mon–Fri 8am – 6pm. Emergencies 24 hours on the same number or 01288 359500",
    notes: "Pets and farm, VetPartners group. The branch page gives Saturday 8.30am – 1pm for the farm side only. Out of hours a Penbode vet answers, and pets are usually seen at Stratton, near Bude, not here. Whether non-clients are seen isn't stated",
    verified: "2026-09-14",
  },
  {
    slug: "nute-wadebridge",
    name: "Nute Veterinary Centre – Wadebridge",
    kind: "vet",
    vet: { emergency: false },
    // PL27 6HB via postcodes.io; OSM has no node.
    lat: 50.52011, lon: -4.82328,
    address: "Higher Trenant Road, Wadebridge, PL27 6HB",
    phone: "01208 813258",
    url: "https://www.cvsvets.com/south-west/nute-veterinary-centre-wadebridge",
    hours: "Mon–Fri 8am – 7pm, Sat 8am – 1pm",
    notes: "Small animals, CVS group. Nights, weekends and bank holidays go to Clifton Villa Veterinary Centre, 53 Henver Road, Newquay, TR7 3DQ (01637 520123), 25 km from Port Isaac; free phone advice first. Whether non-clients are seen isn't stated. Position is the postcode's",
    verified: "2026-09-14",
  },
  {
    slug: "wave-vets-wadebridge",
    name: "Wave Vets",
    kind: "vet",
    vet: { emergency: false },
    // PL27 7AW via postcodes.io; OSM has no node.
    lat: 50.51724, lon: -4.83796,
    address: "Unit 4, Trevanson Street, Wadebridge, PL27 7AW",
    phone: "01208 812099",
    url: "https://wavevets.co.uk/emergencies",
    hours: "Mon–Fri 8.30am – 6pm, Sat 8.30am – 12pm",
    notes: "Independent. Entrance on Goldsworthy Way, opposite the Saltbox and Lidl. Out of hours the answerphone sends you to Beacon VetCare, Chapel Parc, Chapel Town, Summercourt, TR8 5AH (01872 890100), 27 km from Port Isaac in a straight line; pets come back here next morning. Mobile 07500 794648. Whether non-clients are seen isn't stated. Position is the postcode's",
    verified: "2026-09-14",
  },
  {
    slug: "penmellyn-padstow",
    name: "Penmellyn Vets – Padstow & St Merryn",
    kind: "vet",
    vet: { emergency: true },
    // OSM node 11327765577.
    lat: 50.52309, lon: -4.99587,
    address: "Riviera, St Merryn, Padstow, PL28 8NR",
    phone: "01841 520647",
    url: "https://www.padstowvets.com/contact-us",
    hours: "Mon, Tue and Thu 8.30am – 2.30pm; closed Wed, Fri and weekends. Emergencies 24 hours on 01637 880307",
    notes: "In St Merryn, 4.7 km west of Padstow, not in the town. Penmellyn group, part of IVC. Its own vets cover out of hours at Penmellyn's hospital in St Columb Major, where a nurse is on site round the clock. Whether non-clients are seen isn't stated",
    verified: "2026-09-14",
  },
  {
    slug: "penmellyn-st-columb",
    name: "Penmellyn Vets – St Columb Hospital",
    kind: "vet",
    vet: { emergency: true },
    // OSM node 2430578077.
    lat: 50.42771, lon: -4.94038,
    address: "Station Road, St Columb Major, TR9 6BX",
    phone: "01637 880307",
    url: "https://www.penmellynvet.co.uk/emergencies",
    hours: "Mon–Fri 8am – 6.30pm, Sat 8.30am – 4.30pm. Emergencies 24 hours on the same number",
    notes: "Penmellyn's hospital, where its own vets see every branch's out-of-hours cases; a nurse is based there round the clock. 13 km south of Padstow. Whether non-clients are seen isn't stated",
    verified: "2026-09-14",
  },
  {
    // Centre of OSM way 118521679; TR7 1RQ via postcodes.io is 30 m away.
    slug: "newquay-miu",
    name: "Newquay Community Hospital minor injury unit",
    kind: "hospital",
    hospital: { type: "utc" },
    lat: 50.41093, lon: -5.07399,
    address: "St Thomas Road, Newquay, TR7 1RQ",
    phone: "01637 834800",
    url: "https://www.cornwallft.nhs.uk/newquay-community/",
    hours: "Closed until Monday 5 October 2026, then open on fewer days to begin with. The trust's live status page gives its usual hours as Thursday to Tuesday 8am – 6pm, closed Wednesdays; X-ray Mon, Tue, Thu and Fri 9am – 5pm",
    notes: "Minor injury unit, not an A&E: walk in, no appointment, injuries from the last 14 days. Temporarily closed because there aren't enough specialist staff. The trust plans to reopen it from 5 October at the busiest times, and will confirm. Meanwhile it points to Bodmin (8am – 10pm), Camborne Redruth or St Austell. Phone is the hospital's. Live status: cornwallft.nhs.uk/miu-waiting-times",
    verified: "2026-09-14",
  },
  {
    slug: "clifton-villa-newquay",
    name: "Clifton Villa Veterinary Centre (CVS Vets 24/7)",
    kind: "vet",
    vet: { emergency: true },
    // TR7 3DQ via postcodes.io; OSM has no node.
    lat: 50.41830, lon: -5.06253,
    address: "53 Henver Road, Newquay, TR7 3DQ",
    phone: "01637 851122",
    url: "https://www.cvsvets.com/south-west/clifton-villa-veterinary-centre-newquay",
    hours: "Emergencies 24 hours, every day, seen here. Routine hours not given on the page",
    notes: "CVS group, with its own vets and nurses on site through nights, weekends and bank holidays. Free phone advice on 01637 520123, and an emergency consultation arranged if needed. Out-of-hours centre for Nute Veterinary Centre, Wadebridge. Whether non-clients are seen isn't stated. Position is the postcode's",
    verified: "2026-09-14",
  },
  {
    slug: "newquayvet",
    name: "NewquayVet",
    kind: "vet",
    vet: { emergency: false },
    // TR7 2QL via postcodes.io; OSM has no node.
    lat: 50.40482, lon: -5.06216,
    address: "21 + 22 Treloggan Trade Park, Newquay, TR7 2QL",
    phone: "01637 871100",
    url: "https://newquayvet.uk/surgery-hours/",
    hours: "Mon–Fri 9am – 10.30am, 2pm – 3pm and 5pm – 6.30pm; Sat 9am – 12pm. Closed Sundays",
    notes: "Independent. Open surgeries rather than appointments: turn up in surgery hours and wait. Nights, weekends and bank holidays go to CVETS, Cornwall Veterinary Emergency Treatment Service, The Old Dairy, Penstraze, Truro, TR4 8PN (01872 560952), 16 km from Newquay. Whether non-clients are seen isn't stated. Position is the postcode's",
    verified: "2026-09-14",
  },
  {
    slug: "penmellyn-newquay",
    name: "Penmellyn Vets – Newquay",
    kind: "vet",
    vet: { emergency: true },
    // TR7 3EQ via postcodes.io; OSM has no node.
    lat: 50.41796, lon: -5.05458,
    address: "152 Henver Road, Newquay, TR7 3EQ",
    phone: "01637 871695",
    email: "newquayvets@penmellyn.co.uk",
    url: "https://www.newquayvets.com/contact-us",
    hours: "Mon–Fri 8.30am – 6pm, Sat 8.30am – 4.30pm, closed Sundays. Emergencies 24 hours on 01637 880307",
    notes: "Penmellyn group, part of IVC. Its own vets cover out of hours at Penmellyn's hospital in St Columb Major, 10 km inland, where a nurse is on site round the clock. Whether non-clients are seen isn't stated. Position is the postcode's",
    verified: "2026-09-14",
  },
  {
    slug: "beacon-vetcare-newquay",
    name: "Beacon VetCare – Newquay",
    kind: "vet",
    vet: { emergency: true },
    // Centre of OSM way 187795409.
    lat: 50.41734, lon: -5.04476,
    address: "Church Street, St Columb Minor, Newquay, TR7 3ET",
    phone: "01637 695100",
    email: "newquay@beaconvetcare.co.uk",
    url: "https://beaconvetcare.co.uk/newquay/",
    hours: "Mon–Fri 8.30am – 6.30pm, Sat 8.30am – 1.30pm, closed Sundays. Emergencies 24 hours on 01872 890100, press 1",
    notes: "Independent, four branches. Emergencies, overnight and advanced cases go to its referral centre at Chapel Parc, Chapel Town, Summercourt, TR8 5AH, 9 km from Newquay, open 24 hours with a vet and nurse on site. Out-of-hours centre for Wave Vets, Wadebridge. Whether non-clients are seen isn't stated",
    verified: "2026-09-14",
  },
  {
    // Centre of OSM way 545023986.
    slug: "camborne-redruth-miu",
    name: "Camborne Redruth Community Hospital minor injury unit",
    kind: "hospital",
    hospital: { type: "utc" },
    lat: 50.22918, lon: -5.24530,
    address: "Barncoose Terrace, Redruth, TR15 3ER",
    phone: "01209 318000",
    url: "https://www.cornwallft.nhs.uk/camborne-redruth-hospital/",
    hours: "Usually 8am – 10pm every day, doctor-led until 9pm, X-ray 8am – 8pm, on the trust's live status page, which also posts pauses in service",
    notes: "Minor injury unit, not an A&E: walk in, no appointment, injuries from the last 14 days. One of the units the trust points to while Newquay's is closed. Phone is the hospital's. Live status: cornwallft.nhs.uk/miu-waiting-times",
    verified: "2026-09-15",
  },
  {
    slug: "st-clement-perranporth",
    name: "St Clement Veterinary Clinic – Perranporth",
    kind: "vet",
    vet: { emergency: true },
    // OSM node 12461530029.
    lat: 50.34524, lon: -5.15279,
    address: "36a St Pirans Road, Perranporth, TR6 0BJ",
    phone: "01872 572572",
    email: "stclementrequests@gmail.com",
    url: "https://stclementvets.co.uk/facilities/perranporth/",
    hours: "Mon–Thu 8.30am – 5pm, Fri 8.30am – 2pm, by appointment; closed weekends. Emergencies on 01872 223400",
    notes: "Branch of St Clement Veterinary Clinic, St Clement Vean, Truro, TR1 1RN (Mon–Fri 8am – 7pm, Sat 8.30am – 3pm). Between Piran Surf and the Perranporth Inn. In opening hours an emergency is triaged by phone and seen at the Truro branch. On weeknights its own on-call vet answers 01872 223400, at an extra charge; at weekends MiNightVet in Falmouth takes the calls. Whether non-clients are seen isn't stated",
    verified: "2026-09-15",
  },
  {
    slug: "penmellyn-pool",
    name: "Penmellyn Vets – Pool",
    kind: "vet",
    vet: { emergency: true },
    // OSM node 6080285744.
    lat: 50.22819, lon: -5.27031,
    address: "33 Church Road, Pool, Redruth, TR15 3PT",
    phone: "01209 613405",
    email: "poolvets@penmellyn.co.uk",
    url: "https://www.penmellynpool.com/emergencies",
    hours: "Mon–Fri 8.30am – 6pm, Sat 8.30am – 12.30pm, closed Sundays. Emergencies 24 hours on 01637 880307",
    notes: "Penmellyn group, part of IVC. Its own vets cover out of hours at Penmellyn's hospital in St Columb Major, 32 km north-east, where a nurse is on site round the clock. Whether non-clients are seen isn't stated",
    verified: "2026-09-15",
  },
  {
    slug: "vets4pets-camborne",
    name: "Vets for Pets – Camborne",
    kind: "vet",
    vet: { emergency: false },
    // Inside Pets at Home: centre of OSM way 60910969.
    lat: 50.22555, lon: -5.27393,
    address: "Inside Pets at Home, Trevenson Road, Camborne Retail Park, TR15 3PS",
    phone: "01209 712366",
    url: "https://www.vets4pets.com/practices/vets4pets-camborne/",
    hours: "Mon–Fri 9am – 7pm, Sat 9am – 12.30pm, closed Sundays",
    notes: "Locally owned Vets for Pets practice, in Pool between Camborne and Redruth. Out of hours: CVets, The Old Dairy, Penstraze, Truro, TR4 8PN (01872 560952), 10 km north-east, fees from £105.09. Whether non-clients are seen isn't stated",
    verified: "2026-09-15",
  },
  {
    slug: "cornwall-animal-hospital",
    name: "Cornwall Animal Hospital",
    kind: "vet",
    vet: { emergency: null },
    // Centre of OSM way 540384624.
    lat: 50.24848, lon: -5.22334,
    address: "Treleigh Cottage, Treleigh, Redruth, TR16 4AY",
    phone: "01209 313214",
    url: "https://cornwallanimalhospital.org/veterinary-services/",
    hours: "Mon–Fri 8.30am – 6.30pm, Sat 8.30am – 12.30pm, closed Sundays, on the site. OSM gives weekday closing as 5pm",
    notes: "A charity practice for owners who can't pay private fees in full: around half its clients are on means-tested benefits or a state pension, and it helps others on low incomes at its discretion. No out-of-hours arrangement given, and nothing on whether visitors' pets are seen; ring first. Head office 01209 214004",
    verified: "2026-09-15",
  },
  {
    slug: "lamorna-house-camborne",
    name: "Lamorna House Veterinary Centre",
    kind: "vet",
    vet: { emergency: false },
    // Centre of OSM way 573119941, "Lamorna House", amenity=veterinary, with the
    // postcode; East Hill from directories, the practice page gives no address.
    lat: 50.22473, lon: -5.27955,
    address: "East Hill, Tuckingmill, Camborne, TR14 8NQ",
    phone: "01209 713100",
    url: "https://www.cvsvets.com/south-west/lamorna-house-veterinary-centre",
    hours: "Not given on the practice page",
    notes: "Small animals, CVS group, since 1949. Nights, weekends and bank holidays go to CVS Vets 24/7 at Rosemullion Veterinary Hospital, Tregoniggie Industrial Estate, Falmouth, TR11 4SN (01326 761600), 15 km south-east, or Clifton Villa, Newquay (01637 520123); free phone advice first. Whether non-clients are seen isn't stated. Street from directories",
    verified: "2026-09-15",
  },
  {
    slug: "medivet-redruth",
    name: "Medivet Redruth – Monument Vets",
    kind: "vet",
    vet: { emergency: false },
    // TR15 1SS via postcodes.io; OSM has no node.
    lat: 50.24388, lon: -5.21979,
    address: "60 Cardrew Industrial Estate, Cardrew Way, Redruth, TR15 1SS",
    phone: "01209 214737",
    email: "redruth@medivet.co.uk",
    url: "https://www.medivetgroup.com/vet-practices/redruth/",
    hours: "Mon–Fri 8.30am – 6.30pm, Sat 8.30am – 12.30pm",
    notes: "Medivet group: cats, dogs, rabbits and small mammals. Out of hours: CVets, The Old Dairy, Penstraze, Truro, TR4 8PN (01872 560952), 6 km north-east, consultations from £185. Whether non-clients are seen isn't stated. Position is the postcode's",
    verified: "2026-09-15",
  },
  {
    slug: "redruth-vet-surgery",
    name: "Redruth Veterinary Surgery",
    kind: "vet",
    vet: { emergency: false },
    // OSM node 5393374646.
    lat: 50.23893, lon: -5.23157,
    address: "Unit G, Bartles Industrial Estate, North Street, Redruth, TR15 1HR",
    phone: "01209 218801",
    email: "info@redruthvetsurgery.co.uk",
    url: "https://redruthvetsurgery.co.uk/",
    hours: "Mon–Fri 8.30am – 6.30pm, Sat 8.30am – 12.30pm",
    notes: "Independent, owned and run by a registered veterinary nurse. Out of hours: CVets, Penstraze, Truro (01872 560952), 7 km north-east. Whether non-clients are seen isn't stated",
    verified: "2026-09-15",
  },
  {
    // OSM node 2483239857, "Stennack Surgery".
    slug: "stennack-surgery-miu",
    name: "Stennack Surgery minor injuries",
    kind: "hospital",
    hospital: { type: "minor", walk_in: true },
    lat: 50.21078, lon: -5.48468,
    address: "The Old Stennack School, Stennack, St Ives, TR26 1RU",
    phone: "01736 793333",
    url: "https://www.cornwallft.nhs.uk/miu-waiting-times/",
    hours: "Mon–Fri 8am – 8pm, walk in. Not at weekends",
    notes: "St Ives's GP practice, which Cornwall's community trust lists among its minor injury services: walk in for minor injuries only, no appointment. For an illness, NHS 111 first. The practice's own site couldn't be reached to confirm, or to say whether visitors are seen; a search listing quoting its page adds that it opens on some bank holidays, not Christmas Day or Boxing Day",
    verified: null,
  },
  {
    // Centre of OSM way 1409804111, "Bodriggy Surgery"; TR27 4PB via
    // postcodes.io is 15 m away.
    slug: "bodriggy-hayle",
    name: "Bodriggy Health Centre minor injuries",
    kind: "hospital",
    hospital: { type: "minor" },
    lat: 50.18716, lon: -5.41291,
    address: "60 Queensway, Hayle, TR27 4PB",
    phone: "01736 753136",
    url: "https://www.bodriggysurgery.co.uk/clinics-and-services/minor-injury/",
    hours: "Mon–Fri 8am – 6.30pm, phone lines 8.30am – 6pm. Not at weekends",
    notes: "Hayle's GP practice. Sees some minor injuries: sprains and strains, minor burns and scalds, minor head injuries if not unconscious, bites and stings, minor eye injuries, cuts and grazes. Whether that's walk-in or by appointment, and whether visitors are seen, isn't stated: ring first",
    verified: "2026-09-15",
  },
  {
    // Centre of OSM way 308327216, "West Cornwall Hospital (Penzance)".
    slug: "west-cornwall-utc",
    name: "West Cornwall Hospital urgent treatment centre",
    kind: "hospital",
    hospital: { type: "utc" },
    lat: 50.12171, lon: -5.54291,
    address: "St Clare Street, Penzance, TR18 2PF",
    phone: "01736 874000",
    url: "https://royalcornwallhospitals.nhs.uk/services/urgent-treatment-centre-at-west-cornwall-hospital/",
    hours: "Usually 8am – 10pm every day, X-ray 8am – 11pm, on the trust's live waiting-times page",
    notes: "Urgent treatment centre, not an A&E: walk in or call 111. Minor burns and scalds, simple arm and leg fractures, cuts, urinary infections, minor falls. Ground floor: past main reception, turn right. 10pm to 8am, NHS 111; the nearest A&E is Treliske, Truro. Live waits: cornwallft.nhs.uk/miu-waiting-times. Phone is the hospital's",
    verified: "2026-09-15",
  },
  {
    slug: "hayle-vets",
    name: "Hayle Veterinary Surgery",
    kind: "vet",
    vet: { emergency: false },
    // TR27 4DH via postcodes.io; OSM has no node.
    lat: 50.19001, lon: -5.41497,
    address: "84 Commercial Road, Hayle, TR27 4DH",
    phone: "01736 754111",
    email: "info@haylevets.co.uk",
    url: "https://www.haylevets.co.uk/",
    hours: "Mon–Fri 8.30am – 6.30pm, Sat 8.30am – 12pm, closed Sundays",
    notes: "Independent, since 1986. The blue building next to the Cornish Arms on the main road through Hayle. Out of hours: CVets, The Old Dairy, Penstraze, Truro, TR4 8PN (01872 560952), 21 km north-east. Second number 01736 754777. Whether non-clients are seen isn't stated. Position is the postcode's",
    verified: "2026-09-15",
  },
  {
    slug: "animal-vets-hayle",
    name: "Animal Vets – Hayle",
    kind: "vet",
    vet: { emergency: false },
    // TR27 4DY via postcodes.io; OSM has no node.
    lat: 50.19067, lon: -5.40991,
    address: "18 Fore Street, Copperhouse, Hayle, TR27 4DY",
    phone: "01736 755555",
    email: "reception@animalvets.co.uk",
    url: "https://animalvets.co.uk/animal-vets-locations/",
    hours: "Mon–Fri 8am – 6pm, Sat 9am – 1pm, closed Sundays",
    notes: "Independent, family run. On Fore Street opposite Chapel Lane and Church Street. Out of hours ring the usual number: from 6pm on weekdays it goes to one of the practice's own vets, after 6.30pm to C-Vets (CVets, Penstraze, Truro, 21 km north-east). Branch at Lelant. Whether non-clients are seen isn't stated. Position is the postcode's",
    verified: "2026-09-15",
  },
  {
    slug: "animal-vets-lelant",
    name: "Animal Vets – Lelant",
    kind: "vet",
    vet: { emergency: false },
    // TR26 3EU via postcodes.io; OSM has no node.
    lat: 50.18513, lon: -5.44561,
    address: "Units 1 & 2, Trevenwyth Rural Workshops, St Ives Road, Lelant, TR26 3EU",
    phone: "01736 796088",
    email: "reception@animalvets.co.uk",
    url: "https://animalvets.co.uk/animal-vets-locations/",
    hours: "Mon–Fri 9am – 2pm. Saturdays at Hayle only",
    notes: "Branch of Animal Vets, Hayle, on the St Ives road at the Carbis Bay end of Lelant; replaced its Carbis Bay clinic in 2023. Emergencies on the Hayle number, 01736 755555, which goes to C-Vets after 6.30pm. Whether non-clients are seen isn't stated. Position is the postcode's",
    verified: "2026-09-15",
  },
  {
    slug: "medivet-st-ives",
    name: "Medivet St Ives Cornwall – St Ives Veterinary Surgery",
    kind: "vet",
    vet: { emergency: false },
    // OSM node 5619926481, "St Ives Veterinary Surgery", with the postcode.
    lat: 50.20797, lon: -5.48946,
    address: "Trenwith Lane, St Ives, TR26 1DA",
    phone: "01736 798333",
    email: "st.ives.cornwall@medivet.co.uk",
    url: "https://www.medivetgroup.com/vet-practices/st-ives-cornwall/",
    hours: "Mon–Fri 8.30am – 6.30pm. Saturday appointments 8.30am – 12.30pm at Medivet Camborne, Trevithick Road, TR14 8LQ (01209 718281)",
    notes: "Medivet group: cats, dogs and rabbits. Free car park, step-free. Out of hours: CVets, The Old Dairy, Penstraze, Truro, TR4 8PN (01872 560952), 25 km north-east, consultations from £185. Whether non-clients are seen isn't stated",
    verified: "2026-09-15",
  },
  {
    slug: "rosevean-vets-penzance",
    name: "Rosevean Veterinary Practice",
    kind: "vet",
    vet: { emergency: true },
    // TR18 3HU via postcodes.io; OSM has no node.
    lat: 50.12439, lon: -5.53936,
    address: "Rosevean House, Coombe Road, Penzance, TR18 3HU",
    phone: "01736 362215",
    url: "https://www.roseveanvets.co.uk/emergency/",
    hours: "Consultations by appointment, Mon–Fri 8am – 6.30pm, Sat 9am – 1pm, closed Sundays. Emergencies 24 hours on the same number",
    notes: "VetPartners group: pets, horses and farm animals, with inpatient facilities. Runs its own 24-hour emergency service for registered clients; out of hours, ring and follow the recorded instructions, and in hours ring ahead before bringing an emergency in. Initial emergency consultation £277 as a guide. Also takes Regent Court Vets' out-of-hours calls. Whether non-clients are seen isn't stated. Position is the postcode's",
    verified: "2026-09-15",
  },
  {
    slug: "regent-court-vets-penzance",
    name: "Regent Court Veterinary Practice",
    kind: "vet",
    vet: { emergency: false },
    // TR18 4DE via postcodes.io; OSM has no node.
    lat: 50.11504, lon: -5.53594,
    address: "Lower Queen Street, Penzance, TR18 4DE",
    phone: "01736 368768",
    email: "reception@regentcourtvets.co.uk",
    url: "https://www.regentcourtvets.com/emergency",
    hours: "Mon–Fri 8.30am – 6.30pm, Sat 8.30am – 12.30pm, closed Sundays",
    notes: "VetPartners group, a stone's throw from the promenade. Out of hours the practice number diverts to Rosevean Vets, Coombe Road, 1 km north (01736 362215), which gets the notes daily. Directories list a St Just branch; the practice's own site shows only Penzance. Whether non-clients are seen isn't stated. Position is the postcode's",
    verified: "2026-09-15",
  },
  {
    slug: "vets4pets-penzance",
    name: "Vets for Pets – Penzance",
    kind: "vet",
    vet: { emergency: false },
    // Inside Pets at Home: centre of OSM way 760620654. The practice's site
    // gives TR18 3AP, which postcodes.io lists as terminated in 2013; OSM has
    // TR18 3FH on the store.
    lat: 50.12824, lon: -5.51547,
    address: "Inside Pets at Home, Penzance Retail Park, Eastern Green, Penzance",
    phone: "01736 335300",
    url: "https://www.vets4pets.com/practices/vets-in-cornwall/vets-for-pets-penzance/",
    hours: "Mon–Fri 8.30am – 7pm, Sat 8.30am – 3pm, closed Sundays",
    notes: "Locally owned Vets for Pets practice, on the retail park at Eastern Green on the Long Rock side of Penzance. Out of hours: CVets, The Old Dairy, Penstraze, Truro, TR4 8PN (01872 560952), 31 km north-east, minimum fee £142 plus treatment. Whether non-clients are seen isn't stated",
    verified: "2026-09-15",
  },
  {
    slug: "mounts-bay-vets",
    name: "Mounts Bay Vets",
    kind: "vet",
    vet: { emergency: true },
    // TR20 8HX via postcodes.io; OSM has no node.
    lat: 50.13026, lon: -5.50514,
    address: "Units 15D/E, Cuxhaven Way, Longrock Industrial Estate, Long Rock, TR20 8HX",
    phone: "01736 330331",
    email: "enquiries@mountsbayvets.co.uk",
    url: "https://mountsbayvets.co.uk/emergencies/",
    hours: "Mon–Fri 8.30am – 6pm, Sat 9am – 4pm, closed Sundays. Emergencies 24 hours on the same number",
    notes: "Independent, employee-owned, just off the A30 at Long Rock; free parking. Its own vets cover emergencies from Monday 8am to Saturday 4pm, at Long Rock; from Saturday 4pm to Monday morning and on bank holidays MiNightVet, Tregoniggie Industrial Estate, Bickland Water Road, Falmouth, TR11 4SN, 29 km east. The emergency service is for registered clients \"or for holiday makers away from home\". Phone assessment £15; £35 for an unregistered client who can't reach their own vet. Pay at the time. Branch at Porthleven. Position is the postcode's",
    verified: "2026-09-15",
  },
  {
    // Centre of OSM way 64551813, "Helston Community Hospital", with the
    // postcode.
    slug: "helston-miu",
    name: "Helston Community Hospital minor injury unit",
    kind: "hospital",
    hospital: { type: "utc" },
    lat: 50.09181, lon: -5.26491,
    address: "Meneage Road, Helston, TR13 8DR",
    phone: "01326 435900",
    url: "https://www.cornwallft.nhs.uk/helston-community",
    hours: "Usually Mon–Sat 8am – 6pm, closed Sundays, on the trust's live status page, which also posts pauses in service. No X-ray",
    notes: "Minor injury unit, not an A&E: walk in, no appointment, injuries from the last 14 days, run by nurses, paramedics and healthcare assistants. No X-ray here; West Cornwall Hospital, Penzance, has it 8am – 11pm and Camborne Redruth 8am – 8pm. Free parking. Phone is the hospital's; also 01326 435930. Live status: cornwallft.nhs.uk/miu-waiting-times",
    verified: "2026-09-16",
  },
  {
    slug: "mounts-bay-vets-porthleven",
    name: "Mounts Bay Vets – Porthleven",
    kind: "vet",
    vet: { emergency: false },
    // TR13 9JY via postcodes.io; OSM has no node.
    lat: 50.08574, lon: -5.31739,
    address: "The Shipyard, Porthleven, TR13 9JY",
    phone: "01736 330331",
    email: "enquiries@mountsbayvets.co.uk",
    url: "https://mountsbayvets.co.uk/",
    hours: "Mon, Wed and Fri 2.30pm – 5.30pm only. Emergencies 24 hours on the same number",
    notes: "Branch clinic of Mounts Bay Vets, Long Rock, at the Shipyard Market; free parking outside. Emergencies aren't seen here: from Monday 8am to Saturday 4pm at Long Rock, 14 km west; from Saturday 4pm to Monday morning and on bank holidays MiNightVet, Falmouth, 18 km east. The emergency service is for registered clients \"or for holiday makers away from home\". Position is the postcode's",
    verified: "2026-09-16",
  },
  {
    slug: "rosemullion-vets-helston",
    name: "Rosemullion Veterinary Centre – Helston",
    kind: "vet",
    vet: { emergency: false },
    // TR13 8RR via postcodes.io; OSM has no node.
    lat: 50.09962, lon: -5.27472,
    address: "Isaac House, Tyacke Road, Helston, TR13 8RR",
    phone: "01326 572596",
    url: "https://www.cvsvets.com/south-west/rosemullion-veterinary-centre-helston",
    hours: "Mon–Fri 9am – 7pm, Sat 9am – 5pm, closed Sundays",
    notes: "Small animals, CVS group, since 1885. Small car park, and a pay and display nearby whose ticket they refund. Nights, weekends and bank holidays go to CVS Vets 24/7 at Rosemullion Veterinary Hospital, Tregoniggie Industrial Estate, Bickland Water Road, Falmouth, TR11 4SN (01326 761600), 14 km east; free phone advice first. Whether non-clients are seen isn't stated. Position is the postcode's",
    verified: "2026-09-16",
  },
  {
    slug: "head-and-head-helston",
    name: "Head & Head Vets",
    kind: "vet",
    vet: { emergency: false },
    // TR13 0LW via postcodes.io; OSM has no node.
    lat: 50.11320, lon: -5.26977,
    address: "Water-ma-Trout, Helston, TR13 0LW",
    phone: "01326 572216",
    email: "info@headandhead.co.uk",
    url: "https://www.headandhead.co.uk/emergency",
    hours: "Mon 8.30am – 5.30pm, Tue–Thu 8.30am – 6pm, Fri 8.30am – 5.30pm, Sat 8.30am – 12.30pm, closed Sundays, on its emergency page; the contact page gives 6pm every weekday",
    notes: "VetPartners group, in Helston since the 1870s, at Water-ma-Trout since 1988. In hours, ring ahead before bringing an emergency in. Out of hours: CVets, The Old Dairy, Penstraze, Truro, TR4 8PN (01872 560952), 20 km north-east, initial emergency consultation from £150. Whether non-clients are seen isn't stated. Position is the postcode's",
    verified: "2026-09-16",
  },
  {
    // Centre of OSM way 138246917, "Falmouth Hospital", with the postcode.
    slug: "falmouth-miu",
    name: "Falmouth Community Hospital minor injury unit",
    kind: "hospital",
    hospital: { type: "utc" },
    lat: 50.15570, lon: -5.08618,
    address: "Falmouth, TR11 2JA",
    phone: "01326 436600",
    url: "https://www.cornwallft.nhs.uk/falmouth-community",
    hours: "Every day 8am – 8pm on the trust's live status page, which also posts pauses in service. X-ray Mon, Wed and Fri 9am – 5pm",
    notes: "Minor injury unit, not an A&E: walk in, no appointment, injuries from the last 14 days, run by nurses, paramedics and healthcare assistants. Open on Sundays and has X-ray three days a week, which Helston's has neither of. A heating upgrade expected to take up to 18 months has moved the unit into temporary rooms; signs on arrival. Free parking. Live status: cornwallft.nhs.uk/miu-waiting-times",
    verified: "2026-09-16",
  },
  {
    // Centre of OSM way 1252508003, "Rosemullion Veterinary Practice", Bickland
    // Water Road, TR11 4SN.
    slug: "rosemullion-vets-falmouth",
    name: "Rosemullion Veterinary Hospital – Falmouth",
    kind: "vet",
    vet: { emergency: true },
    lat: 50.15472, lon: -5.09871,
    address: "Tregoniggie Industrial Estate, Bickland Water Road, Falmouth, TR11 4SN",
    phone: "01326 313991",
    url: "https://www.cvsvets.com/south-west/rosemullion-veterinary-hospital-falmouth",
    hours: "24 hours every day for emergencies, with vets and nurses on site overnight",
    notes: "Small animal hospital, CVS group, since 1885; on-site parking and disabled access. A CVS Vets 24/7 centre, taking nights, weekends and bank holidays for Rosemullion Helston: ring first, free phone advice, on 01326 761600. Whether non-clients are seen isn't stated",
    verified: "2026-09-16",
  },
  {
    // Centre of OSM way 184199043, "Health Centre", TR12 6PB; postcodes.io
    // puts the postcode 35 m west.
    slug: "st-keverne-health-centre",
    name: "St Keverne Health Centre minor injuries",
    kind: "hospital",
    hospital: { type: "minor" },
    lat: 50.04857, lon: -5.09078,
    address: "Polventon Parc, St Keverne, TR12 6PB",
    phone: "01326 280761",
    url: "https://www.stkevernehealthcentre.co.uk/health-information/minor-injuries/",
    hours: "Mon–Fri 8am – 6.30pm, phones and reception, on the practice's contact page. Not at weekends",
    notes: "St Keverne's GP practice. Its site says it deals with minor injuries, but a suspected broken bone should go straight to an emergency department. It isn't on Cornwall's community trust's list of minor injury services, and the site doesn't say whether visitors are seen or walk-ins taken, so ring first. The 36 from Coverack Car Park calls at the Health Centre stop, 7 minutes, Mon–Sat. Closed from 1pm on Wednesday 30 Sep 2026 for training",
    verified: "2026-09-16",
  },
  // Section 29.
  {
    slug: "cornish-paws-penryn",
    name: "Cornish Paws",
    kind: "vet",
    vet: { emergency: true },
    // TR10 8NT via postcodes.io, the postcode its own site's map uses; OSM has no
    // node. By Penryn Rugby Club's car park.
    lat: 50.16641, lon: -5.11457,
    address: "Off Penryn Rugby Club car park, Penryn, TR10 8NT",
    phone: "01326 450900",
    email: "info@cornishpaws.co.uk",
    url: "https://www.cornishpaws.co.uk/",
    hours: "Mon, Tue and Fri 8am – 6.30pm, Wed 8am – 7.30pm, Thu 8.30am – 6.30pm, Sat 8.30am – 12.30pm; Sundays emergencies only. Emergencies 24 hours on the same line",
    notes: "Independent, family run. Dogs, cats and exotic pets. Free parking outside, and three spaces kept for out-of-hours visits; separate dog and cat waiting areas, a courtyard for nervous dogs to wait in, full disabled access. Out of hours the phones go to CVS Vets 24/7 at Rosemullion Veterinary Hospital, Falmouth. Whether non-clients are seen isn't stated. Position is the postcode's",
    verified: "2026-09-16",
  },
  {
    slug: "vets4pets-falmouth",
    name: "Vets for Pets – Falmouth",
    kind: "vet",
    vet: { emergency: false },
    // Inside Pets at Home: centre of OSM way 628689112, at Ponsharden. Its site
    // gives TR10 8AB.
    lat: 50.16467, lon: -5.08999,
    address: "Inside Pets at Home, Ponsharden Roundabout, Falmouth Road, Falmouth, TR10 8AB",
    phone: "01326 373030",
    url: "https://www.vets4pets.com/practices/vets-in-cornwall/vets4pets-falmouth/",
    hours: "Mon–Fri 9am – 6.30pm, Sat 9am – 12.30pm, closed Sundays; phones from 8.30am",
    notes: "Locally owned Vets for Pets practice inside Pets at Home at Ponsharden, between Falmouth and Penryn; parking. Out of hours: CVS Vets 24/7, Rosemullion Veterinary Hospital, Tregoniggie Industrial Estate, Bickland Water Road, Falmouth, TR11 4SN (01326 761600), fee £209.80 before 10pm and £277.60 after. Whether non-clients are seen isn't stated",
    verified: "2026-09-16",
  },
  {
    slug: "rosemullion-vets-penryn",
    name: "Rosemullion Veterinary Centre – Penryn",
    kind: "vet",
    vet: { emergency: false },
    // TR10 8LF via postcodes.io, from the practice's page; OSM has no node.
    lat: 50.16533, lon: -5.10184,
    address: "Parc Briwer, Penryn, TR10 8LF",
    phone: "01326 378080",
    url: "https://www.cvsvets.com/south-west/rosemullion-veterinary-practice-penryn",
    hours: "Mon–Fri 9am – 5pm, closed weekends, from the page's structured data",
    notes: "Small animals, CVS group; on-site parking. In hours, ring the practice in an emergency. Nights, weekends and bank holidays go to CVS Vets 24/7 at Rosemullion Veterinary Hospital, Falmouth (01326 761600), with free phone advice first. Whether non-clients are seen isn't stated. Position is the postcode's",
    verified: "2026-09-16",
  },
  // Section 30.
  {
    // St Austell Hospital bus stop (0800COC31476, OSM node 8979993212) is 30 m
    // away: the 24, 25 and 24A.
    // Centre of OSM way 970367232, "St Austell Community Hospital"; the trust
    // gives PL26 6AA, which postcodes.io puts 40 m south-east.
    slug: "st-austell-miu",
    name: "St Austell Community Hospital minor injury unit",
    kind: "hospital",
    hospital: { type: "utc" },
    lat: 50.32740, lon: -4.77343,
    address: "Porthpean Road, St Austell, PL26 6AA",
    phone: "01726 873000",
    url: "https://www.cornwallft.nhs.uk/st-austell",
    hours: "Every day 8am – 8pm on the trust's live status page, which also posts pauses in service. X-ray Mon–Sat 9am – 5pm",
    notes: "Minor injury unit, not an A&E: walk in, no appointment, injuries from the last 14 days, run by nurses, paramedics and healthcare assistants. X-ray six days a week. Free parking. Live status: cornwallft.nhs.uk/miu-waiting-times. The St Austell Hospital bus stop is at the entrance: the 24 and 25 from St Austell bus station, Mon–Sat, about 10 minutes, and the 24A on Sundays",
    verified: "2026-09-16",
  },
  {
    slug: "st-clement-truro",
    name: "St Clement Veterinary Clinic – Truro",
    kind: "vet",
    vet: { emergency: true },
    // TR1 1RN via postcodes.io; OSM has no node.
    lat: 50.27178, lon: -5.03408,
    address: "St Clement Vean, Truro, TR1 1RN",
    phone: "01872 223400",
    email: "stclementrequests@gmail.com",
    url: "https://stclementvets.co.uk/services/emergencies/",
    hours: "Mon–Fri 8am – 7pm, Sat 8.30am – 3pm. Emergencies on the same number",
    notes: "On the outskirts of Truro, purpose built, with a car park and disabled access. In opening hours an emergency is triaged by phone and brought here. On weeknights its own on-call vet answers, at an extra charge; at weekends MiNightVet in Falmouth takes the calls. Branch at Perranporth. Whether non-clients are seen isn't stated. Position is the postcode's",
    verified: "2026-09-16",
  },
  {
    slug: "city-road-vets-truro",
    name: "City Road Veterinary Centre",
    kind: "vet",
    vet: { emergency: null },
    // Centre of OSM way 656021018, "City Road Veterinary Centre", TR1 2JL.
    lat: 50.26189, lon: -5.05621,
    address: "City Road, Truro, TR1 2JL",
    phone: "01872 273959",
    email: "reception@cityroadvets.co.uk",
    url: "https://cityroadvets.co.uk/",
    hours: "By appointment: Mon–Fri 8am – 6.30pm, Sat 8am – 2pm. Sundays and bank holidays 9am – 11am, urgent cases only, not Christmas Day or Boxing Day",
    notes: "Independent, family owned and run; says it's Cornwall's longest established independent vets. Small animals, birds and exotics. The site says nothing about nights or who covers out of hours, so ring. Whether non-clients are seen isn't stated",
    verified: "2026-09-16",
  },
  // Sections 31 and 32.
  {
    slug: "beacon-vetcare-par",
    name: "Beacon VetCare – Par",
    kind: "vet",
    vet: { emergency: true },
    // Centre of OSM way 1363607418, "Beacon VetCare", Polmear Hill, PL24 2AR;
    // postcodes.io puts the postcode 110 m east.
    lat: 50.34991, lon: -4.68983,
    address: "Polmear Hill, Par, PL24 2AR",
    phone: "01726 212300",
    email: "par@beaconvetcare.co.uk",
    url: "https://beaconvetcare.co.uk/par/",
    hours: "Mon–Fri 8.30am – 6.30pm, Sat 8.30am – 1.30pm, closed Sundays. Emergencies 24 hours on 01872 890100, press 1",
    notes: "Independent, by the beach at Par: four consulting rooms, x-ray, ultrasound and theatre. Emergencies, overnight and advanced cases go to its referral centre at Chapel Parc, Chapel Town, Summercourt, TR8 5AH, 21 km inland, open 24 hours with a vet and nurse on site. Fully accessible. Whether non-clients are seen isn't stated",
    verified: "2026-09-16",
  },
  {
    slug: "beacon-vetcare-st-austell",
    name: "Beacon VetCare – St Austell",
    kind: "vet",
    vet: { emergency: true },
    // PL25 3JN via postcodes.io; OSM has no node. Off Bucklers Lane, Holmbush.
    lat: 50.34325, lon: -4.75979,
    address: "Bucklers Lane, St Austell, PL25 3JN",
    phone: "01726 212100",
    email: "staustell@beaconvetcare.co.uk",
    url: "https://beaconvetcare.co.uk/st-austell/",
    hours: "Mon–Fri 8.30am – 6.30pm, closed weekends. Emergencies 24 hours on 01872 890100, press 1",
    notes: "Independent, Beacon VetCare's newest branch: three consulting rooms, x-ray and theatre. Emergencies, overnight and advanced cases go to its referral centre at Chapel Parc, Chapel Town, Summercourt, TR8 5AH, 16 km away, open 24 hours with a vet and nurse on site. Not open on Saturdays, unlike Par. Whether non-clients are seen isn't stated. Position is the postcode's",
    verified: "2026-09-16",
  },
  {
    slug: "penmellyn-st-austell",
    name: "Penmellyn Vets – St Austell",
    kind: "vet",
    vet: { emergency: true },
    // Centre of OSM way 1357864293, "Penmellyn Vets"; its site gives 54A Holmbush
    // Road, PL25 3LQ, which postcodes.io puts 140 m west.
    lat: 50.33903, lon: -4.75993,
    address: "54A Holmbush Road, St Austell, PL25 3LQ",
    phone: "01726 77777",
    email: "staustellvets@penmellyn.co.uk",
    url: "https://www.staustellvet.co.uk/emergencies",
    hours: "Mon–Fri 8.30am – 6pm, Sat 8.30am – 4.30pm, closed Sundays. Emergencies 24 hours on 01637 880307",
    notes: "Penmellyn group, part of IVC. Its own vets cover out of hours at Penmellyn's hospital in St Columb Major, 16 km away, where a nurse is on site round the clock; clinical notes are shared between practices. Disabled parking, wheelchair access and toilets. Whether non-clients are seen isn't stated",
    verified: "2026-09-16",
  },
  {
    slug: "pelyn-vets-st-austell",
    name: "Pelyn Vets – St Austell",
    kind: "vet",
    vet: { emergency: true },
    // Centre of OSM way 1090602831, "Pelyn Vets", King's Avenue, PL25 4TT.
    lat: 50.33840, lon: -4.78640,
    address: "8 Kings Avenue, St Austell, PL25 4TT",
    phone: "01726 68177",
    email: "admin@kernowvetgroup.co.uk",
    url: "https://www.kernowvetgroup.com/about-us/emergencies",
    hours: "Mon–Fri 8.30am – 6.30pm, Sat 8.30am – 12.30pm, closed Sundays. Emergencies 24 hours on 01208 872254",
    notes: "Kernow Veterinary Group, part of IVC, near St Austell bus and railway stations. Out of hours an answering service takes details and the duty vet rings back; if the pet needs seeing it's at Pelyn Vets, Edgecumbe Road, Lostwithiel, PL22 0DZ, 10 km away, or Penmellyn Vets, St Columb Major, 15 km, depending on who's on duty. The group's other St Austell branch, Churchend on Trevarthian Road, has been temporarily closed since 3 July 2026. Whether non-clients are seen isn't stated",
    verified: "2026-09-16",
  },
  {
    slug: "vets4pets-st-austell",
    name: "Vets for Pets – St Austell",
    kind: "vet",
    vet: { emergency: false },
    // Inside Pets at Home: OSM node 14061944471, "Vets4Pets", at Pentewan Retail
    // Park. Its site gives PL25 5BU, which postcodes.io puts 30 m west.
    lat: 50.33215, lon: -4.79318,
    address: "Inside Pets at Home, Unit 2B Pentewan Retail Park, Pentewan Road, St Austell, PL25 5BU",
    phone: "01726 626820",
    url: "https://www.vets4pets.com/practices/vets-in-cornwall/vets-for-pets-st-austell/",
    hours: "Mon–Fri 9am – 7pm, Sat 9am – 6pm, closed Sundays",
    notes: "Locally owned Vets for Pets practice inside Pets at Home, on the Pentewan road out of St Austell; parking. Out of hours: Beacon VetCare, Chapel Parc, Chapel Town, Summercourt, TR8 5AH (01872 890100), consultation fee £150 7pm – 10pm and £180 10pm – 8am, paid at the time. Whether non-clients are seen isn't stated",
    verified: "2026-09-16",
  },
  // Sections 33 and 34.
  {
    // Centre of OSM way 159098120, "Liskeard Community Hospital", PL14 3XD;
    // postcodes.io puts the postcode 29 m away.
    slug: "liskeard-miu",
    name: "Liskeard Community Hospital minor injury unit",
    kind: "hospital",
    hospital: { type: "utc" },
    lat: 50.46182, lon: -4.45090,
    address: "Clemo Road, Liskeard, PL14 3XD",
    phone: "01579 373500",
    url: "https://www.cornwallft.nhs.uk/liskeard-community",
    hours: "Every day 8am – 8pm on the trust's live status page. X-ray Mon–Sat 9am – 5pm, not bank holidays",
    notes: "Minor injury unit, not an A&E: walk in, no appointment, injuries from the last 14 days, run by nurses, paramedics and healthcare assistants. Free parking. Phone is the hospital's. Live status: cornwallft.nhs.uk/miu-waiting-times",
    verified: "2026-09-16",
  },
  {
    // Centre of OSM way 384290896, "Urgent Treatment Centre, Cumberland Centre",
    // PL1 4JZ; postcodes.io puts the postcode 62 m away. OSM's opening_hours
    // (to 22:00) are out of date. Section 35's research may add this too.
    slug: "cumberland-centre-utc",
    name: "Urgent Treatment Centre, Cumberland Centre",
    kind: "hospital",
    hospital: { type: "utc" },
    lat: 50.36991, lon: -4.16874,
    address: "Damerel Close, Plymouth, PL1 4JZ",
    phone: "01752 434390",
    url: "https://www.plymouthhospitals.nhs.uk/miu-at-the-cumberland-centre",
    hours: "8am – 8pm, 7 days a week. X-ray 8am – 8pm, 7 days",
    notes: "Urgent treatment centre, not an A&E: drop in, no appointment. Nurse practitioners see anyone over 1 year old, x-ray over 2: fractures, sprains, minor head injuries, burns, bites and stings, cuts. Free on-site parking. In Devonport, across the Tamar from Torpoint. The 34 stops 85 m away at Mount Wise Village by the Sea, 3 minutes from Cremyll Street at Admiral's Hard, where the Cremyll ferry lands",
    verified: "2026-09-16",
  },
  {
    // OSM node 9882873464, "Luxstowe Vets"; the practice gives PL13 2ES, which
    // postcodes.io puts 18 m away.
    slug: "luxstowe-vets-looe",
    name: "Luxstowe Vets – Looe",
    kind: "vet",
    vet: { emergency: true },
    lat: 50.35330, lon: -4.45629,
    address: "The Quay, West Looe, PL13 2ES",
    phone: "01579 342120",
    url: "https://www.luxstowevet.co.uk/branches/looe",
    hours: "Tue and Thu 2.30pm – 5pm only, non-urgent appointments; the home page gives 2pm – 5.30pm and says times may vary. Emergencies 24 hours on 01579 342120, press 1",
    notes: "A small branch on the quay in West Looe, part of VetPartners; operations are done at Liskeard. Luxstowe runs its own 24-hour emergency service, seen at its Liskeard practice. Whether non-clients are seen isn't stated",
    verified: "2026-09-16",
  },
  {
    // Centre of OSM way 893972649, "Luxstowe Vets", PL14 3QF; postcodes.io puts the
    // postcode 8 m away.
    slug: "luxstowe-vets-liskeard",
    name: "Luxstowe Vets – Liskeard",
    kind: "vet",
    vet: { emergency: true },
    lat: 50.45821, lon: -4.46181,
    address: "Luxstowe, Liskeard, PL14 3QF",
    phone: "01579 342120",
    url: "https://www.luxstowevet.co.uk/emergency",
    hours: "Mon–Fri 8.30am – 6pm, Sat 8.30am – 12.30pm. Emergencies 24 hours on 01579 342120, press 1; bank holidays emergencies only",
    notes: "Luxstowe's main practice, part of VetPartners, where all its operations are done and all its out-of-hours emergencies are seen, by its own team rather than an outside service. Branches at West Looe and Torpoint. Whether non-clients are seen isn't stated",
    verified: "2026-09-16",
  },
  {
    // PL11 2BS via postcodes.io, from the practice's page; OSM has no node.
    slug: "luxstowe-vets-torpoint",
    name: "Luxstowe Vets – Torpoint",
    kind: "vet",
    vet: { emergency: true },
    lat: 50.37483, lon: -4.19593,
    address: "4 Eliot Square, Torpoint, PL11 2BS",
    phone: "01579 342120",
    url: "https://www.luxstowevet.co.uk/branches/torpoint",
    hours: "Mon–Thu 9.30am – 1pm and 2.30pm – 6pm, Fri 9.30am – 1pm and 2.30pm – 5pm, non-urgent appointments; closed weekends. Emergencies 24 hours on 01579 342120, press 1",
    notes: "Branch of Luxstowe Vets, part of VetPartners, near the Torpoint ferry; operations are done at Liskeard, and out-of-hours emergencies are seen at Liskeard, 21 km away. Whether non-clients are seen isn't stated. Position is the postcode's",
    verified: "2026-09-16",
  },
  {
    // OSM node 1762056796, "Pelyn Veterinary Group"; the group gives PL22 0DZ, which
    // postcodes.io puts 15 m away.
    slug: "pelyn-vets-lostwithiel",
    name: "Pelyn Vets – Lostwithiel",
    kind: "vet",
    vet: { emergency: true },
    lat: 50.40046, lon: -4.69040,
    address: "Edgecumbe Road, Nomansland, Lostwithiel, PL22 0DZ",
    phone: "01208 872254",
    url: "https://www.kernowvetgroup.com/about-us/emergencies",
    hours: "Mon–Fri 8.30am – 6.30pm, Sat 8.30am – 12.30pm, closed Sundays. Emergencies 24 hours on the same number",
    notes: "Kernow Veterinary Group, part of IVC. Out of hours an answering service takes details and the duty vet rings back; if the pet needs seeing it's here or at Penmellyn Vets, St Columb, TR9 6BX, depending on who's on duty. Whether non-clients are seen isn't stated",
    verified: "2026-09-16",
  },
  // Section 35.
  {
    // Centre of OSM way 1005807475 "Rosehill Vets", PL1 5PF; postcodes.io puts the
    // postcode 3 m away.
    slug: "rosehill-vets-plymouth",
    name: "Rosehill Vets",
    kind: "vet",
    vet: { emergency: true },
    lat: 50.37677, lon: -4.16083,
    address: "61 Molesworth Road, Stoke, Plymouth, PL1 5PF",
    phone: "01752 562575",
    url: "https://www.rosehillvets.co.uk/",
    hours: "Mon–Fri 8am – 7pm, Sat 9am – 1.30pm, closed Sundays. Out of hours ring 01752 702646",
    notes: "Part of IVC. Out of hours, ring first, then go to Plymouth Veterinary Hospital, 26 William Prance Road, Derriford, PL6 5WR. On the Plymouth side of the Tamar, north of Stonehouse. Whether non-clients are seen isn't stated",
    verified: "2026-09-16",
  },
  {
    // Centre of OSM way 506686915 "Woodlands Veterinary Hospital"; CVS gives
    // 12 Burnett Road, PL6 5BH, which postcodes.io puts 170 m away.
    slug: "woodlands-vets-plymouth",
    name: "Woodlands Veterinary Hospital",
    kind: "vet",
    vet: { emergency: true },
    lat: 50.40081, lon: -4.13200,
    address: "12 Burnett Road, Plymouth, PL6 5BH",
    phone: "01752 700600",
    url: "https://www.cvsvets.com/south-west/minightvet-plymouth",
    hours: "Open 24 hours every day for emergencies: ring first. Routine hours not given on the page",
    notes: "Veterinary hospital, part of CVS, and a CVS Vets 24/7 centre with its own night staff on site: free telephone advice and emergency consultations through the night, weekends and bank holidays. In Manadon, north Plymouth. Whether non-clients are seen isn't stated",
    verified: "2026-09-16",
  },
  // Section 36.
  {
    // PL21 0AJ via postcodes.io, from the practice's own page. There is no
    // minor injury unit east of the Plym: this GP service at Ivybridge is the
    // nearest thing, and the Cumberland Centre is both nearer to Warren Point
    // and better equipped.
    slug: "ivybridge-minor-injury",
    name: "Beacon Medical Group minor injury service",
    kind: "hospital",
    hospital: { type: "minor" },
    lat: 50.39222, lon: -3.92063,
    address: "Ivybridge Health Centre, Station Road, Ivybridge, PL21 0AJ",
    phone: "01752 690777",
    url: "https://www.beaconmedicalgroup.nhs.uk/health-information/minor-injuries/",
    hours: "Mon–Fri 8am – 6pm. Ring first: no walk-ins",
    notes: "A GP practice's minor injury service, not a unit: ring 01752 690777, ask for the Minor Injury Service, and a patient advisor checks you meet the criteria before booking a same-day appointment. \"The Minor Injury Service is available to all\" — non-patients fill in a temporary resident form on arrival. Injuries within 48 hours: sprains and strains, hand injuries, eye injuries, cuts, burns, foreign bodies, bites, head injuries with no loss of consciousness. No x-ray at all; the practice sends you to the Cumberland Centre or Derriford for that. Nothing nearer Wembury than the Cumberland Centre, which is open 8am – 8pm every day and does have x-ray",
    verified: "2026-09-16",
  },
  // Optional, and really section 38's: 19.7 km from Warren Point, so it won't
  // reach section 36's nearest three, but it is the only walk-in unit in the
  // South Hams and will matter from Bigbury on.
  {
    // TQ7 1AT via postcodes.io, from the trust's own page. Run by University
    // Hospitals Plymouth, not Torbay and South Devon: Livewell's page says "the
    // minor injury units in Plymouth, Kingsbridge and South Hams are now
    // delivered by University Hospitals Plymouth".
    slug: "south-hams-miu",
    name: "South Hams Hospital minor injury unit",
    kind: "hospital",
    hospital: { type: "utc" },
    lat: 50.28869, lon: -3.77885,
    address: "South Hams Hospital, Plymouth Road, Kingsbridge, TQ7 1AT",
    phone: "01548 852349",
    url: "https://www.plymouthhospitals.nhs.uk/miu-at-south-hams-hospital",
    hours: "8.30am – 5.30pm, 7 days a week. X-ray Mon–Fri 9am – 5pm only, none at weekends or on bank holidays",
    notes: "Minor injury unit, not an A&E: \"you do not need to pre-book an appointment, just drop-in\". Nurse-practitioner led — cuts, small burns and scalds, bites and stings, sprains and some limb fractures, minor head injuries, infected wounds, foreign bodies in eyes. Free but limited parking. Livewell's page and Modbury Health Centre both give 9am – 5pm; the trust's own page gives 8.30am – 5.30pm",
    verified: "2026-09-16",
  },
  {
    // OSM node 619558354, "Pets at Home", Friary Retail Park, inside which the
    // practice sits. The PL4 0HD on Vets4Pets' own page is a postcode
    // terminated in 2014, so the OSM node is the position rather than
    // postcodes.io. The nearest vet to the Barbican.
    slug: "vets4pets-plymouth",
    name: "Vets4Pets Plymouth",
    kind: "vet",
    vet: { emergency: true },
    lat: 50.37149, lon: -4.12879,
    address: "Unit 1B, Friary Retail Park, Exeter Street, Plymouth, PL4 0HD",
    phone: "01752 235140",
    url: "https://www.vets4pets.com/practices/vets-in-plymouth/vets-for-pets-plymouth/",
    hours: "Mon–Fri 9am – 7pm, Sat 9am – 3pm, closed Sundays",
    notes: "Inside Pets at Home at Friary Retail Park, a few minutes from the Barbican and the nearest vet to it. Out of hours, MiNightVet Plymouth at Woodlands Veterinary Group, 12 Burnett Road, Derriford, PL6 5WR — 01752 754900. Taking new clients; whether non-clients are seen isn't stated. The postcode on its own page was terminated in 2014",
    verified: "2026-09-16",
  },
  {
    // PL9 7HX via postcodes.io, from the practice's own contact page; OSM way
    // 1241650221 puts it 50 m away. The nearest vet to where the path crosses
    // Laira Bridge and turns for Hooe.
    slug: "ocean-city-vets",
    name: "Ocean City Vets",
    kind: "vet",
    vet: { emergency: true },
    lat: 50.36677, lon: -4.10234,
    address: "15 Billacombe Road, Plymouth, PL9 7HX",
    phone: "01752 659202",
    email: "contact@oceancityvets.co.uk",
    url: "https://www.oceancityvets.co.uk/contact-us/",
    hours: "Mon–Fri 8am – 6pm, Sat 8am – 12pm, closed Sundays",
    notes: "Independent, opened 2025, at Pomphlett by Laira Bridge. \"As a small team, we're unable to offer a 24-hour service at the moment\": between 6pm and 8am on weekdays, and from noon on Saturday through the weekend, emergencies go to MiNightVet Plymouth, Woodlands Veterinary Group, 12 Burnett Road, PL6 5BH, 01752 754900. Offers second-opinion consultations; whether non-clients are seen isn't stated. Mobile 07426 976239",
    verified: "2026-09-16",
  },
  {
    // PL9 7BN via postcodes.io, from the group's own branch page; OSM way
    // 884183026 puts it 75 m away.
    slug: "plymstock-vets",
    name: "Plymstock Veterinary Surgery",
    kind: "vet",
    vet: { emergency: true },
    lat: 50.36457, lon: -4.09812,
    address: "70 Pomphlett Road, Plymstock, Plymouth, PL9 7BN",
    phone: "01752 492293",
    email: "enquiries@plymouthvets.co.uk",
    url: "https://www.plymouthvets.co.uk/about-us/our-locations/plymstock",
    hours: "Mon–Fri 9am – 1pm and 2pm – 6pm, closed Saturdays and Sundays. Emergencies 01752 702646",
    notes: "Plymouth Vet Group's Plymstock branch, the same group as Rosehill. All four of its centres close at 6pm on weekdays and for most of the weekend and bank holidays, when you're given the number for the group's own hospital, Plymouth Veterinary Hospital, 26 William Prance Road, Derriford, PL6 5WR, staffed overnight. Whether non-clients are seen isn't stated",
    verified: "2026-09-16",
  },
  {
    // PL9 9BU via postcodes.io, from the practice's own contact page. OSM way
    // 1016553837 is 140 m away and labelled "Plymstock Veterinary Centre",
    // which is a different practice: the postcode is the safer position. The
    // nearest vet of any kind to Warren Point, at 5.9 km — there is none in
    // Wembury, Yealmpton or Newton Ferrers.
    slug: "elm-vets-plymstock",
    name: "Elm Vets Plymstock",
    kind: "vet",
    vet: { emergency: true },
    lat: 50.36008, lon: -4.08866,
    address: "2 Horncross Road, Plymstock, Plymouth, PL9 9BU",
    phone: "01752 481599",
    email: "plymstock@elmvetgroup.co.uk",
    url: "https://www.elmvetsplymouth.co.uk/contact-us",
    hours: "Mon–Fri 9am – 1pm and 2pm – 6pm, closed for lunch, closed Saturdays and Sundays. Emergencies 01752 567567",
    notes: "In Elburton despite the name, and the nearest practice to the Wembury end of the day. Appointment only, and the practice says so plainly: \"if you turn up without having pre-arranged an appointment, there will be no vets available to see you\" — so ring first. Out of hours the number given is the group's own Milehouse surgery, 28 Outland Road, PL2 3DF; which site actually sees the animal isn't stated. Whether non-clients are seen isn't stated",
    verified: "2026-09-16",
  },  // Sections 37 and 38.
  {
    // OSM way 180219366 "South Moor Vets", addr:postcode PL21 0TP, matching
    // the practice's own page. The nearest vet to the Erme and to Bigbury.
    slug: "south-moor-vets-modbury",
    name: "South Moor Vets, Modbury",
    kind: "vet",
    vet: { emergency: true },
    lat: 50.34999, lon: -3.89307,
    address: "New Mills, Modbury, Devon, PL21 0TP",
    phone: "01548 830210",
    url: "https://southmoorvets.co.uk/contact/modbury/",
    hours: "Mon–Fri 9am – 6pm. Closed Saturdays and Sundays; the group's other three branches open 9am – 1pm on Saturdays",
    notes: "Independent four-branch practice, at Modbury since the 1950s and on the New Mills estate since 2005; also the base for South Moor Equine. \"For out-of-hours emergencies, your pet will be cared for by our own team at one of our other branches\" — Kingsbridge, Ivybridge or Dartington, so ring first and be told where to drive. Free parking outside. Whether non-clients are seen isn't stated",
    verified: "2026-09-16",
  },
  {
    // OSM node 2011565581 "South Moor Vets" on Derby Road; the practice's own
    // TQ7 1JL puts it 136 m away through postcodes.io, so the node is the
    // better position.
    slug: "south-moor-vets-kingsbridge",
    name: "South Moor Vets, Kingsbridge",
    kind: "vet",
    vet: { emergency: true },
    lat: 50.28198, lon: -3.77214,
    address: "Derby Road, Kingsbridge, Devon, TQ7 1JL",
    phone: "01548 852766",
    url: "https://southmoorvets.co.uk/contact/kingsbridge/",
    hours: "Mon–Fri 9am – 6pm, Sat 9am – 1pm, closed Sundays",
    notes: "The same independent group as Modbury, purpose-built on Derby Road since 1990 and mainly a small animal clinic. Out of hours \"you'll be directed to our on-call team — the same reassuring faces you see during the day, not a stranger at an unfamiliar clinic\", so the number to ring is the branch's own. Free car park in front, about 15 spaces, covered waiting area. Short walk from the bus station through the memorial park. Whether non-clients are seen isn't stated",
    verified: "2026-09-16",
  },
  {
    // TQ7 4BL via postcodes.io, from the practice's own contact page; the
    // surgery is at Stumpy Post Cross on the A381, about 3 km north of
    // Kingsbridge, and is not in OpenStreetMap.
    slug: "selworthy-vets",
    name: "Selworthy Vets",
    kind: "vet",
    vet: { emergency: true },
    lat: 50.31051, lon: -3.77334,
    address: "Stumpy Post Surgery, Kingsbridge, Devon, TQ7 4BL",
    phone: "01548 853322",
    email: "reception@selworthyvets.co.uk",
    url: "https://www.selworthyvets.co.uk/contact",
    hours: "Mon–Thu 8.30am – 6.15pm, Fri 8.30am – 6pm, Sat 8.30am – 1pm, closed Sundays. Emergencies on the same number, any hour",
    notes: "Independent, family-run mixed practice — small animal, farm and equine — at Stumpy Post Cross on the Totnes road. \"24hr Emergency Care Available\" from its own vets and nurses rather than a referred-out service, with registered nurses on site through the night for inpatients: \"if you have an emergency please call us directly on 01548 853322 as emails and social media are not monitored outside normal hours\". Whether non-clients are seen isn't stated",
    verified: "2026-09-16",
  },
  // Sections 39 and 40.
  // Sections 39 and 40. There is no minor injury unit in Dartmouth at all: the
  // Dartmouth Health and Wellbeing Centre on Wessex Way, opened 2023, says so
  // itself and sends people to Totnes, 19 km away. Kingsbridge's South Hams
  // unit is already recorded.
  {
    // Centre of OSM way 146179853 "Totnes Community Hospital", addr:postcode
    // TQ9 5GH, matching the trust's own page; postcodes.io puts the postcode
    // 15 m away.
    slug: "totnes-miu",
    name: "Totnes Community Hospital minor injuries unit",
    kind: "hospital",
    // `walk_in` is only read for type "minor" in section.njk, so it is left off
    // here; the appointment-first rule is in `hours` and `notes` instead.
    hospital: { type: "utc" },
    lat: 50.43274, lon: -3.68414,
    address: "Totnes Community Hospital, Coronation Road, Totnes, TQ9 5GH",
    phone: "01803 862622",
    url: "https://www.torbayandsouthdevon.nhs.uk/services/urgent-and-emergency-care/minor-injuries-units/",
    hours: "8am – 5pm, 7 days a week, closed Christmas Day and Boxing Day. X-ray Mon 9am – 5pm and Tue–Wed 9am – 1pm only, not on bank holidays",
    notes: "Minor injuries unit, not an A&E. Appointment-priority: ring 01803 862622 and choose option 1 for a same-day appointment. Walk-ins are taken but come second, and if the unit is full you may be redirected or called back for a later time, so ring first. The nearest unit to Dartmouth, which has none of its own — the Dartmouth Health and Wellbeing Centre, Wessex Way, TQ6 0JL, 01803 832845, is GPs, nurses and therapies, 8am – 4.30pm, and sends injuries here. Kingsbridge's South Hams unit is nearer to Torcross and takes walk-ins without an appointment",
    verified: "2026-09-16",
  },
  {
    // Centre of OSM way 386272887 "Torbay Hospital", amenity=hospital,
    // emergency=yes, addr:postcode TQ2 7AA, matching the trust's own page.
    slug: "torbay-hospital",
    name: "Torbay Hospital",
    kind: "hospital",
    hospital: { type: "ae" },
    lat: 50.48215, lon: -3.55514,
    address: "Torbay Hospital, Lowes Bridge, Torquay, TQ2 7AA",
    phone: "01803 654003",
    url: "https://www.torbayandsouthdevon.nhs.uk/services/urgent-and-emergency-care/emergency-department/",
    hours: "24 hours, every day",
    notes: "The nearest full emergency department to the South Hams coast east of the Erme, and the one to head for from Torcross, Dartmouth or Brixham: Derriford, in Plymouth, is further from all three. Brixham has a community hospital of its own, on Greenswood Road, TQ5 9HW, 01803 881399, two minutes out of the Town Square on the 18 — but it is a 20-bed ward and outpatient clinics, with no minor injuries unit and no urgent care, and the town's GP practice says plainly that it cannot deal with minor injuries either and sends people to Totnes, Newton Abbot or here. The number is the department's own; the switchboard is 01803 614567 or 0300 456 8000. Waiting times for it and for the Newton Abbot and Totnes units are published on the trust's site before you set off",
    verified: "2026-09-16",
  },
  {
    // TQ6 9QH via postcodes.io, from the structured address on the practice's
    // own CVS page: The Old Mews, Roseville Street. Not in OpenStreetMap. The
    // nearest vet to Dartmouth and to the whole of section 40.
    slug: "dart-vale-dartmouth",
    name: "Dart Vale Veterinary Centre, Dartmouth",
    kind: "vet",
    vet: { emergency: true },
    lat: 50.35174, lon: -3.58197,
    address: "The Old Mews, Roseville Street, Dartmouth, TQ6 9QH",
    phone: "01803 832422",
    url: "https://www.cvsvets.com/south-west/dart-vale-veterinary-centre-dartmouth",
    hours: "Tuesdays and Thursdays 9am – 5.30pm only. Nothing on any other day",
    notes: "A small-animal branch surgery in Dartmouth since the early 1950s, now part of CVS — and open two days a week, which is the thing to know before walking a hurt dog up into the town. Every other day, and every night, weekend and bank holiday, it is Dart Vale Veterinary Hospital, Station Road, Totnes, TQ9 5JR, 01803 866073, which is staffed around the clock by its own emergency team: ring for free advice first and they arrange a consultation. Twenty minutes up the A381 from Dartmouth. Whether non-clients are seen isn't stated. Opening hours from the structured data on the practice's own page; the page itself prints none",
    verified: "2026-09-16",
  },
  // Optional. It won't make the nearest three on either section — 12.2 km from
  // the section 40 route against Dart Vale Dartmouth's 0.4 and South Moor
  // Kingsbridge's 8.6 — but it is where a Dartmouth emergency actually goes,
  // and section 41 will be nearer to it.
  {
    // TQ9 5JR via postcodes.io, from the group's own page.
    slug: "dart-vale-totnes",
    name: "Dart Vale Veterinary Hospital, Totnes",
    kind: "vet",
    vet: { emergency: true },
    lat: 50.43379, lon: -3.68777,
    address: "Station Road, Totnes, TQ9 5JR",
    phone: "01803 866073",
    url: "https://www.cvsvets.com/south-west/dart-vale-veterinary-hospital-totnes",
    hours: "Open 24 hours every day for emergencies, with its own overnight team. Routine hours not given on the page",
    notes: "A CVS 24/7 veterinary hospital, and where the Dartmouth branch sends everything outside its two days a week. Its own vets and nurses trained in critical care, on site through the night, weekends and bank holidays; free telephone advice first, then an emergency consultation if the animal needs to be seen. Referral surgery, internal medicine and ophthalmology as well. Whether non-clients are seen isn't stated",
    verified: "2026-09-16",
  },
  // Section 41.
  {
    // TQ5 9PW via postcodes.io, from the structured address on the practice's
    // own CVS page: 13/15 Penn Meadow. OSM has an unnamed amenity=veterinary
    // node 2712528497 60 m away, which is almost certainly it.
    slug: "dart-vale-brixham",
    name: "Dart Vale Veterinary Centre, Brixham",
    kind: "vet",
    vet: { emergency: true },
    lat: 50.38837, lon: -3.51243,
    address: "13/15 Penn Meadow, Brixham, TQ5 9PW",
    phone: "01803 854051",
    url: "https://www.cvsvets.com/south-west/dart-vale-veterinary-centre-brixham",
    hours: "Mon–Fri 8.30am – 6pm. Nothing listed for Saturday or Sunday",
    notes: "The nearest vet to the Brixham end of the day, in Penn Meadow behind the harbour, and the same CVS group as the Dartmouth branch at the other end of the section. Disabled access and parking on site. \"When our practice is closed during nights, weekends and bank holidays, we provide 24/7 care at Dart Vale Veterinary Hospital, Totnes\" — Station Road, TQ9 5JR, 01803 866073, staffed overnight by its own emergency team, with free telephone advice first. Whether non-clients are seen isn't stated. The hours are the structured data on the practice's own page; a directory adds a Saturday morning surgery that the page itself does not",
    verified: "2026-09-16",
  },
  {
    // OSM node 3374879584 "Silverton" (amenity=veterinary); the practice's own
    // TQ5 0DY puts it 90 m away through postcodes.io, so the node is the better
    // position. In Higher Brixham, on the Summercourt Way estate.
    slug: "silverton-vets-brixham",
    name: "Silverton Veterinary Centre, Brixham",
    kind: "vet",
    vet: { emergency: true },
    lat: 50.38551, lon: -3.53007,
    address: "8 Summercourt Way, Brixham, TQ5 0DY",
    phone: "01803 853060",
    email: "reception@silvertonvets.co.uk",
    url: "https://www.cvsvets.com/south-west/silverton-veterinary-centre-brixham",
    hours: "Mon–Thu 9am – 6pm, Fri 9am – 1pm. Closed Saturdays and Sundays",
    notes: "A small animal practice in Higher Brixham since 1985, now part of CVS, with disabled access and parking. It shuts at one o'clock on a Friday and does not open again until Monday, which is worth knowing before walking a hurt dog up the hill. Out of hours the practice sends you to MiNightVet South Devon, 7pm to 8am every night and all weekend; directories put that service at Station Road, Totnes, TQ9 5JR on 01803 866073 — the same address and number as Dart Vale's 24-hour hospital — but the practice's own page prints neither, so ring the surgery number and be told where to drive. Whether non-clients are seen isn't stated",
    verified: "2026-09-16",
  },
  // Sections 42 and 43.
  {
    // Centre of OSM way 170313253 "Newton Abbot Community Hospital",
    // amenity=hospital, addr:postcode TQ12 2TS, which matches the trust's own
    // page for the hospital. The trust's minor-injuries page gives the UTC's
    // address as TQ12 2SL, 280 m south-east — the West Golds Road entrance.
    slug: "newton-abbot-utc",
    name: "Newton Abbot Community Hospital urgent treatment centre",
    kind: "hospital",
    hospital: { type: "utc" },
    lat: 50.53922, lon: -3.61238,
    address: "Newton Abbot Community Hospital, West Golds Road, Jetty Marsh, Newton Abbot, TQ12 2TS",
    phone: "01626 324631",
    url: "https://www.torbayandsouthdevon.nhs.uk/services/urgent-and-emergency-care/minor-injuries-units/",
    hours: "8am – 8pm, 7 days a week including bank holidays. X-ray 9am – 5pm, 7 days a week including bank holidays, closed Christmas Day",
    notes: "Urgent treatment centre, not an A&E, and the nearest one to the whole of this coast: right for a sprain, a gash or a suspected break, twelve hours a day, with an X-ray department that keeps the same hours — which Totnes's does not. Ring 01626 324631 for a same-day appointment; walk-ins are taken but are asked to ring first unless it is an emergency. Free 20-minute bays and a pay-and-display car park. It matters because the two hospitals actually on the path cannot help: Teignmouth Community Hospital, Mill Lane, TQ14 9BQ, 01626 772161, is outpatient clinics and day surgery, Mon–Fri 8.30am – 5pm, with no injury unit at all; and Dawlish Community Hospital, Barton Terrace, EX7 9DH, 01626 868500, has a minor injuries unit that the trust says is \"currently closed due to staff shortage\" and has been shut repeatedly, so do not walk up the hill to it. Hospital switchboard 01626 324500. Waiting times for here, Totnes and Torbay's emergency department are published on the trust's site before you set off",
    verified: "2026-09-16",
  },
  {
    // Centre of OSM way 206900884 "Royal Devon & Exeter Hospital (Wonford)",
    // amenity=hospital, emergency=yes, addr:postcode EX2 5DW.
    //
    // NOTE FOR THE PARENT: recorded for the Starcross end. Torbay Hospital is
    // 17.9 km from Starcross and this is 11.1 km, so from the ferry pier this
    // is the nearer A&E, and it is nearer still to everything east of the Exe.
    // On section 43 it lands fourth by the nearest-end rule, behind Torbay,
    // Newton Abbot and Totnes, so it may not show; it will earn its place on
    // sections 44 onwards.
    slug: "royal-devon-exeter",
    name: "Royal Devon and Exeter Hospital (Wonford)",
    kind: "hospital",
    hospital: { type: "ae" },
    lat: 50.71691, lon: -3.50628,
    address: "Barrack Road, Exeter, EX2 5DW",
    phone: "01392 411611",
    url: "https://www.royaldevon.nhs.uk/services/emergency-department-ed-or-ae/",
    hours: "24 hours, every day",
    notes: "The nearest full emergency department to the Exe: eleven kilometres from Starcross against Torbay's eighteen, and a designated trauma unit seeing about 90,000 people a year. The department is being rebuilt, and its entrance has moved off the main hospital site to Church Hill — follow the signs rather than the satnav. The number is the hospital switchboard. From Babbacombe, Torbay Hospital is much nearer",
    verified: "2026-09-16",
  },
  {
    // 96 Warbro Road, TQ1 3RE via postcodes.io, from the practice's own page.
    // Not in OpenStreetMap. A kilometre from the babbacombe endpoint and 700 m
    // from the section 42 route — the nearest vet to the end of one section
    // and the start of the next.
    slug: "bay-vet-torquay",
    name: "Bay Vet Group, Torquay (Babbacombe)",
    kind: "vet",
    vet: { emergency: true },
    lat: 50.47543, lon: -3.51901,
    address: "96 Warbro Road, Babbacombe, Torquay, TQ1 3RE",
    phone: "01803 314940",
    url: "https://www.bayvetgroup.co.uk/vets-in-torquay/",
    hours: "Mon–Fri 9am – 6pm. Closed Saturdays and Sundays",
    notes: "The nearest vet to Babbacombe, in Warbro Road behind the Downs, and the group's main Torquay premises: free on-road parking, air-conditioned waiting room. Weekdays only — the group's Saturday morning surgery is at Dawlish and its Saturday daytime one at Paignton, and there is nothing at all on a Sunday. Out of hours is MiNightVet at Dart Vale Vets, Station Road, Totnes, TQ9 5JR, 7pm to 8am every night, and EVES at Exeter from 4pm on Saturday through Sunday daytime; either way ring 01626 247999, which redirects. The animal has to be taken to whichever clinic is on: they do not come out. The out-of-hours consultation alone was £185.20 before 10pm and £246.00 after, payable at the time, on top of treatment — and the group says the emergency service is for registered clients. Dentistry is done at Paignton, Newton Abbot or Dawlish, not here. The branch page prints the group's central number, 01803 247999; the practice's own listed line is 01803 314940",
    verified: "2026-09-16",
  },
  {
    // 148 Teignmouth Road, TQ1 4RY via postcodes.io, from the practice's own
    // site. Not in OpenStreetMap. A kilometre from the babbacombe endpoint,
    // on the road section 43 starts up.
    slug: "quarry-house-vets-torquay",
    name: "Quarry House Vets, Torquay",
    kind: "vet",
    vet: { emergency: true },
    lat: 50.48218, lon: -3.53529,
    address: "148 Teignmouth Road, Torquay, TQ1 4RY",
    phone: "01803 324341",
    url: "https://quarryhousevets.co.uk/emergency-service/",
    hours: "Mon–Fri 9am – 5pm, Wednesdays to 7pm, Sat 9am – 12 noon. Closed Sundays",
    notes: "An independent practice on the Teignmouth road out of St Marychurch, and the one of the two Torquay vets that opens on a Saturday morning. Separate waiting areas for dogs, cats and rabbits. Every emergency is seen at this clinic in practice hours. Outside them, 07967 103178 redirects to the duty vet; weekends and bank holidays until 7pm are shared with Greenbay Vets, 34 Walnut Road, Torquay, TQ2 6HS, and 7pm to 8am is MiNightVet South Devon at Dart Vale Vets, Station Road, Totnes, TQ9 5JR. Unregistered animals get free telephone advice on whether the animal needs to be seen, and treatment is paid for at the consultation — which is a plainer answer than most practices give a walker with a hurt dog. Branches at Teignmouth (St James Vets, 19a Fore Street, TQ14 8DY, 01626 773898, Monday and Wednesday mornings only) and Newton Abbot (Albany Vets, 01626 368000)",
    verified: "2026-09-16",
  },
  {
    // Maudlin Drive, TQ14 8RU via postcodes.io, from the practice's own page.
    // Not in OpenStreetMap. 1.1 km from the section 43 route.
    //
    // NOTE FOR THE PARENT: it will not make section 43's nearest three — 8.5 km
    // from the nearer end of the day against the Torquay pair's one — but it
    // is the only full-week vet between Torquay and Dawlish, which is the
    // thing to know in the middle of the day's walk.
    slug: "bay-vet-teignmouth",
    name: "Bay Vet Group, Teignmouth",
    kind: "vet",
    vet: { emergency: true },
    lat: 50.55879, lon: -3.49825,
    address: "Maudlin Drive, off New Road, Teignmouth, TQ14 8RU",
    phone: "01626 778882",
    url: "https://www.bayvetgroup.co.uk/vets-in-teignmouth/",
    hours: "Mon–Fri 9am – 6pm. Closed Saturdays and Sundays",
    notes: "Above the town off New Road, on the hill the path climbs out of Teignmouth towards Holcombe. On-site parking, step-free access, fifteen-minute consultations, digital X-ray and ultrasound, and home visits. Weekdays only; the same out-of-hours arrangement as the rest of the group — MiNightVet at Totnes overnight, EVES at Exeter from 4pm Saturday through Sunday, 01626 247999 for both, registered clients, and the animal goes to them. The other vet in Teignmouth is St James Vets, 19a Fore Street, TQ14 8DY, 01626 773898, which is Quarry House's branch and opens on Monday and Wednesday mornings only — but it is 400 m from the sea front against this one's kilometre and a bit",
    verified: "2026-09-16",
  },
  {
    // Hospital Hill, EX7 9NS via postcodes.io, from the group's own site. Not
    // in OpenStreetMap. 550 m from the section 43 route at Dawlish and 5.4 km
    // from the starcross endpoint — the nearest vet to the end of the day.
    slug: "bay-vet-dawlish",
    name: "Bay Vet Group, Dawlish",
    kind: "vet",
    vet: { emergency: true },
    lat: 50.58187, lon: -3.47278,
    address: "Hospital Hill, Dawlish, EX7 9NS",
    phone: "01626 862020",
    url: "https://www.bayvetgroup.co.uk/",
    hours: "Mon–Fri 9am – 6pm, Sat 9am – 12 noon. Closed Sundays",
    notes: "The group's main surgery, up Hospital Hill behind the town, and the nearest vet to the Starcross end of the day — five kilometres back down the coast road, with the 2 passing the bottom of the hill every half hour. One of only two branches in the group that open on a Saturday, and the only one anywhere near this end of the path. Sundays nothing: MiNightVet at Dart Vale Vets, Station Road, Totnes, TQ9 5JR overnight, and EVES at Exeter St David's from 4pm Saturday through Sunday daytime, both on 01626 247999, registered clients, animal taken to them, consultation £185.20 before 10pm and £246.00 after on top of treatment. From Starcross the Exeter service is much the nearer of the two",
    verified: "2026-09-16",
  },];
