// Hospitals and vets.
//
// Unlike everything else these are matched by "the nearest few, however far" —
// there is always a nearest A&E and you always want to know which it is, even
// when it's an hour away. They get pins, but never widen the map: the nearest
// A&E to this stretch is in Taunton, and fitting it in would zoom the route
// out to nothing.
//
//   hospital.type   "ae"  a full 24/7 emergency department
//                   "utc" urgent treatment centre — the old minor injuries
//                         unit, right for a sprain or a gash, not for a
//                         serious injury
//                   "minor" a GP practice's minor injuries service — nurse-led,
//                         weekdays, ring first. Worth knowing on the doorstep,
//                         but not somewhere you can simply turn up
//   vet.emergency   true | false | null — whether they cover out of hours
export default [
  {
    slug: "minehead-utc",
    name: "Minehead Community Hospital",
    kind: "hospital",
    hospital: { type: "utc" },
    lat: 51.20011, lon: -3.46191,
    address: "Luttrell Way, Minehead, TA24 6DF",
    phone: "01643 701701",
    hours: "8am – 9pm daily, last patient 8.30pm",
    notes: "Urgent treatment centre, not an A&E — right for sprains and cuts. NHS 111 first if you're unsure it's the right place",
    verified: null,
  },
  {
    slug: "musgrove-park",
    name: "Musgrove Park Hospital",
    kind: "hospital",
    hospital: { type: "ae" },
    lat: 51.01157, lon: -3.12170,
    address: "Parkfield Drive, Taunton, TA1 5DA",
    phone: "01823 333444",
    hours: "24 hours, every day",
    notes: "Nearest full A&E to the Somerset end of the path",
    verified: null,
  },
  {
    slug: "north-devon-district",
    name: "North Devon District Hospital",
    kind: "hospital",
    hospital: { type: "ae" },
    lat: 51.09217, lon: -4.05046,
    address: "Raleigh Park, Barnstaple, EX31 4JB",
    phone: "01271 322577",
    hours: "24 hours, every day",
    notes: "Nearest full A&E once you're into Devon; also a designated trauma unit",
    verified: "2026-09-13",
  },
  {
    slug: "white-lodge-minehead",
    name: "White Lodge Veterinary Centre",
    kind: "vet",
    vet: { emergency: true },
    lat: 51.20092, lon: -3.46509,
    address: "Stephenson Road, Alcombe, Minehead",
    phone: "01643 703649",
    url: "https://www.whitelodgevetclinic.co.uk/",
    hours: "Emergencies 24 hours on the same number",
    notes: "8am–7pm handled by the Minehead or Williton practice; 7pm–8am by Somerset Veterinary Emergency Clinic at Bridgwater. Registered clients first — others seen at their discretion, possibly for a higher fee",
    verified: "2026-09-13",
  },
  {
    slug: "charter-barnstaple",
    name: "Charter Veterinary Hospital (CVS Vets 24/7)",
    kind: "vet",
    vet: { emergency: true },
    lat: 51.06500, lon: -4.09262,
    address: "Charter Court, Roundswell, Barnstaple, EX31 3FG",
    phone: "01271 371115",
    url: "https://www.cvsvets.com/south-west/charter-veterinary-hospital",
    hours: "Emergencies 24 hours, every day",
    notes: "Formerly MiNightVet, whose site now redirects to CVS; other practices still send out-of-hours cases to \"MiNightVet Barnstaple\" at this address. Out-of-hours cover for the Ilfracombe practice too",
    verified: "2026-09-13",
  },
  {
    slug: "lyn-health-lynton",
    name: "Lyn Health minor injury service",
    kind: "hospital",
    hospital: { type: "minor" },
    lat: 51.22921, lon: -3.83722,
    address: "Burvill Street, Lynton, EX35 6HA",
    phone: "01598 753226",
    hours: "Mon–Fri, appointments 9am – 5pm. Not at weekends",
    notes: "Nurse-led, at the GP surgery: wounds, burns, bites and stings, sprains, minor head injuries. No walk-ins; ring first or use NHS 111",
    verified: "2026-09-13",
  },
  {
    slug: "combe-coastal-ilfracombe",
    name: "Combe Coastal Practice minor injuries",
    kind: "hospital",
    hospital: { type: "minor" },
    lat: 51.20374, lon: -4.12687,
    address: "Ilfracombe Medical Centre, St Brannocks Road, Ilfracombe, EX34 8EG",
    phone: "01271 863119",
    hours: "Mon–Fri only. 8am – 6.30pm on the practice's site, 8.30am – 6pm in Royal Devon's 2024 notice",
    notes: "Ilfracombe's minor injuries service while the Tyrrell Hospital unit is closed, which Royal Devon calls temporary. Ring first; the duty clinician calls back with a same-day slot. Whether visitors are seen isn't stated",
    verified: "2026-09-13",
  },
  {
    slug: "charter-mullacott",
    name: "Charter Veterinary Centre – Mullacott",
    kind: "vet",
    vet: { emergency: false },
    lat: 51.17762, lon: -4.14603,
    address: "Bickenbridge Farm, Mullacott, Ilfracombe, EX34 8NZ",
    phone: "01271 866770",
    url: "https://www.cvsvets.com/south-west/charter-veterinary-centre-mullacott",
    notes: "Small animals, CVS group. Nights, weekends and bank holidays go to Charter Veterinary Hospital, Barnstaple. Street address from OSM, not the CVS page",
    verified: "2026-09-13",
  },
  {
    slug: "argyll-braunton",
    name: "Argyll Veterinary Centre – Braunton",
    kind: "vet",
    vet: { emergency: false },
    // EX33 2JL via postcodes.io; OSM has no node for it.
    lat: 51.10695, lon: -4.16053,
    address: "28 Exeter Road, Braunton, EX33 2JL",
    phone: "01271 812405",
    url: "https://www.cvsvets.com/south-west/argyll-veterinary-centre-braunton",
    hours: "Mon–Fri 8.30am – 7pm, Sat 9am – 12.30pm",
    notes: "Small animals, CVS group. Nights, weekends and bank holidays go to Charter Veterinary Hospital, Barnstaple. Position is the postcode's, not the building's. Argyll's Ilfracombe branch, still on OSM, closed in 2021",
    verified: "2026-09-13",
  },
  {
    // Centre of OSM way 180169336.
    slug: "torrington-health-centre",
    name: "Torrington Health Centre minor injuries",
    kind: "hospital",
    hospital: { type: "minor" },
    lat: 50.95207, lon: -4.14004,
    address: "New Road, Torrington, EX38 8EL",
    phone: "01805 622247",
    url: "https://torringtonhc.nhs.uk/services/medical-services-and-clinics",
    hours: "Weekdays 8.30am – 6pm, closed 12.15 – 1.15pm. Not at weekends",
    notes: "A GP practice's minor injuries service. Nearest to Instow while Bideford Community Hospital's unit is temporarily closed. Whether visitors are seen, and whether to ring first, isn't stated. Castle Gardens Surgery, 50 m away (01805 623222), runs one too, a sit-down-and-wait service; the two cover each other's lunch hour",
    verified: "2026-09-13",
  },
  {
    slug: "vets4pets-barnstaple",
    name: "Vets4Pets Barnstaple",
    kind: "vet",
    vet: { emergency: false },
    // EX31 2AU via postcodes.io, the station's postcode; OSM has no node.
    lat: 51.07472, lon: -4.06215,
    address: "Inside Pets at Home, Barnstaple Retail Park, Station Road, Barnstaple, EX31 2AU",
    phone: "01271 335520",
    url: "https://www.vets4pets.com/practices/vets4pets-barnstaple/",
    hours: "Mon–Fri 9am – 7pm, Sat 9am – 6pm, closed Sundays",
    notes: "By Barnstaple station, near the path. Out of hours goes to Charter Veterinary Hospital. Position is the postcode's, not the building's",
    verified: "2026-09-13",
  },
  {
    slug: "tarka-vets-barnstaple",
    name: "Tarka Vets",
    kind: "vet",
    vet: { emergency: true },
    // EX32 7AS via postcodes.io; OSM has no node.
    lat: 51.08548, lon: -4.05856,
    address: "St George's House, St George's Road, Barnstaple, EX32 7AS",
    phone: "01271 452660",
    url: "https://www.tarkavets.org/",
    hours: "Mon–Fri 8am – 6pm, Sat 8.30am – 12.30pm. Emergencies 24 hours on the same number",
    notes: "Independent; covers its own emergencies rather than sending them to Charter. Text or WhatsApp 07476 947981. Whether it sees non-clients out of hours isn't stated. Position is the postcode's",
    verified: "2026-09-13",
  },
  {
    slug: "medivet-northam",
    name: "Medivet Northam (Witten Park Vets)",
    kind: "vet",
    vet: { emergency: false },
    // EX39 3QA via postcodes.io; OSM has no node.
    lat: 51.03150, lon: -4.21716,
    address: "Heywood Road, Northam, EX39 3QA",
    phone: "01237 473278",
    url: "https://www.medivetgroup.com/vet-practices/northam/",
    hours: "Mon–Fri 8.30am – 6pm, Sat 9am – 12pm",
    notes: "Emergencies seen here until 7pm every day, then at Charter Veterinary Hospital, Barnstaple; ring this number for a call-back either way. Medivet East-the-Water, Bideford (01237 422657), is weekdays only. Position is the postcode's",
    verified: "2026-09-13",
  },
  {
    slug: "torbridge-bideford",
    name: "Torbridge Veterinary Centre – Bideford",
    kind: "vet",
    vet: { emergency: false },
    // EX39 3DX via postcodes.io; OSM has no node.
    lat: 51.00719, lon: -4.23368,
    address: "7 Caddsdown Industrial Park, Clovelly Road, Bideford, EX39 3DX",
    phone: "01237 472075",
    url: "https://www.cvsvets.com/south-west/torbridge-veterinary-centre-bideford",
    hours: "Mon–Fri 8am – 7pm, Sat 8.30am – 5pm",
    notes: "Small animals, CVS group. Open Saturday afternoons, when Medivet Northam isn't. When closed, Charter Veterinary Hospital, Barnstaple (01271 371115). Position is the postcode's",
    verified: "2026-09-13",
  },
  {
    // Centre of OSM way 175283262.
    slug: "hartland-surgery",
    name: "Hartland Surgery minor injuries",
    kind: "hospital",
    hospital: { type: "minor" },
    lat: 50.99236, lon: -4.48230,
    address: "66 The Square, Hartland, EX39 6BL",
    phone: "01237 441200",
    url: "https://hartlandsurgery.co.uk/about/",
    hours: "Mon–Fri 8am – 6.30pm, Thu until 8pm; reception shut 1–2pm but phones answered. Phones 8.30am – 6pm. Not at weekends",
    notes: "A GP practice's minor injury service: doctors and a nurse see injuries from the last 48 hours — cuts, sprains, bites, minor burns, eye injuries. Ring or call in, for anyone in the Hartland area; seen as soon as possible",
    verified: "2026-09-13",
  },
  {
    // OSM node 984261739.
    slug: "stratton-miu",
    name: "Stratton Community Hospital minor injury unit",
    kind: "hospital",
    hospital: { type: "utc" },
    lat: 50.83055, lon: -4.51761,
    address: "Hospital Road, Stratton, Bude, EX23 9BR",
    phone: "01288 287700",
    // The trust's page also gives 01288 287722.
    url: "https://www.cornwallft.nhs.uk/stratton-community/",
    hours: "24 hours every day on Cornwall's live status page, which also posts closures. 8pm – 8am by calling 111 first",
    notes: "Minor injury unit, not an A&E. Walk in by day; from 8pm to 8am a community treatment centre on the site takes patients through NHS 111. Holsworthy's GP practice calls the unit 111-only, so ring 111 first if in doubt. X-ray Mon, Tue, Wed and Fri 9am – 5pm. Live status: cornwallft.nhs.uk/miu-waiting-times",
    verified: "2026-09-13",
  },
  {
    slug: "tamar-vets-hartland",
    name: "Tamar Vets – Hartland",
    kind: "vet",
    vet: { emergency: true },
    // EX39 6AG via postcodes.io; OSM has no node.
    lat: 50.99009, lon: -4.46936,
    address: "Unit 7, Hartland Industrial Estate, Hartland, EX39 6AG",
    phone: "01288 354796",
    url: "https://www.tamarvets.co.uk/hartland-vets/",
    hours: "Mon, Wed and Fri 4pm – 6pm, by appointment. Emergencies 24 hours on 01288 354796",
    notes: "Branch of Tamar Vets, Bude, which takes the bookings: Mon–Fri 8.30am – 7pm, Sat 9am – 1pm. Branch line 01237 441741. Independent, with its own 24-hour emergency service and nurses on site round the clock; where night cases are seen, and whether non-clients are taken, isn't stated. Position is the postcode's",
    verified: "2026-09-13",
  },
  {
    slug: "tamar-vets-bude",
    name: "Tamar Vets – Bude",
    kind: "vet",
    vet: { emergency: true },
    // Centre of OSM way 722865229, which OSM addresses as Howards Way, EX23 8DY.
    lat: 50.82875, lon: -4.54385,
    address: "9 The Strand, Bude, EX23 8QU",
    phone: "01288 354796",
    url: "https://www.tamarvets.co.uk/contact/",
    hours: "Mon–Fri 8.30am – 7pm, Sat 9am – 1pm. Emergencies 24 hours on the same number",
    notes: "Independent, with branches in Holsworthy and Hartland. Its own vets cover emergencies, with nurses on site 24 hours. Whether non-clients are seen out of hours isn't stated. Second line 01288 355784",
    verified: "2026-09-13",
  },
  {
    slug: "penbode-stratton",
    name: "Penbode Vets – Stratton",
    kind: "vet",
    vet: { emergency: true },
    // OSM node 11009334145.
    lat: 50.82741, lon: -4.52112,
    address: "A39 Hillhead, Stratton, Bude, EX23 9AB",
    phone: "01288 359500",
    url: "https://www.penbodevets.co.uk/contact-us/stratton-branch",
    hours: "Mon–Fri 8am – 6pm, Sat 9am – 5pm. Emergencies 24 hours on the same number",
    notes: "VetPartners group. Its own 24-hour service: out-of-hours calls are passed to a vet, and pets from every Penbode branch are usually seen here, where staff are on site at all times. Whether non-clients are seen isn't stated",
    verified: "2026-09-13",
  },
  {
    slug: "penbode-bradworthy",
    name: "Penbode Vets – Bradworthy",
    kind: "vet",
    vet: { emergency: true },
    // EX22 7SZ via postcodes.io; OSM has no node.
    lat: 50.90123, lon: -4.38554,
    address: "Ashleigh House, Bradworthy, EX22 7SZ",
    phone: "01409 241241",
    url: "https://www.penbodevets.co.uk/contact-us/bradworthy-branch",
    hours: "Mon–Fri 8am – 5pm, alternate Saturdays 8.30am – 1pm. Emergencies 24 hours on the same number or 01288 359500",
    notes: "Small branch, pets and farm. Out of hours a Penbode vet answers, and pets are usually seen at Stratton, near Bude, not here. Position is the postcode's",
    verified: "2026-09-13",
  },
  {
    // Centre of OSM way 1336913592.
    slug: "launceston-miu",
    name: "Launceston Community Hospital minor injury unit",
    kind: "hospital",
    hospital: { type: "utc" },
    lat: 50.62792, lon: -4.35915,
    address: "Link Road, Launceston, PL15 9JD",
    phone: "01566 765600",
    url: "https://www.cornwallft.nhs.uk/launceston-hospital/",
    hours: "Usually 8am – 8pm every day, X-ray Sunday to Friday 9am – 5pm, on the trust's live status page",
    notes: "Minor injury unit, not an A&E: walk in, no appointment. Live waiting times and hours: cornwallft.nhs.uk/miu-waiting-times. Stratton, near Bude, is nearer and open 24 hours",
    verified: "2026-09-14",
  },
  {
    // Emergency department entrance, OSM node 8151096985.
    slug: "derriford",
    name: "University Hospitals Plymouth (Derriford)",
    kind: "hospital",
    hospital: { type: "ae" },
    lat: 50.41680, lon: -4.11320,
    address: "Derriford Road, Crownhill, Plymouth, PL6 8DH",
    phone: "01752 202082",
    url: "https://www.plymouthhospitals.nhs.uk/emergency-department",
    hours: "24 hours, every day",
    notes: "Major trauma centre for the South West peninsula: severe injuries, strokes, heart attacks, neurosurgery. Phone is the switchboard",
    verified: "2026-09-14",
  },
  {
    // Emergency entrance, OSM node 10016851800.
    slug: "royal-cornwall-hospital",
    name: "Royal Cornwall Hospital (Treliske)",
    kind: "hospital",
    hospital: { type: "ae" },
    lat: 50.26601, lon: -5.09201,
    address: "Treliske, Truro, TR1 3LJ",
    phone: "01872 250000",
    url: "https://royalcornwallhospitals.nhs.uk/services/emergency-department-ed/",
    hours: "24 hours, every day",
    notes: "Cornwall's emergency department. Walk-in patients use the Minors entrance: the department is on the right of the Trelawny Wing with its own entrance, signed in red. Phone is the switchboard; the department's lines, 01872 253111 and 253113, are for patients already there",
    verified: "2026-09-14",
  },
  {
    // Centre of OSM way 279708712.
    slug: "bodmin-miu",
    name: "Bodmin Community Hospital minor injury unit",
    kind: "hospital",
    hospital: { type: "utc" },
    lat: 50.46762, lon: -4.74216,
    address: "Boundary Road, Bodmin, PL31 2QT",
    phone: "01208 251300",
    url: "https://www.cornwallft.nhs.uk/bodmin-community",
    hours: "Usually 8am – 10pm every day, X-ray 8am – 8pm, on the trust's live status page, which also posts pauses in service",
    notes: "Minor injury unit, not an A&E: walk in, no appointment, injuries from the last 14 days. Live status: cornwallft.nhs.uk/miu-waiting-times",
    verified: "2026-09-14",
  },
  {
    slug: "penbode-camelford",
    name: "Penbode Vets – Camelford",
    kind: "vet",
    vet: { emergency: true },
    // Centre of OSM way 988762867.
    lat: 50.61533, lon: -4.68527,
    address: "Inns Park, Valley Truckle, Camelford, PL32 9RX",
    phone: "01840 213277",
    url: "https://www.penbodevets.co.uk/contact-us/camelford-branch",
    hours: "Mon–Fri 8am – 6pm. Emergencies 24 hours on the same number or 01288 359500",
    notes: "Pets and farm, VetPartners group. The branch page gives Saturday 8.30am – 1pm for the farm side only. Out of hours a Penbode vet answers, and pets are usually seen at Stratton, near Bude, not here. Whether non-clients are seen isn't stated",
    verified: "2026-09-14",
  },
  {
    slug: "nute-wadebridge",
    name: "Nute Veterinary Centre – Wadebridge",
    kind: "vet",
    vet: { emergency: false },
    // PL27 6HB via postcodes.io; OSM has no node.
    lat: 50.52011, lon: -4.82328,
    address: "Higher Trenant Road, Wadebridge, PL27 6HB",
    phone: "01208 813258",
    url: "https://www.cvsvets.com/south-west/nute-veterinary-centre-wadebridge",
    hours: "Mon–Fri 8am – 7pm, Sat 8am – 1pm",
    notes: "Small animals, CVS group. Nights, weekends and bank holidays go to Clifton Villa Veterinary Centre, 53 Henver Road, Newquay, TR7 3DQ (01637 520123), 25 km from Port Isaac; free phone advice first. Whether non-clients are seen isn't stated. Position is the postcode's",
    verified: "2026-09-14",
  },
  {
    slug: "wave-vets-wadebridge",
    name: "Wave Vets",
    kind: "vet",
    vet: { emergency: false },
    // PL27 7AW via postcodes.io; OSM has no node.
    lat: 50.51724, lon: -4.83796,
    address: "Unit 4, Trevanson Street, Wadebridge, PL27 7AW",
    phone: "01208 812099",
    url: "https://wavevets.co.uk/emergencies",
    hours: "Mon–Fri 8.30am – 6pm, Sat 8.30am – 12pm",
    notes: "Independent. Entrance on Goldsworthy Way, opposite the Saltbox and Lidl. Out of hours the answerphone sends you to Beacon VetCare, Chapel Parc, Chapel Town, Summercourt, TR8 5AH (01872 890100), 27 km from Port Isaac in a straight line; pets come back here next morning. Mobile 07500 794648. Whether non-clients are seen isn't stated. Position is the postcode's",
    verified: "2026-09-14",
  },
  {
    slug: "penmellyn-padstow",
    name: "Penmellyn Vets – Padstow & St Merryn",
    kind: "vet",
    vet: { emergency: true },
    // OSM node 11327765577.
    lat: 50.52309, lon: -4.99587,
    address: "Riviera, St Merryn, Padstow, PL28 8NR",
    phone: "01841 520647",
    url: "https://www.padstowvets.com/contact-us",
    hours: "Mon, Tue and Thu 8.30am – 2.30pm; closed Wed, Fri and weekends. Emergencies 24 hours on 01637 880307",
    notes: "In St Merryn, 4.7 km west of Padstow, not in the town. Penmellyn group, part of IVC. Its own vets cover out of hours at Penmellyn's hospital in St Columb Major, where a nurse is on site round the clock. Whether non-clients are seen isn't stated",
    verified: "2026-09-14",
  },
  {
    slug: "penmellyn-st-columb",
    name: "Penmellyn Vets – St Columb Hospital",
    kind: "vet",
    vet: { emergency: true },
    // OSM node 2430578077.
    lat: 50.42771, lon: -4.94038,
    address: "Station Road, St Columb Major, TR9 6BX",
    phone: "01637 880307",
    url: "https://www.penmellynvet.co.uk/emergencies",
    hours: "Mon–Fri 8am – 6.30pm, Sat 8.30am – 4.30pm. Emergencies 24 hours on the same number",
    notes: "Penmellyn's hospital, where its own vets see every branch's out-of-hours cases; a nurse is based there round the clock. 13 km south of Padstow. Whether non-clients are seen isn't stated",
    verified: "2026-09-14",
  },
  {
    // Centre of OSM way 118521679; TR7 1RQ via postcodes.io is 30 m away.
    slug: "newquay-miu",
    name: "Newquay Community Hospital minor injury unit",
    kind: "hospital",
    hospital: { type: "utc" },
    lat: 50.41093, lon: -5.07399,
    address: "St Thomas Road, Newquay, TR7 1RQ",
    phone: "01637 834800",
    url: "https://www.cornwallft.nhs.uk/newquay-community/",
    hours: "Closed until Monday 5 October 2026, then open on fewer days to begin with. The trust's live status page gives its usual hours as Thursday to Tuesday 8am – 6pm, closed Wednesdays; X-ray Mon, Tue, Thu and Fri 9am – 5pm",
    notes: "Minor injury unit, not an A&E: walk in, no appointment, injuries from the last 14 days. Temporarily closed because there aren't enough specialist staff. The trust plans to reopen it from 5 October at the busiest times, and will confirm. Meanwhile it points to Bodmin (8am – 10pm), Camborne Redruth or St Austell. Phone is the hospital's. Live status: cornwallft.nhs.uk/miu-waiting-times",
    verified: "2026-09-14",
  },
  {
    slug: "clifton-villa-newquay",
    name: "Clifton Villa Veterinary Centre (CVS Vets 24/7)",
    kind: "vet",
    vet: { emergency: true },
    // TR7 3DQ via postcodes.io; OSM has no node.
    lat: 50.41830, lon: -5.06253,
    address: "53 Henver Road, Newquay, TR7 3DQ",
    phone: "01637 851122",
    url: "https://www.cvsvets.com/south-west/clifton-villa-veterinary-centre-newquay",
    hours: "Emergencies 24 hours, every day, seen here. Routine hours not given on the page",
    notes: "CVS group, with its own vets and nurses on site through nights, weekends and bank holidays. Free phone advice on 01637 520123, and an emergency consultation arranged if needed. Out-of-hours centre for Nute Veterinary Centre, Wadebridge. Whether non-clients are seen isn't stated. Position is the postcode's",
    verified: "2026-09-14",
  },
  {
    slug: "newquayvet",
    name: "NewquayVet",
    kind: "vet",
    vet: { emergency: false },
    // TR7 2QL via postcodes.io; OSM has no node.
    lat: 50.40482, lon: -5.06216,
    address: "21 + 22 Treloggan Trade Park, Newquay, TR7 2QL",
    phone: "01637 871100",
    url: "https://newquayvet.uk/surgery-hours/",
    hours: "Mon–Fri 9am – 10.30am, 2pm – 3pm and 5pm – 6.30pm; Sat 9am – 12pm. Closed Sundays",
    notes: "Independent. Open surgeries rather than appointments: turn up in surgery hours and wait. Nights, weekends and bank holidays go to CVETS, Cornwall Veterinary Emergency Treatment Service, The Old Dairy, Penstraze, Truro, TR4 8PN (01872 560952), 16 km from Newquay. Whether non-clients are seen isn't stated. Position is the postcode's",
    verified: "2026-09-14",
  },
  {
    slug: "penmellyn-newquay",
    name: "Penmellyn Vets – Newquay",
    kind: "vet",
    vet: { emergency: true },
    // TR7 3EQ via postcodes.io; OSM has no node.
    lat: 50.41796, lon: -5.05458,
    address: "152 Henver Road, Newquay, TR7 3EQ",
    phone: "01637 871695",
    email: "newquayvets@penmellyn.co.uk",
    url: "https://www.newquayvets.com/contact-us",
    hours: "Mon–Fri 8.30am – 6pm, Sat 8.30am – 4.30pm, closed Sundays. Emergencies 24 hours on 01637 880307",
    notes: "Penmellyn group, part of IVC. Its own vets cover out of hours at Penmellyn's hospital in St Columb Major, 10 km inland, where a nurse is on site round the clock. Whether non-clients are seen isn't stated. Position is the postcode's",
    verified: "2026-09-14",
  },
  {
    slug: "beacon-vetcare-newquay",
    name: "Beacon VetCare – Newquay",
    kind: "vet",
    vet: { emergency: true },
    // Centre of OSM way 187795409.
    lat: 50.41734, lon: -5.04476,
    address: "Church Street, St Columb Minor, Newquay, TR7 3ET",
    phone: "01637 695100",
    email: "newquay@beaconvetcare.co.uk",
    url: "https://beaconvetcare.co.uk/newquay/",
    hours: "Mon–Fri 8.30am – 6.30pm, Sat 8.30am – 1.30pm, closed Sundays. Emergencies 24 hours on 01872 890100, press 1",
    notes: "Independent, four branches. Emergencies, overnight and advanced cases go to its referral centre at Chapel Parc, Chapel Town, Summercourt, TR8 5AH, 9 km from Newquay, open 24 hours with a vet and nurse on site. Out-of-hours centre for Wave Vets, Wadebridge. Whether non-clients are seen isn't stated",
    verified: "2026-09-14",
  },
  {
    // Centre of OSM way 545023986.
    slug: "camborne-redruth-miu",
    name: "Camborne Redruth Community Hospital minor injury unit",
    kind: "hospital",
    hospital: { type: "utc" },
    lat: 50.22918, lon: -5.24530,
    address: "Barncoose Terrace, Redruth, TR15 3ER",
    phone: "01209 318000",
    url: "https://www.cornwallft.nhs.uk/camborne-redruth-hospital/",
    hours: "Usually 8am – 10pm every day, doctor-led until 9pm, X-ray 8am – 8pm, on the trust's live status page, which also posts pauses in service",
    notes: "Minor injury unit, not an A&E: walk in, no appointment, injuries from the last 14 days. One of the units the trust points to while Newquay's is closed. Phone is the hospital's. Live status: cornwallft.nhs.uk/miu-waiting-times",
    verified: "2026-09-15",
  },
  {
    slug: "st-clement-perranporth",
    name: "St Clement Veterinary Clinic – Perranporth",
    kind: "vet",
    vet: { emergency: true },
    // OSM node 12461530029.
    lat: 50.34524, lon: -5.15279,
    address: "36a St Pirans Road, Perranporth, TR6 0BJ",
    phone: "01872 572572",
    email: "stclementrequests@gmail.com",
    url: "https://stclementvets.co.uk/facilities/perranporth/",
    hours: "Mon–Thu 8.30am – 5pm, Fri 8.30am – 2pm, by appointment; closed weekends. Emergencies on 01872 223400",
    notes: "Branch of St Clement Veterinary Clinic, St Clement Vean, Truro, TR1 1RN (Mon–Fri 8am – 7pm, Sat 8.30am – 3pm). Between Piran Surf and the Perranporth Inn. In opening hours an emergency is triaged by phone and seen at the Truro branch. On weeknights its own on-call vet answers 01872 223400, at an extra charge; at weekends MiNightVet in Falmouth takes the calls. Whether non-clients are seen isn't stated",
    verified: "2026-09-15",
  },
];
