// Things worth stopping for. Matched like everything else — by position, near
// the route — so a section picks up whatever it passes.
//
// `poi.type` groups them — ancient, viewpoint, monument, church, lighthouse,
// nature, machine. All share one colour; the glyph says what sort of thing it
// is, the colour says it's worth stopping for.
//
// Kept to things you'd actually divert for: all of these are within 750 m of
// the path, most within 250 m. A landmark you can't reach on the day isn't a
// point of interest, it's trivia.
export default [
  {
    slug: "swcp-start-sculpture",
    poi: { type: "monument" },
    name: "South West Coast Path start marker",
    kind: "poi",
    lat: 51.21103, lon: -3.47369,
    address: "Minehead seafront",
    notes: "Mile zero. A pair of hands holding a map — the official start of all 630 miles",
    verified: null,
  },
  {
    slug: "furzebury-brake",
    poi: { type: "ancient" },
    name: "Furzebury Brake",
    kind: "poi",
    lat: 51.22393, lon: -3.52522,
    notes: "Archaeological site up on North Hill, a little above the path",
    verified: null,
  },
  {
    slug: "hurlstone-point",
    poi: { type: "viewpoint" },
    name: "Hurlstone Point",
    kind: "poi",
    lat: 51.23254, lon: -3.57934,
    notes: "The corner where the coast turns away west, looking back over Porlock Bay",
    verified: null,
  },
  {
    slug: "bossington-hill",
    poi: { type: "viewpoint" },
    name: "Bossington Hill",
    kind: "poi",
    lat: 51.22471, lon: -3.57197,
    notes: "Viewpoint over Porlock Vale and the bay",
    verified: null,
  },
  {
    slug: "liberator-monument",
    poi: { type: "monument" },
    name: "Liberator Monument",
    kind: "poi",
    lat: 51.21724, lon: -3.60250,
    notes: "Memorial to a wartime aircraft crash, right beside the path. What it commemorates needs checking on the ground",
    verified: null,
  },
  {
    slug: "culbone-church",
    poi: { type: "church" },
    name: "Culbone Church (St Beuno's)",
    kind: "poi",
    lat: 51.22143, lon: -3.65933,
    notes: "Said to be the smallest complete parish church in England — 35 feet long, seats 33, in the Domesday Book and almost certainly pre-Norman. No road reaches it; you can only arrive on foot, which is what makes passing it on the path worth the detour",
    verified: null,
  },
  {
    slug: "old-burrow-roman-fort",
    poi: { type: "ancient" },
    name: "Old Burrow Roman Fort",
    kind: "poi",
    lat: 51.23039, lon: -3.73721,
    notes: "A Roman fortlet on the moor above the path, set here to watch the Bristol Channel. About as remote as Roman Britain gets",
    verified: null,
  },
  {
    slug: "foreland-lighthouse",
    poi: { type: "lighthouse" },
    name: "Lynmouth Foreland Lighthouse",
    kind: "poi",
    lat: 51.24553, lon: -3.78660,
    notes: "Out on the Foreland, below the path — the most northerly point in Devon",
    verified: null,
  },
  {
    slug: "glen-lyn-gorge",
    poi: { type: "nature" },
    name: "Glen Lyn Gorge",
    kind: "poi",
    lat: 51.22919, lon: -3.82940,
    address: "Lynmouth",
    notes: "The gorge behind Lynmouth. The 1952 flood came down these rivers and destroyed much of the village",
    verified: null,
  },
  {
    slug: "cliff-railway",
    poi: { type: "machine" },
    name: "Lynton & Lynmouth Cliff Railway",
    kind: "poi",
    lat: 51.23147, lon: -3.83392,
    url: "https://www.cliffrailwaylynton.co.uk/",
    notes: "Opened 1890 and still entirely water-powered — the highest and steepest fully water-powered railway in the world. 862 feet of track, 500 feet of lift. Also the painless way up to Lynton if you're staying there",
    verified: null,
  },
  {
    slug: "valley-of-rocks",
    poi: { type: "nature" },
    name: "Valley of Rocks",
    kind: "poi",
    lat: 51.23175, lon: -3.85448,
    address: "Lynton",
    notes: "A dry valley running parallel to the sea, cut in the last Ice Age, with Castle Rock at its seaward end. Feral goats, introduced in 1976 and kept at around 25",
    verified: null,
  },
  {
    slug: "martinhoe-roman-fortlet",
    poi: { type: "ancient" },
    name: "Martinhoe Roman Fortlet",
    kind: "poi",
    lat: 51.22750, lon: -3.91603,
    notes: "A clifftop signal station held for ten or twenty years around AD 55–75, watching the Silures across the Channel in South Wales. Its beacon fires were placed to be seen from the sea",
    verified: null,
  },
  {
    slug: "heddons-mouth",
    poi: { type: "nature" },
    name: "Heddon's Mouth",
    kind: "poi",
    lat: 51.23027, lon: -3.92905,
    notes: "Where the Heddon reaches the sea, down the valley below the path. A restored 19th-century lime kiln stands on the beach",
    verified: null,
  },
  {
    slug: "great-hangman",
    poi: { type: "viewpoint" },
    name: "Great Hangman",
    kind: "poi",
    lat: 51.21467, lon: -4.00470,
    notes: "318 m: the highest point on the whole South West Coast Path, and with 244 m of cliff face the highest sea cliff in England",
    verified: null,
  },
  {
    slug: "little-hangman",
    poi: { type: "viewpoint" },
    name: "Little Hangman",
    kind: "poi",
    lat: 51.21422, lon: -4.02733,
    notes: "The last summit of the day, directly above Combe Martin",
    verified: null,
  },
  {
    slug: "hele-cornmill",
    poi: { type: "machine" },
    name: "Hele Corn Mill",
    kind: "poi",
    lat: 51.20806, lon: -4.09875,
    address: "Watermouth Road, Hele Bay, Ilfracombe, EX34 9QY",
    url: "http://www.helecornmill.com/",
    notes: "A watermill built in 1525, grinding flour until about 1940 and restored to working order in the 1970s. Tea room",
    verified: null,
  },
  {
    slug: "hillsborough",
    poi: { type: "ancient" },
    name: "Hillsborough",
    kind: "poi",
    lat: 51.21049, lon: -4.10349,
    notes: "An Iron Age promontory fort above Ilfracombe harbour, now a local nature reserve. Known locally as the sleeping elephant, for its outline",
    verified: null,
  },
  {
    slug: "verity",
    poi: { type: "monument" },
    name: "Verity",
    kind: "poi",
    lat: 51.21088, lon: -4.11159,
    address: "Ilfracombe pier",
    notes: "Damien Hirst's 20 m stainless steel and bronze figure at the harbour mouth, on loan to the town since 2012",
    verified: null,
  },
  {
    slug: "st-nicholas-chapel",
    poi: { type: "lighthouse" },
    name: "St Nicholas Chapel, Lantern Hill",
    kind: "poi",
    lat: 51.21112, lon: -4.11293,
    url: "https://www.stnicholaschapelilfracombe.co.uk/",
    notes: "A 14th-century chapel above the harbour that has kept a light for shipping since the Middle Ages, and still does. Said to be Britain's oldest working lighthouse",
    verified: null,
  },
  {
    slug: "capstone-hill",
    poi: { type: "viewpoint" },
    name: "Capstone Hill",
    kind: "poi",
    lat: 51.21175, lon: -4.12071,
    notes: "The hill on Ilfracombe's seafront, with a path spiralling to the top and a view along the whole town",
    verified: null,
  },
  {
    slug: "bull-point-lighthouse",
    poi: { type: "lighthouse" },
    name: "Bull Point Lighthouse",
    kind: "poi",
    lat: 51.19907, lon: -4.20115,
    notes: "First lit in 1879. The headland subsided in 1972, and the present tower was built in 1974 using the old equipment",
    verified: null,
  },
  {
    slug: "morte-point",
    poi: { type: "nature" },
    name: "Morte Point",
    kind: "poi",
    lat: 51.18779, lon: -4.23063,
    notes: "The headland at the corner of the day, with jagged slate reefs running out to sea and Woolacombe's beach in view to the south",
    verified: null,
  },
  {
    slug: "barricane-beach",
    poi: { type: "nature" },
    name: "Barricane Beach",
    kind: "poi",
    lat: 51.17627, lon: -4.21346,
    notes: "A small cove below the path just north of Woolacombe, known for the shells that wash up on it, cowries among them",
    verified: null,
  },
  {
    slug: "baggy-point",
    poi: { type: "nature" },
    name: "Baggy Point",
    kind: "poi",
    // OSM node 531628126.
    lat: 51.14304, lon: -4.26087,
    notes: "The headland between Putsborough and Croyde. The Hyde family gave it to the National Trust in 1939",
    verified: null,
  },
  {
    slug: "baggy-point-coastguard-pole",
    poi: { type: "monument" },
    name: "Baggy Point coastguard pole",
    kind: "poi",
    // OSM node 10748990206.
    lat: 51.14375, lon: -4.25737,
    notes: "A post standing in for a ship's mast, used by the coastguard to practise rocket-line and breeches-buoy rescues. There were several on the North Devon coast; this is the only one left",
    verified: null,
  },
  {
    slug: "baggy-point-whale-bones",
    poi: { type: "monument" },
    name: "Baggy Point whale bones",
    kind: "poi",
    // OSM node 10606708831.
    lat: 51.13689, lon: -4.24655,
    notes: "Beside the path: the bones of a whale washed up on Croyde beach in 1915, kept here by the Hyde family",
    verified: null,
  },
  {
    slug: "braunton-burrows",
    poi: { type: "nature" },
    name: "Braunton Burrows",
    kind: "poi",
    // Centre of OSM way 142670333.
    lat: 51.09281, lon: -4.20464,
    notes: "One of Britain's largest sand dune systems, at the heart of the North Devon UNESCO biosphere reserve. From 1943 to D-Day it was the US Army's Assault Training Center; it's still used for military training, but open",
    verified: null,
  },
  {
    slug: "braunton-burrows-landing-craft",
    poi: { type: "monument" },
    name: "D-Day practice landing craft",
    kind: "poi",
    // OSM way 145785367, "WW2 Landing Craft".
    lat: 51.07677, lon: -4.19828,
    notes: "Concrete replicas of landing craft in the south of the Burrows, where US troops rehearsed loading and unloading before D-Day. A memorial to them stands on one. Off the American Road",
    verified: null,
  },
  {
    slug: "crow-point",
    poi: { type: "lighthouse" },
    name: "Crow Point",
    kind: "poi",
    // OSM node 1556351274, Crow Point Light.
    lat: 51.06615, lon: -4.18982,
    notes: "The sand spit at the mouth of the Taw and Torridge, with a small navigation light",
    verified: null,
  },
  {
    slug: "braunton-great-field",
    poi: { type: "ancient" },
    name: "Braunton Great Field",
    kind: "poi",
    // OSM node 1561459201.
    lat: 51.10228, lon: -4.17494,
    notes: "One of only two medieval open strip field systems surviving in England, divided into strips by 1202",
    verified: null,
  },
  {
    slug: "barnstaple-long-bridge",
    poi: { type: "monument" },
    name: "Barnstaple Long Bridge",
    kind: "poi",
    // Centre of OSM way 30693088.
    lat: 51.07751, lon: -4.06008,
    notes: "Sixteen pointed arches over the Taw, 159 m long. There's been work on it since about 1280; widened in 1796. Grade I listed and a scheduled monument. The route crosses it",
    verified: null,
  },
  {
    slug: "queen-annes-walk",
    poi: { type: "monument" },
    name: "Queen Anne's Walk and the Tome Stone",
    kind: "poi",
    // OSM node 6904883328, the stone under the colonnade.
    lat: 51.07914, lon: -4.06141,
    notes: "The merchants' exchange of 1713, a colonnade on the Strand. Under it, the Tome Stone: a round stone table where Barnstaple merchants sealed their deals. Now a café",
    verified: null,
  },
  {
    slug: "barnstaple-castle-mound",
    poi: { type: "ancient" },
    name: "Castle Mound",
    kind: "poi",
    // Centre of OSM way 29024588.
    lat: 51.08078, lon: -4.06289,
    notes: "The tree-covered motte of Barnstaple's Norman castle, all that survives of it. A ruin by 1326",
    verified: null,
  },
  {
    slug: "barnstaple-pannier-market",
    poi: { type: "monument" },
    name: "Pannier Market and Butchers Row",
    kind: "poi",
    // Centre of OSM way 1137962309.
    lat: 51.08054, lon: -4.05951,
    url: "https://www.barnstaple.co.uk/spaces/barnstaple-pannier-market",
    notes: "Victorian covered market of 1855, refurbished in 2023. Open Tuesday to Saturday, 9am–4pm; the produce markets are Tuesday, Friday and Saturday",
    verified: null,
  },
  {
    slug: "fremington-quay",
    poi: { type: "monument" },
    name: "Fremington Quay",
    kind: "poi",
    // Centre of OSM way 187941408, the old station.
    lat: 51.07972, lon: -4.12008,
    notes: "Once the busiest quay between Bristol and Land's End, shipping ball clay. The last cargo ship called in 1969. The station and signal box are now a café and heritage centre",
    verified: null,
  },
  {
    slug: "isley-marsh",
    poi: { type: "nature" },
    name: "Isley Marsh",
    kind: "poi",
    // OSM node 828227068.
    lat: 51.07269, lon: -4.15629,
    url: "https://www.rspb.org.uk/days-out/reserves/isley-marsh",
    notes: "RSPB saltmarsh and mudflats, seen from the Tarka Trail along its south side; there are no paths into the reserve. Best in winter, for ducks and waders",
    verified: null,
  },
  {
    slug: "instow-signal-box",
    poi: { type: "machine" },
    name: "Instow Signal Box",
    kind: "poi",
    // Centre of OSM way 165323331.
    lat: 51.05008, lon: -4.17909,
    url: "https://tarkatrail.org.uk/plan-your-visit/instow-signal-box/",
    notes: "Built 1873 and the first signal box in the UK to be listed, with its levers and the level crossing gates. On the Tarka Trail at the south end of the village. Open occasional Sundays and bank holidays, Easter to October, 2–5pm",
    verified: null,
  },
];
