// Things worth stopping for. Matched like everything else — by position, near
// the route — so a section picks up whatever it passes.
//
// `poi.type` groups them — ancient, viewpoint, monument, church, lighthouse,
// nature, machine. All share one colour; the glyph says what sort of thing it
// is, the colour says it's worth stopping for.
//
// Kept to things you'd actually divert for: all of these are within 750 m of
// the path, most within 250 m. A landmark you can't reach on the day isn't a
// point of interest, it's trivia.
export default [
  {
    slug: "swcp-start-sculpture",
    poi: { type: "monument" },
    name: "South West Coast Path start marker",
    kind: "poi",
    lat: 51.21103, lon: -3.47369,
    address: "Minehead seafront",
    notes: "Mile zero. A pair of hands holding a map — the official start of all 630 miles",
    verified: null,
  },
  {
    slug: "furzebury-brake",
    poi: { type: "ancient" },
    name: "Furzebury Brake",
    kind: "poi",
    lat: 51.22393, lon: -3.52522,
    notes: "Archaeological site up on North Hill, a little above the path",
    verified: null,
  },
  {
    slug: "hurlstone-point",
    poi: { type: "viewpoint" },
    name: "Hurlstone Point",
    kind: "poi",
    lat: 51.23254, lon: -3.57934,
    notes: "The corner where the coast turns away west, looking back over Porlock Bay",
    verified: null,
  },
  {
    slug: "bossington-hill",
    poi: { type: "viewpoint" },
    name: "Bossington Hill",
    kind: "poi",
    lat: 51.22471, lon: -3.57197,
    notes: "Viewpoint over Porlock Vale and the bay",
    verified: null,
  },
  {
    slug: "liberator-monument",
    poi: { type: "monument" },
    name: "Liberator Monument",
    kind: "poi",
    lat: 51.21724, lon: -3.60250,
    notes: "Memorial to a wartime aircraft crash, right beside the path. What it commemorates needs checking on the ground",
    verified: null,
  },
  {
    slug: "culbone-church",
    poi: { type: "church" },
    name: "Culbone Church (St Beuno's)",
    kind: "poi",
    lat: 51.22143, lon: -3.65933,
    notes: "Said to be the smallest complete parish church in England — 35 feet long, seats 33, in the Domesday Book and almost certainly pre-Norman. No road reaches it; you can only arrive on foot, which is what makes passing it on the path worth the detour",
    verified: null,
  },
  {
    slug: "old-burrow-roman-fort",
    poi: { type: "ancient" },
    name: "Old Burrow Roman Fort",
    kind: "poi",
    lat: 51.23039, lon: -3.73721,
    notes: "A Roman fortlet on the moor above the path, set here to watch the Bristol Channel. About as remote as Roman Britain gets",
    verified: null,
  },
  {
    slug: "foreland-lighthouse",
    poi: { type: "lighthouse" },
    name: "Lynmouth Foreland Lighthouse",
    kind: "poi",
    lat: 51.24553, lon: -3.78660,
    notes: "Out on the Foreland, below the path — the most northerly point in Devon",
    verified: null,
  },
  {
    slug: "glen-lyn-gorge",
    poi: { type: "nature" },
    name: "Glen Lyn Gorge",
    kind: "poi",
    lat: 51.22919, lon: -3.82940,
    address: "Lynmouth",
    notes: "The gorge behind Lynmouth. The 1952 flood came down these rivers and destroyed much of the village",
    verified: null,
  },
  {
    slug: "cliff-railway",
    poi: { type: "machine" },
    name: "Lynton & Lynmouth Cliff Railway",
    kind: "poi",
    lat: 51.23147, lon: -3.83392,
    url: "https://www.cliffrailwaylynton.co.uk/",
    notes: "Opened 1890 and still entirely water-powered — the highest and steepest fully water-powered railway in the world. 862 feet of track, 500 feet of lift. Also the painless way up to Lynton if you're staying there",
    verified: null,
  },
  {
    slug: "valley-of-rocks",
    poi: { type: "nature" },
    name: "Valley of Rocks",
    kind: "poi",
    lat: 51.23175, lon: -3.85448,
    address: "Lynton",
    notes: "A dry valley running parallel to the sea, cut in the last Ice Age, with Castle Rock at its seaward end. Feral goats, introduced in 1976 and kept at around 25",
    verified: null,
  },
  {
    slug: "martinhoe-roman-fortlet",
    poi: { type: "ancient" },
    name: "Martinhoe Roman Fortlet",
    kind: "poi",
    lat: 51.22750, lon: -3.91603,
    notes: "A clifftop signal station held for ten or twenty years around AD 55–75, watching the Silures across the Channel in South Wales. Its beacon fires were placed to be seen from the sea",
    verified: null,
  },
  {
    slug: "heddons-mouth",
    poi: { type: "nature" },
    name: "Heddon's Mouth",
    kind: "poi",
    lat: 51.23027, lon: -3.92905,
    notes: "Where the Heddon reaches the sea, down the valley below the path. A restored 19th-century lime kiln stands on the beach",
    verified: null,
  },
  {
    slug: "great-hangman",
    poi: { type: "viewpoint" },
    name: "Great Hangman",
    kind: "poi",
    lat: 51.21467, lon: -4.00470,
    notes: "318 m: the highest point on the whole South West Coast Path, and with 244 m of cliff face the highest sea cliff in England",
    verified: null,
  },
  {
    slug: "little-hangman",
    poi: { type: "viewpoint" },
    name: "Little Hangman",
    kind: "poi",
    lat: 51.21422, lon: -4.02733,
    notes: "The last summit of the day, directly above Combe Martin",
    verified: null,
  },
  {
    slug: "hele-cornmill",
    poi: { type: "machine" },
    name: "Hele Corn Mill",
    kind: "poi",
    lat: 51.20806, lon: -4.09875,
    address: "Watermouth Road, Hele Bay, Ilfracombe, EX34 9QY",
    url: "http://www.helecornmill.com/",
    notes: "A watermill built in 1525, grinding flour until about 1940 and restored to working order in the 1970s. Tea room",
    verified: null,
  },
  {
    slug: "hillsborough",
    poi: { type: "ancient" },
    name: "Hillsborough",
    kind: "poi",
    lat: 51.21049, lon: -4.10349,
    notes: "An Iron Age promontory fort above Ilfracombe harbour, now a local nature reserve. Known locally as the sleeping elephant, for its outline",
    verified: null,
  },
  {
    slug: "verity",
    poi: { type: "monument" },
    name: "Verity",
    kind: "poi",
    lat: 51.21088, lon: -4.11159,
    address: "Ilfracombe pier",
    notes: "Damien Hirst's 20 m stainless steel and bronze figure at the harbour mouth, on loan to the town since 2012",
    verified: null,
  },
  {
    slug: "st-nicholas-chapel",
    poi: { type: "lighthouse" },
    name: "St Nicholas Chapel, Lantern Hill",
    kind: "poi",
    lat: 51.21112, lon: -4.11293,
    url: "https://www.stnicholaschapelilfracombe.co.uk/",
    notes: "A 14th-century chapel above the harbour that has kept a light for shipping since the Middle Ages, and still does. Said to be Britain's oldest working lighthouse",
    verified: null,
  },
  {
    slug: "capstone-hill",
    poi: { type: "viewpoint" },
    name: "Capstone Hill",
    kind: "poi",
    lat: 51.21175, lon: -4.12071,
    notes: "The hill on Ilfracombe's seafront, with a path spiralling to the top and a view along the whole town",
    verified: null,
  },
  {
    slug: "bull-point-lighthouse",
    poi: { type: "lighthouse" },
    name: "Bull Point Lighthouse",
    kind: "poi",
    lat: 51.19907, lon: -4.20115,
    notes: "First lit in 1879. The headland subsided in 1972, and the present tower was built in 1974 using the old equipment",
    verified: null,
  },
  {
    slug: "morte-point",
    poi: { type: "nature" },
    name: "Morte Point",
    kind: "poi",
    lat: 51.18779, lon: -4.23063,
    notes: "The headland at the corner of the day, with jagged slate reefs running out to sea and Woolacombe's beach in view to the south",
    verified: null,
  },
  {
    slug: "barricane-beach",
    poi: { type: "nature" },
    name: "Barricane Beach",
    kind: "poi",
    lat: 51.17627, lon: -4.21346,
    notes: "A small cove below the path just north of Woolacombe, known for the shells that wash up on it, cowries among them",
    verified: null,
  },
  {
    slug: "baggy-point",
    poi: { type: "nature" },
    name: "Baggy Point",
    kind: "poi",
    // OSM node 531628126.
    lat: 51.14304, lon: -4.26087,
    notes: "The headland between Putsborough and Croyde. The Hyde family gave it to the National Trust in 1939",
    verified: null,
  },
  {
    slug: "baggy-point-coastguard-pole",
    poi: { type: "monument" },
    name: "Baggy Point coastguard pole",
    kind: "poi",
    // OSM node 10748990206.
    lat: 51.14375, lon: -4.25737,
    notes: "A post standing in for a ship's mast, used by the coastguard to practise rocket-line and breeches-buoy rescues. There were several on the North Devon coast; this is the only one left",
    verified: null,
  },
  {
    slug: "baggy-point-whale-bones",
    poi: { type: "monument" },
    name: "Baggy Point whale bones",
    kind: "poi",
    // OSM node 10606708831.
    lat: 51.13689, lon: -4.24655,
    notes: "Beside the path: the bones of a whale washed up on Croyde beach in 1915, kept here by the Hyde family",
    verified: null,
  },
  {
    slug: "braunton-burrows",
    poi: { type: "nature" },
    name: "Braunton Burrows",
    kind: "poi",
    // Centre of OSM way 142670333.
    lat: 51.09281, lon: -4.20464,
    notes: "One of Britain's largest sand dune systems, at the heart of the North Devon UNESCO biosphere reserve. From 1943 to D-Day it was the US Army's Assault Training Center; it's still used for military training, but open",
    verified: null,
  },
  {
    slug: "braunton-burrows-landing-craft",
    poi: { type: "monument" },
    name: "D-Day practice landing craft",
    kind: "poi",
    // OSM way 145785367, "WW2 Landing Craft".
    lat: 51.07677, lon: -4.19828,
    notes: "Concrete replicas of landing craft in the south of the Burrows, where US troops rehearsed loading and unloading before D-Day. A memorial to them stands on one. Off the American Road",
    verified: null,
  },
  {
    slug: "crow-point",
    poi: { type: "lighthouse" },
    name: "Crow Point",
    kind: "poi",
    // OSM node 1556351274, Crow Point Light.
    lat: 51.06615, lon: -4.18982,
    notes: "The sand spit at the mouth of the Taw and Torridge, with a small navigation light",
    verified: null,
  },
  {
    slug: "braunton-great-field",
    poi: { type: "ancient" },
    name: "Braunton Great Field",
    kind: "poi",
    // OSM node 1561459201.
    lat: 51.10228, lon: -4.17494,
    notes: "One of only two medieval open strip field systems surviving in England, divided into strips by 1202",
    verified: null,
  },
  {
    slug: "barnstaple-long-bridge",
    poi: { type: "monument" },
    name: "Barnstaple Long Bridge",
    kind: "poi",
    // Centre of OSM way 30693088.
    lat: 51.07751, lon: -4.06008,
    notes: "Sixteen pointed arches over the Taw, 159 m long. There's been work on it since about 1280; widened in 1796. Grade I listed and a scheduled monument. The route crosses it",
    verified: null,
  },
  {
    slug: "queen-annes-walk",
    poi: { type: "monument" },
    name: "Queen Anne's Walk and the Tome Stone",
    kind: "poi",
    // OSM node 6904883328, the stone under the colonnade.
    lat: 51.07914, lon: -4.06141,
    notes: "The merchants' exchange of 1713, a colonnade on the Strand. Under it, the Tome Stone: a round stone table where Barnstaple merchants sealed their deals. Now a café",
    verified: null,
  },
  {
    slug: "barnstaple-castle-mound",
    poi: { type: "ancient" },
    name: "Castle Mound",
    kind: "poi",
    // Centre of OSM way 29024588.
    lat: 51.08078, lon: -4.06289,
    notes: "The tree-covered motte of Barnstaple's Norman castle, all that survives of it. A ruin by 1326",
    verified: null,
  },
  {
    slug: "barnstaple-pannier-market",
    poi: { type: "monument" },
    name: "Pannier Market and Butchers Row",
    kind: "poi",
    // Centre of OSM way 1137962309.
    lat: 51.08054, lon: -4.05951,
    url: "https://www.barnstaple.co.uk/spaces/barnstaple-pannier-market",
    notes: "Victorian covered market of 1855, refurbished in 2023. Open Tuesday to Saturday, 9am–4pm; the produce markets are Tuesday, Friday and Saturday",
    verified: null,
  },
  {
    slug: "fremington-quay",
    poi: { type: "monument" },
    name: "Fremington Quay",
    kind: "poi",
    // Centre of OSM way 187941408, the old station.
    lat: 51.07972, lon: -4.12008,
    notes: "Once the busiest quay between Bristol and Land's End, shipping ball clay. The last cargo ship called in 1969. The station and signal box are now a café and heritage centre",
    verified: null,
  },
  {
    slug: "isley-marsh",
    poi: { type: "nature" },
    name: "Isley Marsh",
    kind: "poi",
    // OSM node 828227068.
    lat: 51.07269, lon: -4.15629,
    url: "https://www.rspb.org.uk/days-out/reserves/isley-marsh",
    notes: "RSPB saltmarsh and mudflats, seen from the Tarka Trail along its south side; there are no paths into the reserve. Best in winter, for ducks and waders",
    verified: null,
  },
  {
    slug: "instow-signal-box",
    poi: { type: "machine" },
    name: "Instow Signal Box",
    kind: "poi",
    // Centre of OSM way 165323331.
    lat: 51.05008, lon: -4.17909,
    url: "https://tarkatrail.org.uk/plan-your-visit/instow-signal-box/",
    notes: "Built 1873 and the first signal box in the UK to be listed, with its levers and the level crossing gates. On the Tarka Trail at the south end of the village. Open occasional Sundays and bank holidays, Easter to October, 2–5pm",
    verified: null,
  },
  {
    slug: "bideford-long-bridge",
    poi: { type: "monument" },
    name: "Bideford Long Bridge",
    kind: "poi",
    // Centre of OSM way 19852368.
    lat: 51.01647, lon: -4.20324,
    url: "https://en.wikipedia.org/wiki/Bideford_Long_Bridge",
    notes: "The path's way over the Torridge. One of the longest medieval bridges in England: 24 arches of different widths, stone built in the 14th century around a 13th-century timber bridge. Grade I listed",
    verified: null,
  },
  {
    slug: "chudleigh-fort",
    poi: { type: "monument" },
    name: "Chudleigh Fort",
    kind: "poi",
    // Centre of OSM way 184552651.
    lat: 51.01603, lon: -4.19855,
    url: "https://historicengland.org.uk/listing/the-list/list-entry/1208657",
    notes: "Parliamentarian gun fort of 1642 on the hill above East-the-Water, guarding the bridge; stormed by Royalists in 1643. Now a public park. 200 m up from the east end of the bridge",
    verified: null,
  },
  {
    slug: "burton-at-bideford",
    name: "Burton at Bideford",
    kind: "poi",
    // Centre of OSM way 169586912.
    lat: 51.02127, lon: -4.20514,
    address: "Kingsley Road, Bideford, EX39 2QQ",
    phone: "01237 471455",
    url: "https://www.burtonartgallery.co.uk/",
    notes: "Art gallery and museum of the town's history, free, by Victoria Park; also Bideford's tourist information centre. Closed Mondays",
    verified: null,
  },
  {
    slug: "north-devon-maritime-museum",
    name: "North Devon Maritime Museum",
    kind: "poi",
    // OSM node 2590329861.
    lat: 51.05243, lon: -4.19415,
    address: "Odun House, Odun Road, Appledore, EX39 1PT",
    phone: "01237 422064",
    url: "https://northdevonmaritimemuseum.co.uk/",
    notes: "Shipbuilding, fishing and emigration from the Torridge ports, 150 m up from the quay. Admission charge. Directories give 10.30am–5pm daily, April to October",
    verified: null,
  },
  {
    slug: "northam-burrows",
    poi: { type: "nature" },
    name: "Northam Burrows",
    kind: "poi",
    // The Burrows Centre, centre of OSM way 150910745.
    lat: 51.05583, lon: -4.22662,
    url: "https://www.torridge.gov.uk/northamburrows",
    notes: "Country park and SSSI: grazed coastal common, saltmarsh and dunes behind the Pebble Ridge, a bank of grey cobbles along the shore. Sheep and horses graze it, and ground-nesting birds in spring, so dogs on a lead. The Burrows Centre is a seasonal visitor centre; toilets all year",
    verified: null,
  },
  {
    slug: "kipling-tors",
    poi: { type: "nature" },
    name: "Kipling Tors",
    kind: "poi",
    // Centre of OSM way 208447310, the gorse and scrub of Kipling Tor.
    lat: 51.03778, lon: -4.25436,
    url: "https://www.nationaltrust.org.uk/visit/devon/bideford-bay-and-hartland/bideford-bay-and-hartland-kipling-tors-walk",
    notes: "Gorse and bracken hill above Westward Ho!, given to the National Trust in 1938 in memory of Kipling, who was at school in the town from 1878 to 1882 and set Stalky & Co. here. Views to Lundy",
    verified: null,
  },
  {
    slug: "peppercombe",
    poi: { type: "nature" },
    name: "Peppercombe",
    kind: "poi",
    // The waterfall where the path crosses the stream, OSM node 3215566236.
    lat: 50.99526, lon: -4.30749,
    url: "https://www.nationaltrust.org.uk/visit/devon/bideford-bay-and-hartland",
    notes: "National Trust valley with red Triassic cliffs. On the headland, the banks of an Iron Age promontory fort, Peppercombe Castle; a Victorian house of the same name there was lost to erosion. A path climbs the valley to Horns Cross",
    verified: null,
  },
  {
    slug: "bucks-mills",
    poi: { type: "monument" },
    name: "Bucks Mills",
    kind: "poi",
    // OSM place node 945908826.
    lat: 50.98798, lon: -4.34501,
    url: "https://www.nationaltrust.org.uk/bideford-bay-and-hartland/features/bucks-mills-cabin",
    notes: "Hamlet at the foot of a wooded valley, with two lime kilns above the beach that burnt Welsh limestone for fertiliser. The Cabin by the beach path was the summer studio of the artists Judith Ackland and Mary Stella Edwards for fifty years; the National Trust opens it on occasional open days",
    verified: null,
  },
  {
    slug: "clovelly-village",
    name: "Clovelly",
    kind: "poi",
    // OSM node 48227694.
    lat: 50.99803, lon: -4.39876,
    phone: "01237 431781",
    url: "https://www.clovelly.co.uk/tickets/",
    notes: "Privately owned, car-free fishing village: one cobbled street stepping down to the harbour, goods still hauled on sledges. Admission, £10.90 for an adult in 2026, covers the village, Fisherman's Cottage, the Kingsley Museum and Clovelly Court Gardens, and is taken at the Visitor Centre; walkers' accounts say those arriving on the path aren't charged. Dogs on leads. Open all year except Christmas Day",
    verified: "2026-09-13",
  },
  {
    slug: "angels-wings",
    poi: { type: "monument" },
    name: "Angel's Wings",
    kind: "poi",
    // OSM node 1164241068.
    lat: 51.00788, lon: -4.41382,
    notes: "Carved wooden shelter on the path, built in 1826 by Sir James Hamlyn Williams of Clovelly Court to look across the bay towards his daughter's home. The carving is said to be a former butler's work",
    verified: null,
  },
  {
    slug: "gallantry-bower",
    poi: { type: "viewpoint" },
    name: "Gallantry Bower",
    kind: "poi",
    // OSM locality node 1352653010.
    lat: 51.01028, lon: -4.41819,
    notes: "A patch of heath among the woods, on top of a near-vertical cliff about 100 m high. A tumulus on the top",
    verified: null,
  },
  {
    slug: "mouth-mill",
    poi: { type: "nature" },
    name: "Mouth Mill and Blackchurch Rock",
    kind: "poi",
    // Blackchurch Rock, OSM node 5520629722.
    lat: 51.01397, lon: -4.42644,
    notes: "Pebble cove at the bottom of a steep wooded valley, with a ruined lime kiln and Blackchurch Rock, a sea stack",
    verified: null,
  },
  {
    slug: "windbury-head-camp",
    poi: { type: "ancient" },
    name: "Windbury Head Camp",
    kind: "poi",
    // OSM node 1305261760.
    lat: 51.01308, lon: -4.44392,
    notes: "Earthworks of an Iron Age enclosure on the headland, beside the path",
    verified: null,
  },
  {
    slug: "wellington-bomber-memorial",
    poi: { type: "monument" },
    name: "Wellington bomber memorial",
    kind: "poi",
    // OSM node 1321793933.
    lat: 51.01319, lon: -4.44668,
    notes: "Plaque to the five crew of a Wellington that flew into the cliff beneath here in fog on 13 April 1942: two Canadians, a New Zealander and two RAF officers. Put up in 1988. An engine recovered from the wreck is in the museum at Hartland Quay",
    verified: null,
  },
  {
    slug: "hartland-point",
    poi: { type: "lighthouse" },
    name: "Hartland Point",
    kind: "poi",
    // Viewpoint above the lighthouse, OSM node 1347469551; the tower itself
    // (way 1026250380) is 300 m off the path and can't be reached.
    lat: 51.02030, lon: -4.52325,
    url: "https://www.trinityhouse.co.uk/lighthouses-and-lightvessels/hartland-point-lighthouse",
    notes: "The corner of Devon, where the Bristol Channel ends and the coast turns south. The lighthouse below was built by Trinity House in 1874 and replaced by an LED beacon in front of it in 2012. The road down to it is closed by rockfalls, so it's seen from above",
    verified: null,
  },
  {
    slug: "glenart-castle-memorial",
    poi: { type: "monument" },
    name: "Glenart Castle memorial",
    kind: "poi",
    // OSM node 4524630405.
    lat: 51.01853, lon: -4.52533,
    url: "https://en.wikipedia.org/wiki/HMHS_Glenart_Castle",
    notes: "Stone on the path for the hospital ship Glenart Castle, torpedoed off Hartland Point by UC-56 on 26 February 1918, lit and marked with red crosses. 162 died, eight of them nurses. Dedicated in 2002",
    verified: null,
  },
  {
    slug: "blackpool-mill",
    poi: { type: "nature" },
    name: "Blackpool Mill",
    kind: "poi",
    // The waterfall, OSM node 4130248216.
    lat: 51.00546, lon: -4.52996,
    url: "https://www.hartlandabbey.com/blackpool-mill/",
    notes: "Stream valley where a waterfall runs out onto a pebble beach. The cottage behind is Hartland Abbey's holiday let, Barton Cottage in the BBC's Sense and Sensibility. A track runs inland to the Abbey",
    verified: null,
  },
  {
    slug: "pleasure-house-folly",
    poi: { type: "monument" },
    name: "The Pleasure House",
    kind: "poi",
    // OSM node 12250345207.
    lat: 50.99774, lon: -4.52893,
    url: "https://historicengland.org.uk/listing/the-list/list-entry/1333133",
    notes: "Ruined tower on the Warren above Hartland Quay, probably 16th century and remodelled in the 18th as a viewing house for Hartland Abbey, reputedly so a carriage could be backed in to admire the view. Lined up with St Nectan's tower at Stoke",
    verified: null,
  },
  {
    slug: "st-nectans-stoke",
    poi: { type: "church" },
    name: "St Nectan's Church, Stoke",
    kind: "poi",
    // Centre of OSM way 77499301.
    lat: 50.99493, lon: -4.51649,
    url: "https://www.nationalchurchestrust.org/church/st-nectan-hartland",
    notes: "Hartland's parish church, called the Cathedral of North Devon. Its 128 ft tower of about 1420 is a daymark from the sea. Up the lane from Hartland Quay",
    verified: null,
  },
  {
    slug: "hartland-quay-museum",
    name: "Hartland Quay Museum",
    kind: "poi",
    // In the Hartland Quay Hotel's buildings; centre of OSM way 5882717.
    lat: 50.99476, lon: -4.53366,
    address: "Hartland Quay, EX39 6DU",
    phone: "01237 441218",
    url: "https://hartlandquayhotel.co.uk/visit/",
    notes: "Four centuries of shipwrecks on this coast, the lifesaving services, and the quay's trade. Easter to October half term, 11am–4pm. The quay's cliffs, folded beds of sandstone and mudstone, draw geologists",
    verified: "2026-09-13",
  },
  {
    slug: "spekes-mill-mouth",
    poi: { type: "nature" },
    name: "Speke's Mill Mouth",
    kind: "poi",
    // The waterfall, OSM node 970733828.
    lat: 50.98401, lon: -4.52903,
    notes: "Milford Water drops off the cliff to the beach in a series of falls, the main one about 15 m. Viewed from the grass above; the path passes the top",
    verified: null,
  },
  {
    slug: "embury-beacon",
    poi: { type: "ancient" },
    name: "Embury Beacon",
    kind: "poi",
    // OSM node 9759366459.
    lat: 50.94722, lon: -4.53986,
    url: "https://historicengland.org.uk/listing/the-list/list-entry/1003845",
    notes: "Iron Age promontory fort almost entirely lost to the sea; a fragment of two ramparts survives on the cliff edge. Excavated in the 1970s and again recently because of the erosion",
    verified: null,
  },
  {
    slug: "ronald-duncans-hut",
    poi: { type: "monument" },
    name: "Ronald Duncan's Hut",
    kind: "poi",
    // Centre of OSM way 430650740.
    lat: 50.92993, lon: -4.54407,
    url: "https://specialcollectionsarchive.exeter.ac.uk/exhibits/show/ronaldduncan/writinghut",
    notes: "The poet and playwright's stone writing hut above Marsland Mouth, built in the 1960s on the site of an old lookout and restored by his daughter. Left open as a shelter for walkers",
    verified: null,
  },
  {
    slug: "hawkers-hut",
    poi: { type: "monument" },
    name: "Hawker's Hut",
    kind: "poi",
    // OSM node 1298693794.
    lat: 50.90699, lon: -4.56326,
    url: "https://www.nationaltrust.org.uk/visit/cornwall/morwenstow",
    notes: "Driftwood hut in the cliff below the path, built from wreck timber by Robert Hawker, vicar of Morwenstow, who wrote poetry there; visitors included Tennyson and Kingsley. The smallest building the National Trust owns. A few steps down from the path",
    verified: null,
  },
  {
    slug: "morwenstow-church",
    poi: { type: "church" },
    name: "Morwenstow Church",
    kind: "poi",
    // Centre of OSM way 96610543.
    lat: 50.90930, lon: -4.55455,
    url: "https://www.chct.info/histories/morwenstow-st-morwenna-st-john-the-baptist/",
    notes: "St Morwenna and St John the Baptist, Hawker's church, up the combe from Vicarage Cliff. He brought back the harvest festival here in 1843 and buried drowned sailors in the churchyard, where a replica of the Caledonia's figurehead marks the grave of five of her crew; the original is inside",
    verified: null,
  },
  {
    slug: "gchq-bude",
    poi: { type: "machine" },
    name: "GCHQ Bude",
    kind: "poi",
    // Centre of OSM way 79137091.
    lat: 50.88555, lon: -4.55332,
    url: "https://en.wikipedia.org/wiki/GCHQ_Bude",
    notes: "Twenty-one satellite dishes, some 30 m across, on the old RAF Cleave airfield inland of the path. A listening station since 1969. No public access",
    verified: null,
  },
  {
    slug: "bude-sea-pool",
    name: "Bude Sea Pool",
    kind: "poi",
    // Centre of OSM way 286684106.
    lat: 50.83259, lon: -4.55404,
    url: "https://en.wikipedia.org/wiki/Bude_Sea_Pool",
    notes: "Tidal pool in the rocks below Summerleaze, built in 1930 and refilled by every tide; 91 m long. Free, all year, run by the Friends of Bude Sea Pool. Dogs on a lead beside it, not in the water",
    verified: null,
  },
  {
    slug: "bude-castle",
    name: "The Castle, Bude",
    kind: "poi",
    // OSM node 12558768414, the Heritage Centre.
    lat: 50.82905, lon: -4.54881,
    address: "The Wharf, Bude, EX23 8LG",
    phone: "01288 357300",
    url: "https://www.thecastlebude.co.uk/heritage-centre/",
    notes: "Built in 1830 by the inventor Goldsworthy Gurney on the sand, on what's claimed as the first concrete raft foundation. Free heritage centre on Bude's canal, shipwrecks and Gurney; galleries and a café. Directories give 10am–5pm daily",
    verified: null,
  },
  {
    slug: "storm-tower-bude",
    poi: { type: "monument" },
    name: "The Storm Tower",
    kind: "poi",
    // Centre of OSM way 560082922. Wikidata's position, from the listing, is
    // 130 m south-west, which matches where it stood before the last move.
    lat: 50.82898, lon: -4.55490,
    url: "https://www.bude-stratton.gov.uk/budes-iconic-storm-tower-a-journey-from-peril-to-preservation/",
    notes: "The \"Pepper Pot\" on Compass Point: an octagonal coastguard lookout built in 1835 for Sir Thomas Acland, modelled on the Tower of the Winds in Athens, with the compass points carved on its faces. Moved inland in 1881, and again in 2023–24, stone by stone, about 100 m back from the eroding cliff",
    verified: null,
  },
  {
    slug: "millook-haven",
    poi: { type: "nature" },
    name: "Millook Haven",
    kind: "poi",
    // OSM node 33795977, the hamlet at the head of the beach.
    lat: 50.77104, lon: -4.57561,
    url: "https://depositsmag.com/2020/10/03/fabulous-folds-variscan-tectonics-in-southwest-england/",
    notes: "Cove below the hamlet, where the cliff shows the Crackington Formation's sandstones and shales folded into stacked zigzag chevrons during the Variscan mountain-building at the end of the Carboniferous",
    verified: null,
  },
  {
    slug: "dizzard-point",
    poi: { type: "nature" },
    name: "Dizzard Point",
    kind: "poi",
    // OSM node 4281743257, the trig pillar.
    lat: 50.76100, lon: -4.59990,
    url: "https://en.wikipedia.org/wiki/Boscastle_to_Widemouth",
    notes: "Dwarf oak wood on the unstable slopes between the path and the shore, sessile oaks a few metres high with rowan and wild service tree; ancient woodland of international importance for its lichens. In the Boscastle to Widemouth SSSI. No access; seen from the path",
    verified: null,
  },
  {
    slug: "st-gennys-church",
    poi: { type: "church" },
    name: "St Gennys Church",
    kind: "poi",
    // Centre of OSM way 159512817.
    lat: 50.74458, lon: -4.62506,
    url: "https://www.britainexpress.com/counties/cornwall/churches/sy-gennys.htm",
    notes: "Largely 12th-century, on the site of an earlier church, on the hill above Crackington Haven. The lower stages of the tower are Norman, one of only a few in Cornwall, and the font bowl is Tintagel greenstone. North aisle 15th century",
    verified: null,
  },
  {
    slug: "high-cliff",
    poi: { type: "viewpoint" },
    name: "High Cliff",
    kind: "poi",
    // OSM node 1720918939, the summit.
    lat: 50.71766, lon: -4.65039,
    url: "https://www.iwalkcornwall.co.uk/pi/high_cliff",
    notes: "Cornwall's highest cliff, 223 m. The Strangles beach is below it to the north",
    verified: null,
  },
  {
    slug: "beeny-cliff",
    poi: { type: "viewpoint" },
    name: "Beeny Cliff",
    kind: "poi",
    // OSM node 1720920830.
    lat: 50.70345, lon: -4.68122,
    url: "https://literaryrambles.org/walks/beeny-cliff-ramble-thomas-hardy-6772",
    notes: "Where Emma Gifford rode her pony along the cliff edge while Thomas Hardy, restoring the church at St Juliot, courted her in 1870. He came back after her death in 1912 and wrote \"Beeny Cliff\". The waterfall at Pentargon, dropping from a hanging valley into the cove, is just south",
    verified: null,
  },
  {
    slug: "boscastle-harbour",
    poi: { type: "monument" },
    name: "Boscastle Harbour",
    kind: "poi",
    // The National Trust visitor centre, OSM node 975402858.
    lat: 50.69049, lon: -4.69445,
    url: "https://www.nationaltrust.org.uk/visit/cornwall/boscastle/history-of-boscastle",
    notes: "Natural inlet, its harbour walls built by Sir Richard Grenville in 1584. The outer breakwater, damaged by a drifting mine in 1941 and destroyed by a storm in 1947, was rebuilt by the National Trust in 1962. On 16 August 2004 a flash flood, a month's rain in two hours, tore through the village. National Trust visitor centre by the harbour",
    verified: null,
  },
  {
    slug: "museum-of-witchcraft-and-magic",
    name: "Museum of Witchcraft and Magic",
    kind: "poi",
    // OSM node 1289419339.
    lat: 50.69059, lon: -4.69499,
    address: "The Harbour, Boscastle, PL35 0HD",
    url: "https://museumofwitchcraftandmagic.co.uk/visit/",
    notes: "Collection on magic and witchcraft by the harbour. Easter to 31 October, daily, last entry 4.30pm in 2026. Assistance dogs only",
    verified: null,
  },
  {
    slug: "willapark-lookout",
    poi: { type: "viewpoint" },
    name: "Willapark Lookout",
    kind: "poi",
    // Centre of OSM way 113741194.
    lat: 50.68962, lon: -4.70456,
    url: "https://www.nci.org.uk/station/boscastle/",
    notes: "Former coastguard lookout on the headland south of the harbour mouth, leased by the National Coastwatch Institution since 2002 and crewed by volunteers, usually 8am–4pm. Inland of it the Forrabury Stitches, medieval strip fields still farmed in rotation by the National Trust",
    verified: null,
  },
  {
    slug: "rocky-valley-labyrinths",
    poi: { type: "ancient" },
    name: "Rocky Valley labyrinths",
    kind: "poi",
    // OSM node 4726701538.
    lat: 50.67187, lon: -4.72885,
    url: "https://www.britainexpress.com/counties/cornwall/ancient/rock-valley-labyrinths.htm",
    notes: "Two small labyrinths carved into the rock face behind the ruined Trethevy mill. Found in 1948; claimed as Bronze Age, but may be no more than a few centuries old. The mill made cloth and yarn until 1861",
    verified: null,
  },
  {
    slug: "tintagel-castle",
    poi: { type: "ancient" },
    name: "Tintagel Castle",
    kind: "poi",
    // Centre of OSM way 1354036527.
    lat: 50.66870, lon: -4.76111,
    url: "https://www.english-heritage.org.uk/visit/places/tintagel-castle/",
    notes: "English Heritage. Ruins of a 13th-century castle on a headland with far older remains and the Arthurian legend. A footbridge across the gorge, opened in 2019, joins the mainland and island halves. Merlin's Cave is on the beach below. Daily 10am–5pm from 28 March to 24 October 2026, Wed–Sun 10am–4pm in winter; paid entry. Dogs on leads",
    verified: null,
  },
  {
    slug: "st-materiana-tintagel",
    poi: { type: "church" },
    name: "St Materiana's Church",
    kind: "poi",
    // Centre of OSM way 113743827.
    lat: 50.66301, lon: -4.75966,
    url: "https://www.chct.info/histories/tintagel-st-materiana/",
    notes: "Norman church on Glebe Cliff, built between about 1080 and 1150 on an early Christian burial site, with a Norman font and a rood screen of about 1500. Grade I",
    verified: null,
  },
  {
    slug: "tintagel-old-post-office",
    name: "Tintagel Old Post Office",
    kind: "poi",
    // OSM node 13861333561.
    lat: 50.66333, lon: -4.75165,
    address: "Fore Street, Tintagel",
    url: "https://www.nationaltrust.org.uk/visit/cornwall/tintagel-old-post-office",
    notes: "14th-century yeoman's farmhouse with a wavy slate roof and Victorian postal fittings; the National Trust's first building in Cornwall, bought in 1903. Assistance dogs only in the house and garden",
    verified: null,
  },
  {
    slug: "glebe-cliff-quarries",
    poi: { type: "machine" },
    name: "Glebe Cliff slate quarries",
    kind: "poi",
    // OSM node 12803970750, the National Trust map board on Glebe Cliff.
    lat: 50.66288, lon: -4.76057,
    url: "https://en.wikipedia.org/wiki/Tintagel_Slate_Quarries",
    notes: "Slate was cut from these cliffs from at least the 15th century until the last quarry, Long Grass, closed in 1937. Lanterdan, the oldest and largest, on the way to Trebarwith, has a 25 m pinnacle of poor slate the quarrymen left standing",
    verified: null,
  },
  {
    slug: "trebarwith-strand-beach",
    poi: { type: "nature" },
    name: "Trebarwith Strand",
    kind: "poi",
    // OSM node 886478470.
    lat: 50.64473, lon: -4.76036,
    url: "https://www.cornwall-beaches.co.uk/north-cornwall/trebarwith-strand.htm",
    notes: "Almost a mile of sand below the cliffs, uncovered at low tide, with Gull Rock offshore. Dogs allowed all year; not on Cornwall Council's restricted list. RNLI lifeguards late May to late September",
    verified: null,
  },
  {
    slug: "hms-vulture-ii",
    poi: { type: "monument" },
    name: "HMS Vulture II bombing range",
    kind: "poi",
    // Centre of OSM way 164216648, an observation bunker.
    lat: 50.63489, lon: -4.76497,
    url: "https://en.wikipedia.org/wiki/HMS_Vulture_II_(Treligga_Aerodrome)",
    notes: "Fleet Air Arm bombing and gunnery range on the clifftops between Backways Cove and Tregardock, 1939 to 1955, run entirely by the Women's Royal Naval Service. A reinforced hut near Backways Cove and observation bunkers survive",
    verified: null,
  },
  {
    slug: "port-gaverne-cellars",
    poi: { type: "monument" },
    name: "Port Gaverne",
    kind: "poi",
    // OSM node 9676602084, the hamlet.
    lat: 50.59266, lon: -4.82269,
    url: "https://www.cornishrocktors.com/a-short-history-of-port-gaverne/",
    notes: "Cove that grew with the pilchard boom of the early 1800s, when four great fish cellars were built round it, and shipped Delabole slate brought down a purpose-built road. The National Trust owns the beach, two of the cellars and the old slate wharf",
    verified: null,
  },
  {
    slug: "port-isaac-harbour",
    poi: { type: "monument" },
    name: "Port Isaac",
    kind: "poi",
    // OSM node 280487798, the village.
    lat: 50.59388, lon: -4.82999,
    url: "http://www.portisaac-online.co.uk/",
    notes: "Fishing village of narrow lanes round a working harbour, filmed as Portwenn in Doc Martin. Fern Cottage, the doctor's house, is on Roscarrock Hill above the harbour",
    verified: null,
  },
  {
    slug: "doyden-castle",
    poi: { type: "monument" },
    name: "Doyden Castle",
    kind: "poi",
    // Centre of OSM way 164371468.
    lat: 50.58934, lon: -4.87321,
    url: "https://www.nationaltrust.org.uk/holidays/cornwall/doyden-castle",
    notes: "Small Gothic folly on the headland above Port Quin, built about 1830 by the Wadebridge businessman Samuel Symons for drinking and gambling with friends, with a wine cellar below. Now a National Trust holiday let, so seen from outside",
    verified: null,
  },
  {
    slug: "the-rumps",
    poi: { type: "ancient" },
    name: "The Rumps",
    kind: "poi",
    // Centre of OSM way 1078274033, the cliff castle.
    lat: 50.59321, lon: -4.92113,
    url: "https://www.southwestcoastpath.org.uk/walksdb/278/",
    notes: "Iron Age cliff castle of the 2nd century BC on a twin-headed promontory: three ramparts across the neck, still plain to see. On the cliffs between here and Pentire Point, Laurence Binyon wrote \"For the Fallen\" in 1914; a stone plaque of 2001 by the path quotes its fourth verse",
    verified: null,
  },
  {
    slug: "polzeath-beach",
    poi: { type: "nature" },
    name: "Polzeath",
    kind: "poi",
    // OSM node 1595260024, the village.
    lat: 50.57284, lon: -4.91490,
    url: "https://www.cornwall.gov.uk/environment/animal-welfare-and-enforcement/dogs-on-beaches/",
    notes: "Surf beach in Hayle Bay with the village behind it. Dogs banned from Polzeath beach 15 May to 30 September, 10am–6pm. Daymer Bay, further round, has no restriction",
    verified: null,
  },
  {
    slug: "st-enodoc-church",
    poi: { type: "church" },
    name: "St Enodoc Church",
    kind: "poi",
    // Centre of OSM way 113859567.
    lat: 50.55816, lon: -4.92163,
    url: "https://en.wikipedia.org/wiki/St_Enodoc's_Church,_Trebetherick",
    notes: "Small 15th-century church among the dunes and golf course, so buried by drifting sand by the 18th century that services were reached through the roof; dug out and restored in 1864. John Betjeman is buried in the churchyard. Brea Hill, with Bronze Age barrows, is between it and Rock",
    verified: null,
  },
  {
    slug: "national-lobster-hatchery",
    name: "National Lobster Hatchery",
    kind: "poi",
    // Centre of OSM way 162800782.
    lat: 50.53846, lon: -4.93504,
    address: "South Quay, Padstow, PL28 8BL",
    phone: "01841 533877",
    url: "https://nationallobsterhatchery.co.uk/",
    notes: "Charity hatchery on Padstow's South Quay that rears young lobsters for release; a visitor centre shows the process. Open all year; dogs welcome",
    verified: null,
  },
  {
    slug: "stepper-point-daymark",
    poi: { type: "lighthouse" },
    name: "Stepper Point daymark",
    kind: "poi",
    // OSM node 4701442585.
    lat: 50.56809, lon: -4.95258,
    url: "https://www.iwalkcornwall.co.uk/pi/stepper_point_daymark",
    notes: "The \"Pepper Pot\", a 40 ft stone tower built in 1830 as a daytime marker for the mouth of the Camel, over the Doom Bar sandbank that wrecked many ships. Pepper Hole and Butter Hole, collapsed sea caves, are just along the path",
    verified: null,
  },
  {
    slug: "trevone-round-hole",
    poi: { type: "nature" },
    name: "Trevone Round Hole",
    kind: "poi",
    // OSM node 12484416702.
    lat: 50.54823, lon: -4.97942,
    url: "https://www.cornwall-beaches.co.uk/north-coast/trevone-bay.htm",
    notes: "A collapsed sea cave on the cliff above Trevone Bay, about 80 ft deep; a blowhole in a big swell. The ground round it is unstable and people have fallen in: keep back, and keep a dog close",
    verified: null,
  },
  {
    slug: "padstow-lifeboat-station",
    poi: { type: "machine" },
    name: "Padstow Lifeboat Station",
    kind: "poi",
    // Centre of OSM way 461358697.
    lat: 50.54904, lon: -5.02174,
    url: "https://rnli.org/find-my-nearest/lifeboat-stations/padstow-lifeboat-station",
    notes: "The RNLI station at Mother Ivey's Bay; it moved here from Hawker's Cove in 1967 when the estuary silted, and the present boathouse opened in 2006. The old station at Hawker's Cove is passed earlier in the day. Not open to visitors, per the RNLI",
    verified: null,
  },
  {
    slug: "trevose-head-lighthouse",
    poi: { type: "lighthouse" },
    name: "Trevose Head Lighthouse",
    kind: "poi",
    // Centre of OSM way 706928908.
    lat: 50.54922, lon: -5.03521,
    url: "https://www.trinityhouse.co.uk/lighthouses-and-lightvessels/trevose-head",
    notes: "Trinity House light first shown in 1847, 27 m tall. The grounds are open, the tower isn't. Just south, the Round Hole: a sea cave whose roof fell in, a 40 m drop to the sea",
    verified: null,
  },
  {
    slug: "treyarnon-rock-pool",
    poi: { type: "nature" },
    name: "Treyarnon rock pool",
    kind: "poi",
    // OSM node 10782521605, "Tidal Pool".
    lat: 50.52744, lon: -5.02456,
    url: "https://www.wildswimming.co.uk/map/treyarnon-bay-tidal-pool/",
    notes: "Large natural tidal pool in the rocks past the youth hostel, refilled every tide and about 8 ft deep in places; best at low tide. Dogs allowed on Treyarnon beach all year",
    verified: null,
  },
  {
    slug: "park-head",
    poi: { type: "ancient" },
    name: "Park Head",
    kind: "poi",
    // OSM node 4959823424.
    lat: 50.49771, lon: -5.04653,
    url: "https://www.nationaltrust.org.uk/visit/cornwall/carnewas-at-bedruthan/park-head-walk",
    notes: "National Trust headland with an Iron Age cliff castle: two banks and a ditch across its neck. Six Bronze Age burial mounds lie close to the path between Porth Mear and the headland. The view south takes in the stacks of Bedruthan",
    verified: null,
  },
  {
    slug: "bedruthan-steps",
    poi: { type: "nature" },
    name: "Bedruthan Steps",
    kind: "poi",
    // OSM node 3577392550.
    lat: 50.48619, lon: -5.03414,
    url: "https://www.nationaltrust.org.uk/visit/cornwall/carnewas-at-bedruthan/step-closure-at-carnewas-at-bedruthan",
    notes: "Rock stacks and islands along the beach below Carnewas, seen from the clifftop path. The staircase down to the beach has been closed since a rock fall in December 2019, with no timescale for repairs, and there's no other safe way down: the RNLI and National Trust ask people not to look for one",
    verified: null,
  },
  {
    slug: "trevelgue-head",
    poi: { type: "ancient" },
    name: "Trevelgue Head (Porth Island)",
    kind: "poi",
    // Centre of OSM way 63956538, the coastline of Porth Island.
    lat: 50.42696, lon: -5.06378,
    url: "https://historicengland.org.uk/listing/the-list/list-entry/1006712",
    notes: "Iron Age promontory fort on the headland at the north end of Porth beach, with massive ramparts and two early Bronze Age round barrows inside them. A footbridge crosses the gap in the headland. A short detour off the path",
    verified: null,
  },
  {
    slug: "barrowfields",
    poi: { type: "ancient" },
    name: "Barrowfields",
    kind: "poi",
    // OSM node 4335227008.
    lat: 50.41861, lon: -5.07116,
    url: "https://historicengland.org.uk/listing/the-list/list-entry/1004369",
    notes: "Three Bronze Age bowl barrows on the clifftop green in the middle of Newquay Bay, overlooking the stacks at Lusty Glaze: the last of a cemetery of more than fifteen",
    verified: null,
  },
  {
    slug: "huers-hut",
    poi: { type: "monument" },
    name: "Huer's Hut",
    kind: "poi",
    // Centre of OSM way 1173714776.
    lat: 50.42029, lon: -5.08894,
    url: "https://en.wikipedia.org/wiki/Huer%27s_Hut",
    notes: "Whitewashed lookout on the cliff above Newquay harbour, Grade II* listed. From here a huer watched for pilchard shoals and called \"hevva\" to set the boats out, directing them with branches. The building is mid-19th century, on a site used since at least the 14th",
    verified: null,
  },
  {
    slug: "st-pirans-oratory",
    poi: { type: "church" },
    name: "St Piran's Oratory",
    kind: "poi",
    // Centre of OSM way 593477314.
    lat: 50.36504, lon: -5.13914,
    url: "https://stpiran.org/sites/st-pirans-oratory/",
    notes: "The early medieval oratory of Cornwall's patron saint, lost under the dunes of Penhale Sands and uncovered again in 2014, now behind a retaining wall whose gate is usually locked; the roofless interior can be seen over it. A stone cross and the ruins of St Piran's old church are about 350 m away. No signs: a walk inland across the dunes",
    verified: null,
  },
  {
    slug: "cligga-head",
    poi: { type: "machine" },
    name: "Cligga Head",
    kind: "poi",
    // OSM node 2025284475.
    lat: 50.33995, lon: -5.18289,
    url: "https://www.cornishmineimages.co.uk/cligga-head-mine/",
    notes: "91 m cliffs scarred by industry: an explosives works from 1889, run by Nobel from 1893 to 1905, then a wolfram and tin mine that supplied tungsten for armour plate and shells in the Second World War. Keep to the path; there are open shafts",
    verified: null,
  },
  {
    slug: "wheal-coates",
    poi: { type: "machine" },
    name: "Wheal Coates",
    kind: "poi",
    // Centre of OSM way 274838755, the Towanroath Shaft engine house.
    lat: 50.30504, lon: -5.23310,
    url: "https://www.nationaltrust.org.uk/visit/cornwall/wheal-coates/history-of-wheal-coates",
    notes: "National Trust tin mine on the cliffs above Chapel Porth. The Towanroath engine house of 1872, right beside the path, pumped a 600 ft shaft; the Wheal Coates engine houses are up the slope. Mining here is recorded from 1692 and ended in 1914",
    verified: null,
  },
  {
    slug: "portreath-pepperpot",
    poi: { type: "lighthouse" },
    name: "The Pepperpot, Portreath",
    kind: "poi",
    // OSM node 6521121137, "Huer's Hut".
    lat: 50.26400, lon: -5.29186,
    url: "https://commons.wikimedia.org/wiki/Category:Huer%27s_Hut,_Portreath",
    notes: "White conical daymark on Lighthouse Hill above Portreath harbour, built in the 19th century to guide ships into the narrow entrance, with a small light shown at night until 1918. Also called the Huer's Hut: a lookout for pilchard shoals",
    verified: null,
  },
  {
    slug: "hells-mouth-cliffs",
    poi: { type: "nature" },
    name: "Hell's Mouth",
    kind: "poi",
    // OSM node 3678585332.
    lat: 50.23741, lon: -5.36210,
    url: "https://www.nationaltrust.org.uk/visit/cornwall/godrevy",
    notes: "A sheer-sided cove where the North Cliffs drop straight to the sea, a few steps from the B3301 car park. Keep a dog close: the path runs near unfenced edges all along these cliffs",
    verified: null,
  },
  {
    slug: "godrevy-point",
    poi: { type: "lighthouse" },
    name: "Godrevy Point and lighthouse",
    kind: "poi",
    // OSM node 8935747299, Godrevy Point. The lighthouse, way 845047907, is on
    // Godrevy Island offshore.
    lat: 50.24019, lon: -5.39457,
    url: "https://www.nationaltrust.org.uk/visit/cornwall/godrevy",
    notes: "National Trust headland looking out to the Trinity House lighthouse on Godrevy Island. Grey seals haul out on the beach at Mutton Cove, just east of the point, seen from the clifftop; the beach itself is closed to people to protect them. Dogs on a short lead near the edge: off-lead dogs are the commonest cause of disturbance",
    verified: null,
  },
  {
    slug: "harveys-foundry",
    poi: { type: "machine" },
    name: "Harvey's Foundry",
    kind: "poi",
    // Centre of OSM way 390101886.
    lat: 50.18324, lon: -5.42229,
    url: "https://www.harveysfoundrytrust.org.uk/history-heritage/history-of-hayle/",
    notes: "Remains of Harvey & Co's works, founded in 1779, which built Cornish beam engines for mines across the world, including the largest ever made, the Cruquius engine in the Netherlands. It closed in 1903. The Hayle Heritage Centre is in John Harvey House beside it; part of the Cornish Mining World Heritage Site",
    verified: null,
  },
  {
    slug: "rspb-hayle-estuary",
    poi: { type: "nature" },
    name: "RSPB Hayle Estuary (Ryan's Field)",
    kind: "poi",
    // Centre of OSM way 1396197378, Ryan's Field. The Eric Grace Memorial Hide
    // is way 415341818.
    lat: 50.17685, lon: -5.43293,
    url: "https://www.rspb.org.uk/days-out/reserves/hayle-estuary",
    notes: "The most south-westerly estuary in Britain, an RSPB reserve. Ryan's Field is a high-tide roost for waders, watched from the Eric Grace Memorial Hide; best two hours either side of high water. Lelant Saltings can be seen from the station. Dogs are banned from the estuary itself all year",
    verified: null,
  },
  {
    slug: "st-uny-lelant",
    poi: { type: "church" },
    name: "St Uny's Church, Lelant",
    kind: "poi",
    // Centre of OSM way 233521992.
    lat: 50.18868, lon: -5.43621,
    url: "https://en.wikipedia.org/wiki/St_Uny%27s_Church,_Lelant",
    notes: "Granite medieval church among the dunes and golf course above the mouth of the Hayle, first recorded in 1170, with Norman work in the nave arcades. St Michael's Way, the pilgrim route across to St Michael's Mount, starts here",
    verified: null,
  },
  {
    slug: "talland-house",
    poi: { type: "monument" },
    name: "Talland House",
    kind: "poi",
    // Centre of OSM way 760265849.
    lat: 50.20837, lon: -5.47940,
    url: "https://virginiawoolfsociety.org.uk/talland-house-plaque/",
    notes: "The Stephen family's holiday house above Porthminster, where Virginia Woolf spent her childhood summers from 1882 to 1894, the setting she drew on for To the Lighthouse, with Godrevy across the bay. A private house now: seen from the road",
    verified: null,
  },
  {
    slug: "st-senara-zennor",
    poi: { type: "church" },
    name: "St Senara's Church, Zennor",
    kind: "poi",
    // Centre of OSM way 233500074.
    lat: 50.19175, lon: -5.56743,
    url: "https://en.wikipedia.org/wiki/St_Senara%27s_Church,_Zennor",
    notes: "Partly Norman church in Zennor with the Mermaid Chair, made from 15th-century bench ends carved with a mermaid holding a mirror. The legend, first written down in 1873, has her luring a chorister down to Pendour Cove, below the path",
    verified: null,
  },
  {
    slug: "gurnards-head",
    poi: { type: "ancient" },
    name: "Gurnard's Head",
    kind: "poi",
    // OSM node 692878956.
    lat: 50.19267, lon: -5.59909,
    url: "https://www.penwithlandscape.org.uk/trails-and-ancient-sites/trail-guide-bosigran-bosporthennis-and-carn-galva/",
    notes: "Narrow headland off the path with the ramparts of an Iron Age cliff castle across its neck. A spur out and back",
    verified: null,
  },
  {
    slug: "carn-galver-mine",
    poi: { type: "machine" },
    name: "Carn Galver engine houses and Bosigran",
    kind: "poi",
    // OSM node 641302605, Carn Galver Mine.
    lat: 50.17174, lon: -5.61290,
    url: "https://www.nationaltrust.org.uk/visit/cornwall/coast-beaches/carn-galva-and-bosigran",
    notes: "Two National Trust engine houses of the old Morvah and Zennor United Mine beside the B3306, above the Porthmoina valley. On the cliff below, Bosigran Castle, an Iron Age cliff castle behind a stone wall 120 m long, and the granite climbing cliffs of Bosigran and Commando Ridge",
    verified: null,
  },
  {
    slug: "pendeen-lighthouse",
    poi: { type: "lighthouse" },
    name: "Pendeen Lighthouse",
    kind: "poi",
    // Centre of OSM way 390207434.
    lat: 50.16498, lon: -5.67156,
    url: "https://www.trinityhouse.co.uk/lighthouses-and-lightvessels/pendeen-lighthouse",
    notes: "Trinity House lighthouse on Pendeen Watch, first lit on 26 September 1900 to cover the blind stretch of cliffs between Trevose Head and the Longships, with a 17 m tower, keepers' cottages and a foghorn house. Manned until 1995. Walkers can go round the outside",
    verified: null,
  },
  {
    slug: "geevor-tin-mine",
    poi: { type: "machine" },
    name: "Geevor Tin Mine",
    kind: "poi",
    // OSM node 1924136691.
    lat: 50.15195, lon: -5.67598,
    url: "https://geevor.com/visit-us/opening-times-and-prices/",
    notes: "Mining museum in the buildings of the last working mine on this coast: the tin floors, the Hard Rock museum, and an underground tour of the Wheal Mexico workings, 10am – 4pm. Open Sunday to Friday 9am – 5pm, closed Saturdays; a charge. Dogs welcome everywhere except underground, with water bowls. The Count House Café is on site. Part of the Cornish Mining World Heritage Site",
    verified: null,
  },
  {
    slug: "levant-mine",
    poi: { type: "machine" },
    name: "Levant Mine and Beam Engine",
    kind: "poi",
    // OSM node 690269381.
    lat: 50.15211, lon: -5.68541,
    url: "https://www.nationaltrust.org.uk/visit/cornwall/levant-mine-and-beam-engine",
    notes: "National Trust mine on the cliff edge with its 1840 beam engine, restored to steam. Visits by tour only, booking advised: March to October Sunday–Thursday 10am – 4.30pm, November to February Mondays and Wednesdays 10.30am – 3pm",
    verified: null,
  },
  {
    slug: "botallack-crowns",
    poi: { type: "machine" },
    name: "Botallack Crowns engine houses",
    kind: "poi",
    // OSM node 690271327, Crowns Mine.
    lat: 50.14303, lon: -5.69314,
    url: "https://www.nationaltrust.org.uk/visit/cornwall/botallack",
    notes: "Two engine houses built on the rocks at the foot of the cliff, where the Botallack workings ran out under the sea. National Trust land, with more mine buildings, calciner remains and the Count House along the path",
    verified: null,
  },
  {
    slug: "cape-cornwall-headland",
    poi: { type: "viewpoint" },
    name: "Cape Cornwall",
    kind: "poi",
    // OSM node 2488777281, the chimney on the summit.
    lat: 50.12723, lon: -5.70878,
    url: "https://www.nationaltrust.org.uk/visit/cornwall/cape-cornwall",
    notes: "Headland crowned by the chimney of Cape Cornwall Mine, kept as a daymark. Bought by Heinz in 1987 and given to the National Trust; the chimney carries the plaque. Dogs on leads: steep ground and old shafts. Dogs are banned from Priest's Cove beach and slipway, below, from Easter Sunday to 30 September",
    verified: null,
  },
  {
    slug: "ballowall-barrow",
    poi: { type: "ancient" },
    name: "Ballowall Barrow",
    kind: "poi",
    // Centre of OSM way 390426632.
    lat: 50.12228, lon: -5.70145,
    url: "https://www.english-heritage.org.uk/visit/places/ballowall-barrow/",
    notes: "Bronze Age chambered cairn on the clifftop at Carn Gloose, among old mine shafts: English Heritage, managed by the National Trust. Stone cists inside held cremations",
    verified: null,
  },
  {
    slug: "maen-castle",
    poi: { type: "ancient" },
    name: "Maen Castle",
    kind: "poi",
    // OSM node 2355768818.
    lat: 50.07272, lon: -5.70804,
    notes: "Cliff castle on Mayon Cliff, beside the path between Sennen and Land's End",
    verified: null,
  },
  {
    slug: "lands-end-point",
    poi: { type: "viewpoint" },
    name: "Land's End",
    kind: "poi",
    // OSM node 3001298524.
    lat: 50.06549, lon: -5.71485,
    notes: "The westernmost point of mainland England, looking out to the Longships lighthouse. A commercial visitor site with cafés, exhibitions and the hotel; the path runs through it",
    verified: null,
  },
  {
    slug: "minack-theatre",
    poi: { type: "monument" },
    name: "Minack Theatre",
    kind: "poi",
    // Centre of OSM way 841707473.
    lat: 50.04098, lon: -5.65132,
    url: "https://minack.com/visit/faqs/",
    notes: "Open-air theatre built into the cliff above Porthcurno by Rowena Cade, with the Rowena Cade exhibition and a café. Daytime visits from 10am, pre-booked; closed Mondays and Tuesdays November to February, and it can close early before a performance. Dogs on short leads welcome during visiting hours, not at performances",
    verified: null,
  },
  {
    slug: "porthcurno-telegraph-museum",
    poi: { type: "machine" },
    name: "Porthcurno Telegraph Museum",
    kind: "poi",
    // Centre of OSM way 130154035.
    lat: 50.04680, lon: -5.65500,
    notes: "Museum in the valley behind Porthcurno beach, where the undersea telegraph cables to the Empire came ashore, with wartime tunnels. A charge; hours not confirmed",
    verified: null,
  },
  {
    slug: "logan-rock",
    poi: { type: "ancient" },
    name: "Treryn Dinas and the Logan Rock",
    kind: "poi",
    // OSM node 2135047368, Treryn Dinas.
    lat: 50.04073, lon: -5.63685,
    url: "https://en.wikipedia.org/wiki/Treryn_Dinas",
    notes: "National Trust headland with the banks and ditches of an Iron Age cliff castle, and at its tip the Logan Rock, a huge naturally balanced boulder. In 1824 a naval lieutenant, Hugh Goldsmith, levered it off its perch; the Admiralty made him put it back that November. A scramble off the path",
    verified: null,
  },
  {
    slug: "tater-du-lighthouse",
    poi: { type: "lighthouse" },
    name: "Tater Du Lighthouse",
    kind: "poi",
    // Centre of OSM way 843945354.
    lat: 50.05235, lon: -5.57741,
    notes: "Small lighthouse on the rocks below the path between St Loy and Lamorna, seen from above",
    verified: null,
  },
  {
    slug: "penlee-point-lifeboat-station",
    poi: { type: "monument" },
    name: "Penlee Point old lifeboat station",
    kind: "poi",
    // Centre of OSM way 112518592, "Penlee Lifeboat Station".
    lat: 50.08924, lon: -5.53401,
    url: "https://historicengland.org.uk/whats-new/news/former-penlee-point-lifeboat-station-cornwall-listed/",
    notes: "The boathouse, built 1911–13, from which the lifeboat Solomon Browne launched on 19 December 1981 to the Union Star. Both were lost with all hands, sixteen people including the eight lifeboat crew. Closed in 1983 and kept by local volunteers with a memorial garden. Mousehole turns off its lights each 19 December",
    verified: null,
  },
  {
    slug: "jubilee-pool",
    poi: { type: "machine" },
    name: "Jubilee Pool",
    kind: "poi",
    // Centre of OSM way 236573354.
    lat: 50.11487, lon: -5.53158,
    url: "https://jubileepool.co.uk/",
    notes: "Art deco seawater lido of the 1930s on the rocks at Battery Point, with a geothermally heated pool at 28–30°C. 2026 season 31 March – 1 November, Tuesday–Sunday 10am – 5pm in term time, daily in the summer holidays; café 10am – 4pm. Geothermal sessions of 55 minutes on the hour",
    verified: null,
  },
  {
    slug: "st-michaels-mount",
    poi: { type: "monument" },
    name: "St Michael's Mount",
    kind: "poi",
    // Centre of OSM way 55079805, the castle.
    lat: 50.11647, lon: -5.47844,
    url: "https://stmichaelsmount.co.uk/getting-here/walking/",
    notes: "Tidal island with a castle off Marazion, reached by the cobbled causeway for about two hours either side of low water, or by boat. Castle and gardens Sunday–Friday, closed Saturdays, tickets pre-booked April–October. Dogs welcome on the causeway and in the harbour, not in the castle or gardens",
    verified: null,
  },
  {
    slug: "prussia-cove-carters",
    poi: { type: "monument" },
    name: "Prussia Cove and Bessy's Cove",
    kind: "poi",
    // OSM place node 29164647, Prussia Cove.
    lat: 50.10151, lon: -5.41828,
    url: "https://en.wikipedia.org/wiki/Carters_of_Prussia_Cove",
    notes: "Tiny coves below Cudden Point used by the Carter brothers, the most successful smugglers of the Penzance district from about 1777 to 1807; John Carter was known as the King of Prussia. Old cart ruts are cut into the rocks between Bessy's Cove and Prussia Cove. The cottages and lane are a private estate",
    verified: null,
  },
  {
    slug: "wheal-prosper",
    poi: { type: "machine" },
    name: "Wheal Prosper",
    kind: "poi",
    // Centre of OSM way 390101846.
    lat: 50.09439, lon: -5.36578,
    url: "https://en.wikipedia.org/wiki/Wheal_Prosper",
    notes: "Clifftop pumping engine house at Rinsey Head, from a mine that worked only from about 1860 to 1866; the National Trust has owned and kept it since 1969",
    verified: null,
  },
  {
    slug: "wheal-trewavas",
    poi: { type: "machine" },
    name: "Wheal Trewavas",
    kind: "poi",
    // Centre of OSM way 390101842, the New Shaft engine house.
    lat: 50.09077, lon: -5.35583,
    url: "https://en.wikipedia.org/wiki/Wheal_Trewavas",
    notes: "Two engine houses of a copper mine worked from about 1834 to 1846, on the cliff edge just east of Trewavas Head. Part of the Cornish Mining World Heritage Site",
    verified: null,
  },
  {
    slug: "loe-bar",
    poi: { type: "nature" },
    name: "Loe Bar and the Anson memorial",
    kind: "poi",
    // OSM way 25382241, Loe Bar beach; the HMS Anson monument is OSM node
    // 667302047.
    lat: 50.06776, lon: -5.29153,
    url: "https://nmmc.co.uk/2022/02/a-shipwreck-rockets-and-a-change-in-the-law/",
    notes: "Shingle bar dividing Loe Pool, Cornwall's largest natural lake, from the sea. The frigate HMS Anson was wrecked here on 29 December 1807 with the loss of about 100 lives; watching it, Henry Trengrouse of Helston went on to invent the rocket line apparatus. A memorial stands at the Gunwalloe end. Never swim: steep shelving shingle and fierce undertow even on calm days",
    verified: null,
  },
  {
    slug: "marconi-poldhu",
    poi: { type: "monument" },
    name: "Marconi Monument and Centre, Poldhu",
    kind: "poi",
    // OSM node 2792124370, the monument; the Marconi Centre is way 417668127.
    lat: 50.02890, lon: -5.26420,
    url: "https://marconi-centre-poldhu.org.uk/about/history/",
    notes: "On the cliff above Poldhu Cove, the site of the wireless station from which the first transatlantic radio signal, the Morse letter S, was sent on 12 December 1901, heard by Marconi in Newfoundland. The Marconi Centre, opened in 2001, has the story; opening times on its site",
    verified: null,
  },
  {
    slug: "kynance-cove-view",
    poi: { type: "nature" },
    name: "Kynance Cove",
    kind: "poi",
    // OSM node 1547578206, viewpoint.
    lat: 49.97453, lon: -5.22781,
    url: "https://www.kynancecovecafe.co.uk/",
    notes: "National Trust cove of white sand and serpentine stacks, reached by a steep path down from the car park. Dogs are banned from the beach 1 July – 31 August, 10am – 6pm, and welcome on the clifftops all year",
    verified: null,
  },
  {
    slug: "lizard-point-lighthouse",
    poi: { type: "lighthouse" },
    name: "Lizard Point and lighthouse",
    kind: "poi",
    // OSM node 1977845194, Lizard Point; the lighthouse is node 1546248934 and
    // its heritage centre node 798548155.
    lat: 49.95888, lon: -5.20638,
    url: "https://www.trinityhouse.co.uk/lighthouses-and-lightvessels/lizard-lighthouse",
    notes: "The most southerly point of mainland Britain, with cafés above Polpeor Cove. The Lizard lighthouse, just east, has a heritage centre",
    verified: null,
  },
  {
    slug: "lizard-wireless-station",
    poi: { type: "machine" },
    name: "Lizard Wireless Station",
    kind: "poi",
    // OSM node 502248852.
    lat: 49.96350, lon: -5.19185,
    url: "https://lizardwireless.org/opening-times/",
    notes: "Clifftop hut at Bass Point built by Marconi in 1900, a few metres from the path, now a volunteer-run National Trust station where you can try Morse code. Monday–Thursday noon – 3pm, April to the start of October, depending on weather and volunteers; free",
    verified: null,
  },
  {
    slug: "devils-frying-pan",
    poi: { type: "nature" },
    name: "Devil's Frying Pan",
    kind: "poi",
    // Centre of OSM way 815984631.
    lat: 49.98466, lon: -5.18020,
    url: "https://www.iwalkcornwall.co.uk/pi/devils_frying_pan",
    notes: "A sea cave whose roof fell in in 1868, leaving a boulder-filled hole with the old entrance as an arch, just south of Cadgwith. In rough weather the sea seems to boil inside it. Unfenced: keep a dog close",
    verified: null,
  },
  {
    slug: "lowland-point",
    poi: { type: "ancient" },
    name: "Lowland Point",
    kind: "poi",
    // Centre of OSM way 1107336560, the scheduled monument; the saltworks ruins
    // are OSM node 10132220280.
    lat: 50.03487, lon: -5.07734,
    url: "https://www.openstreetmap.org/way/1107336560",
    notes: "Low headland below the cliffs south of Porthoustock, a scheduled ancient monument, with the ruins of saltworks by the path",
    verified: null,
  },
  {
    slug: "st-anthony-in-meneage-church",
    poi: { type: "church" },
    name: "St Anthony-in-Meneage church",
    kind: "poi",
    // Centre of OSM way 158587049.
    lat: 50.08962, lon: -5.10097,
    notes: "Small church on the shore of Gillan Creek, where the path crosses by stepping stones at low tide, about three hours either side of low water, or by Sailaway's on-demand ferry April to October. Otherwise it's an inland detour by road through Manaccan",
    verified: null,
  },
  // Section 29.
  {
    slug: "trebah-garden",
    poi: { type: "nature" },
    name: "Trebah Garden",
    kind: "poi",
    // Centre of OSM way 49641995.
    lat: 50.10329, lon: -5.12238,
    url: "https://www.trebahgarden.co.uk/",
    notes: "Subtropical valley garden running down to its own beach on the Helford, which the path crosses. Entry charged; opening times and dog policy on its site",
    verified: null,
  },
  {
    slug: "glendurgan-garden",
    poi: { type: "nature" },
    name: "Glendurgan Garden",
    kind: "poi",
    // Centre of OSM way 49641988.
    lat: 50.10724, lon: -5.11704,
    url: "https://www.nationaltrust.org.uk/visit/cornwall/glendurgan-garden",
    notes: "National Trust valley garden above Durgan, with a laurel maze. Entry charged; opening times on its site",
    verified: null,
  },
  {
    // OSM node 14089881400.
    slug: "rosemullion-head",
    poi: { type: "nature" },
    name: "Rosemullion Head",
    kind: "poi",
    lat: 50.11012, lon: -5.08254,
    notes: "Headland between the Helford and Maenporth, looking across Falmouth Bay",
    verified: null,
  },
  {
    slug: "pendennis-castle",
    poi: { type: "monument" },
    name: "Pendennis Castle",
    kind: "poi",
    // Centre of OSM way 142798233; the museum entrance is OSM node 865125078.
    // Little Dennis, the blockhouse below, is way 142799732.
    lat: 50.14687, lon: -5.04721,
    url: "https://www.openstreetmap.org/way/142798233",
    notes: "Henry VIII's castle on Pendennis Point, facing St Mawes Castle across the mouth of the Fal, run by English Heritage. Entry charged. The path goes round the point below it, past the Little Dennis blockhouse",
    verified: null,
  },
  // Section 30.
  {
    slug: "church-of-st-anthony-roseland",
    poi: { type: "church" },
    name: "Church of St Anthony, Roseland",
    kind: "poi",
    // Centre of OSM way 245495024.
    lat: 50.14948, lon: -5.00410,
    url: "https://www.visitchurches.org.uk/visit/our-churches/st-anthonys-church-roseland-cornwall",
    notes: "Grade II* listed church by the path above Place, cared for by the Churches Conservation Trust",
    verified: null,
  },
  {
    slug: "st-anthony-lighthouse",
    poi: { type: "lighthouse" },
    name: "St Anthony Lighthouse",
    kind: "poi",
    // Centre of OSM way 673396687.
    lat: 50.14116, lon: -5.01606,
    url: "https://www.openstreetmap.org/way/673396687",
    notes: "White lighthouse below St Anthony Head, marking the entrance to Falmouth harbour",
    verified: null,
  },
  // Section 31.
  {
    slug: "caerhays-castle",
    poi: { type: "monument" },
    name: "Caerhays Castle",
    kind: "poi",
    // Centre of OSM way 85475632.
    lat: 50.23957, lon: -4.84678,
    url: "https://www.caerhays.co.uk/",
    notes: "Castellated house in its garden above Porthluney Cove. House and garden opening on its site",
    verified: null,
  },
  {
    slug: "dodman-point",
    poi: { type: "viewpoint" },
    name: "Dodman Point",
    kind: "poi",
    // OSM node 3662862740, the cross; the cape is OSM node 8477022500.
    lat: 50.21993, lon: -4.80316,
    url: "https://www.openstreetmap.org/node/3662862740",
    notes: "The highest headland on this stretch, with a granite cross at the top and the National Trust's Watch House nearby",
    verified: null,
  },
  // Section 32.
  {
    // OSM node 12685659294.
    slug: "black-head",
    poi: { type: "nature" },
    name: "Black Head",
    kind: "poi",
    lat: 50.29917, lon: -4.75425,
    notes: "Headland between Pentewan and Porthpean, reached by a short spur off the path",
    verified: null,
  },
  {
    slug: "ropehaven-cliffs",
    poi: { type: "nature" },
    name: "Ropehaven Cliffs Nature Reserve",
    kind: "poi",
    // Centre of OSM way 285740325.
    lat: 50.30906, lon: -4.76060,
    url: "https://www.openstreetmap.org/way/285740325",
    notes: "Cornwall Wildlife Trust woodland and cliff reserve north of Black Head",
    verified: null,
  },
  {
    slug: "charlestown-harbour",
    poi: { type: "monument" },
    name: "Charlestown harbour",
    kind: "poi",
    // OSM node 311747096, the village.
    lat: 50.33299, lon: -4.75776,
    url: "https://www.openstreetmap.org/node/311747096",
    notes: "Georgian harbour built for china clay and copper, part of the Cornwall and West Devon Mining Landscape World Heritage Site; square-riggers are often moored in the dock",
    verified: null,
  },
  // Section 33.
  {
    slug: "gribbin-tower",
    poi: { type: "monument" },
    name: "Gribbin Tower",
    kind: "poi",
    // Centre of OSM way 29285905.
    lat: 50.31697, lon: -4.67313,
    url: "https://www.wikidata.org/wiki/Q26505543",
    notes: "Tall daymark on Gribbin Head, built as a landmark for shipping; the path passes it",
    verified: null,
  },
  {
    slug: "st-catherines-castle",
    poi: { type: "ancient" },
    name: "St Catherine's Castle",
    kind: "poi",
    // Centre of OSM way 245872264.
    lat: 50.32828, lon: -4.64452,
    url: "https://www.english-heritage.org.uk/visit/places/st-catherines-castle/",
    notes: "Ruined fort on the point above Readymoney Cove, at the mouth of the Fowey; English Heritage",
    verified: null,
  },
  // Section 34.
  {
    slug: "lammana-chapel",
    poi: { type: "ancient" },
    name: "Lammana Chapel",
    kind: "poi",
    // Centre of OSM way 570706357; the ruin of the Monks' House is way 570706368.
    lat: 50.34348, lon: -4.46033,
    url: "https://www.openstreetmap.org/way/570706357",
    notes: "Fenced archaeological site of a chapel on the mainland facing Looe Island, with the ruins of the Monks' House below it by the path",
    verified: null,
  },
  // Section 35.
  {
    slug: "st-michaels-chapel-rame",
    poi: { type: "church" },
    name: "St Michael's Chapel, Rame Head",
    kind: "poi",
    // Centre of OSM way 163758789.
    lat: 50.31370, lon: -4.22312,
    url: "https://www.wikidata.org/wiki/Q17532059",
    notes: "Small chapel out on Rame Head, a short climb off the path",
    verified: null,
  },
  {
    slug: "queen-adelaides-chapel",
    poi: { type: "monument" },
    name: "Queen Adelaide's Chapel",
    kind: "poi",
    // OSM node 3048536319; also called Queen Adelaide's Grotto.
    lat: 50.31853, lon: -4.19020,
    url: "https://www.wikidata.org/wiki/Q26597078",
    notes: "Small chapel, also called Queen Adelaide's Grotto, on the cliff at Penlee Point",
    verified: null,
  },
  {
    slug: "mount-edgcumbe-house",
    poi: { type: "monument" },
    name: "Mount Edgcumbe House and Country Park",
    kind: "poi",
    // Centre of OSM way 225476573.
    lat: 50.35429, lon: -4.17591,
    url: "https://www.mountedgcumbe.gov.uk/",
    notes: "Grade II listed house in the country park the path crosses to Cremyll, with formal gardens and the Orangery café near the ferry. House opening times on its site",
    verified: null,
  },
  // Section 36.
  {
    slug: "smeatons-tower",
    poi: { type: "lighthouse" },
    name: "Smeaton's Tower",
    kind: "poi",
    // Centre of OSM way 316691443.
    lat: 50.36435, lon: -4.14189,
    url: "https://www.openstreetmap.org/way/316691443",
    notes: "Smeaton's Eddystone lighthouse, rebuilt on Plymouth Hoe, which the path passes",
    verified: null,
  },
  {
    slug: "mayflower-steps",
    poi: { type: "monument" },
    name: "Mayflower Steps",
    kind: "poi",
    // OSM node 6473965285.
    lat: 50.36614, lon: -4.13378,
    url: "https://www.openstreetmap.org/node/6473965285",
    notes: "Memorial portico on the Barbican quay marking where the Mayflower is said to have sailed from in 1620",
    verified: null,
  },
  {
    slug: "mount-batten-tower",
    poi: { type: "monument" },
    name: "Mount Batten Tower",
    kind: "poi",
    // OSM node 13092456752, the information board at the tower.
    lat: 50.35942, lon: -4.13027,
    notes: "Round artillery tower at the end of the Mount Batten peninsula, above the pier",
    verified: null,
  },
  {
    slug: "st-werburgh-wembury",
    poi: { type: "church" },
    name: "St Werburgh's church, Wembury",
    kind: "poi",
    // Centre of OSM way 137335559.
    lat: 50.31777, lon: -4.08242,
    notes: "Church on the cliff above Wembury beach, beside the path, with the Mewstone offshore",
    verified: null,
  },
  // Section 37.
  {
    slug: "st-peter-the-poor-fisherman",
    poi: { type: "church" },
    name: "St Peter the Poor Fisherman",
    kind: "poi",
    // Centre of OSM way 663818939.
    lat: 50.30039, lon: -4.01780,
    notes: "Ruined church above Stoke Beach, kept as a shell, on the path at Stoke Point",
    verified: null,
  },
  {
    slug: "revelstoke-watch-tower",
    poi: { type: "monument" },
    name: "Watch Tower, Revelstoke Drive",
    kind: "poi",
    // Centre of OSM way 963576448.
    lat: 50.29555, lon: -4.04445,
    notes: "Ruined tower on the cliff where the path follows the old carriage drive east of Noss Mayo",
    verified: null,
  },
  {
    slug: "burgh-island",
    poi: { type: "nature" },
    name: "Burgh Island",
    kind: "poi",
    // Centre of OSM way 364192804.
    lat: 50.27945, lon: -3.89978,
    notes: "Tidal island off Bigbury-on-Sea with the Pilchard Inn and the art deco hotel: you walk over the sand at low water, and the sea tractor runs when the tide is in",
    verified: null,
  },
  // Section 38.
  {
    slug: "bolt-tail-fort",
    poi: { type: "ancient" },
    name: "Bolt Tail promontory fort",
    kind: "poi",
    // Centre of OSM way 165088738.
    lat: 50.24143, lon: -3.86593,
    notes: "Iron Age rampart across the neck of Bolt Tail, above Hope Cove, which the path crosses",
    verified: null,
  },
  {
    slug: "overbecks",
    poi: { type: "nature" },
    name: "Overbeck's",
    kind: "poi",
    // Centre of OSM way 143885053.
    lat: 50.22279, lon: -3.78430,
    url: "https://www.nationaltrust.org.uk/visit/devon/overbecks",
    notes: "National Trust house and subtropical garden above South Sands, looking down the Salcombe estuary. Opening times on its site",
    verified: null,
  },
  // Section 39.
  {
    slug: "start-point-lighthouse",
    poi: { type: "lighthouse" },
    name: "Start Point lighthouse",
    kind: "poi",
    // OSM node 6518689372.
    lat: 50.22248, lon: -3.64229,
    notes: "Lighthouse at the end of the long spine of Start Point, reached by the lane from the car park; the path stays above it",
    verified: null,
  },
  {
    slug: "hallsands-ruins",
    poi: { type: "ancient" },
    name: "Old Hallsands",
    kind: "poi",
    // OSM node 2875099760, the viewing platform above the ruins.
    lat: 50.23483, lon: -3.65894,
    notes: "The remains of the fishing village lost to the sea in 1917, seen from a viewing platform on the path",
    verified: null,
  },
  // Section 40.
  {
    slug: "slapton-sands-tank",
    poi: { type: "monument" },
    name: "Sherman tank, Torcross",
    kind: "poi",
    // OSM node 716014166.
    lat: 50.26868, lon: -3.65246,
    notes: "A Sherman tank raised from the bay in 1984, kept at Torcross as a memorial to the American servicemen killed in the 1944 Exercise Tiger landings on Slapton Sands",
    verified: null,
  },
  {
    slug: "dartmouth-castle",
    poi: { type: "ancient" },
    name: "Dartmouth Castle",
    kind: "poi",
    // Centre of OSM way 293598135.
    lat: 50.34180, lon: -3.56572,
    url: "https://www.english-heritage.org.uk/visit/places/dartmouth-castle/",
    notes: "Castle at the mouth of the Dart, built to close the river with a chain to Kingswear Castle opposite; English Heritage, with a tea room beside it",
    verified: null,
  },
  {
    slug: "gallants-bower",
    poi: { type: "ancient" },
    name: "Gallants Bower",
    kind: "poi",
    // Centre of OSM way 331560714.
    lat: 50.34109, lon: -3.56952,
    notes: "Earthwork of a Civil War fort on the wooded hill above Dartmouth Castle, National Trust, with a view over the river mouth",
    verified: null,
  },
];
