// Places to stay. Part of the shared location model (see src/_data/locations.js):
// the common fields — slug, name, kind, lat/lon, address, contact, notes,
// verified — are the same for every kind of location, and everything specific
// to somewhere you sleep sits in `stay`.
//
//   stay.dogs             true | false | null   null = not confirmed. Never guess.
//                         A hotel is only recorded if it's true.
//   stay.season           "all-year" | { from: "MM-DD", to: "MM-DD" } | null
//   stay.price_per_night  number (GBP) | null
//   stay.hookup           true | false | null
//   verified              "YYYY-MM-DD" | null   when checked against the owner's
//                                               own website
//   maps_url              optional override for the generated directions link
//
// Free text for colour and caveats only: stay.dogs_note, stay.price_note, notes.
// Each fact lives in one place — don't restate a field inside `notes`.
export default [
  {
    slug: "burrowhayes-farm",
    name: "Burrowhayes Farm",
    kind: "stay",
    lat: 51.20424, lon: -3.57803,
    address: "West Luccombe, Porlock, TA24 8HT",
    phone: "01643 862463",
    url: "https://burrowhayes.co.uk/",
    notes: "National Trust land, a mile east of Porlock",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      dogs: true,
      dogs_note: "Strict control; exercised off site",
      season: null,
      price_per_night: null,
      hookup: true,
    },
  },
  {
    slug: "porlock-holiday-park",
    name: "Porlock Holiday Park",
    kind: "stay",
    lat: 51.21043, lon: -3.59742,
    address: "High Bank, Porlock, TA24 8ND",
    phone: "07348 751554",
    email: "info@porlockholidaypark.co.uk",
    url: "https://www.porlockcaravanpark.co.uk/",
    notes: "Formerly Porlock Caravan Park. Directories still list the old name and a 15 Mar–31 Oct season",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      dogs: true,
      season: null,
      price_per_night: null,
    },
  },
  {
    slug: "lynmouth-holiday-retreat",
    name: "Lynmouth Holiday Retreat",
    kind: "stay",
    lat: 51.21877, lon: -3.82778,
    address: "Manor Farm, Barbrook, Lynton, EX35 6LD",
    phone: "01598 753349",
    url: "https://coastandcountryparks.co.uk/our-parks/lynmouth-holiday-retreat-north-devon/",
    notes: "Maximum unit length 9 m. The coast path runs past it",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      dogs: true,
      dogs_note: "Up to two; short lead, not left unattended. Dog-walking meadow on site",
      season: null,
      price_per_night: null,
      hookup: true,
    },
  },
  {
    slug: "sunny-lyn",
    name: "Sunny Lyn Holiday Park",
    kind: "stay",
    lat: 51.22075, lon: -3.83650,
    address: "Lynbridge Road, Lynton, EX35 6NS",
    phone: "01598 753384",
    email: "info@sunnylyn.co.uk",
    url: "https://www.sunnylyn.co.uk/",
    notes: "Nine electric touring pitches, by the West Lyn river. Lodges run year-round; the touring season isn't stated",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      dogs: true,
      season: null,
      price_per_night: null,
      hookup: true,
    },
  },
  {
    slug: "blue-ball-inn",
    name: "Blue Ball Inn",
    kind: "stay",
    food: { type: "pub" },
    lat: 51.23307, lon: -3.79547,
    address: "Countisbury, Lynmouth, EX35 6NE",
    phone: "01598 741263",
    email: "info@blueballinn.com",
    url: "https://www.blueballinn.com/",
    notes: "Brit Stops member — overnight motorhome parking. Also fourteen en-suite rooms. Stands on the section 2 route at Countisbury",
    verified: "2026-09-13",
    stay: {
      type: "britstop",
      dogs: true,
      dogs_note: "£15 per dog per night; welcome throughout except the main restaurant",
      season: "all-year",
      price_per_night: null,
    },
  },
  {
    slug: "porlock-weir-car-park",
    name: "Porlock Weir car park",
    kind: "stay",
    lat: 51.21878, lon: -3.62691,
    address: "B3225, Porlock Weir, TA24",
    url: "https://park4night.com/en/place/87299",
    // The generated lat/lon link labelled itself "Locanda on the Weir" — the
    // coordinate is right (2 m from the car park in OSM) but Google snaps the
    // label to the nearest named business, and there are six within 60 m. A
    // Plus Code resolves to the point itself.
    maps_url: "https://www.google.com/maps/dir/?api=1&destination=9C3R699F%2BG6",
    notes: "Public car park with public toilets; bars and restaurants alongside. Reported quiet overnight",
    // A park4night listing is user-reported, not the operator.
    verified: null,
    stay: {
      type: "park4night",
      dogs: true,
      season: null,
      price_per_night: 15,
      price_note: "per 24 hours, ticket machine or QR code",
    },
  },
  {
    slug: "hoburne-blue-anchor",
    name: "Hoburne Blue Anchor",
    kind: "stay",
    lat: 51.18204, lon: -3.39684,
    address: "Blue Anchor, Minehead, TA24 6JT",
    phone: "01643 821360",
    notes: "Around 100 touring pitches, but four miles east of Minehead — a drive, not a walk",
    verified: null,
    stay: {
      type: "campsite",
      dogs: null,
      season: null,
      price_per_night: null,
    },
  },
  {
    slug: "bottom-ship",
    name: "The Bottom Ship",
    kind: "stay",
    food: { type: "pub" },
    lat: 51.21829, lon: -3.62726,
    address: "5 Anchor Road, Porlock Weir, TA24 8PB",
    phone: "01643 863288",
    notes: "Rooms above the pub, on the path at Porlock Weir",
    verified: null,
    stay: {
      type: "inn",
      dogs: true,
      season: null,
      price_per_night: null,
    },
  },
  {
    slug: "myrtle-cottage",
    name: "Myrtle Cottage",
    kind: "stay",
    lat: 51.20939, lon: -3.59702,
    address: "High Street, Porlock, TA24 8PU",
    url: "https://myrtleporlock.co.uk/",
    notes: "Walkers welcome, drying facilities. Reported open all year",
    verified: null,
    stay: {
      type: "bnb",
      dogs: true,
      season: null,
      price_per_night: null,
    },
  },
  {
    slug: "kenella-house",
    name: "Kenella House",
    kind: "stay",
    lat: 51.20557, lon: -3.47142,
    address: "7 Tregonwell Road, Minehead, TA24 5DT",
    url: "https://kenellahouse.co.uk/",
    notes: "About 500 m from the path",
    verified: null,
    stay: {
      type: "bnb",
      dogs: null,
      season: null,
      price_per_night: null,
    },
  },
  {
    slug: "caffyns-farm",
    name: "Caffyns Farm",
    kind: "stay",
    lat: 51.21769, lon: -3.87474,
    address: "Croscombe Lane, Lynton, EX35 6JW",
    phone: "01598 753967",
    email: "stay@exmoorcoastholidays.co.uk",
    url: "https://www.exmoorcoastholidays.co.uk/camping",
    notes: "Planning limits campervans to 5.5 m long and 2.2 m high, which rules out most high-tops. No bookings taken. Water and chemical disposal in each field; barn café and farm shop. Trades as Exmoor Coast Holidays",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      dogs: true,
      dogs_note: "Free",
      season: "all-year",
      price_per_night: 15,
      price_note: "per adult; children 5–15 £12",
      hookup: null,
    },
  },
  {
    slug: "lynton-club-site",
    name: "Lynton Camping and Caravanning Club Site",
    kind: "stay",
    lat: 51.21759, lon: -3.85794,
    address: "Caffyn's Cross, Lydiate Lane, Lynton, EX35 6JS",
    phone: "01598 752379",
    url: "https://www.campingandcaravanningclub.co.uk/campsites/uk/devon/lynton/lynton-camping-and-caravanning-club-site/",
    notes: "The Club says not to follow satnav; it publishes approach directions. Arrivals after 1pm. Jumbo pitches for larger units. Whether non-members can book isn't stated. 2027 opens 22 March",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      dogs: true,
      season: { from: "03-27", to: "09-27" },
      price_per_night: null,
      price_note: "members from £9.30 per adult",
      hookup: true,
    },
  },
  {
    slug: "bottom-meadow-car-park",
    name: "Bottom Meadow car park",
    kind: "stay",
    // OSM way 160968516, centre: the pay car park on Castle Hill beside the
    // toilets and play area. The EX35 6AR postcode centroid is 130 m off.
    lat: 51.22846, lon: -3.83339,
    address: "Castle Hill, Lynton, EX35 6AR",
    url: "https://lyntonandlynmouthtowncouncil.gov.uk/parking/",
    // Overnight rules from North Devon Council's motorhomes guidance; the car
    // park itself is run by the town council, whose page doesn't repeat them.
    notes: "Town council car park where motorhomes may stay overnight. Up to two nights, no return within 48 hours; 8 m maximum; self-contained with a built-in toilet; 6 m from other motorhomes. Public toilets (RADAR key for the accessible one) and a play area",
    verified: "2026-09-13",
    stay: {
      type: "aire",
      dogs: null,
      season: null,
      price_per_night: 16,
      price_note: "cash, card or RingGo (location 23606)",
    },
  },
  {
    slug: "woody-bay-honesty-parking",
    name: "Woody Bay honesty-box parking",
    kind: "stay",
    lat: 51.22010, lon: -3.89996,
    address: "Near Woody Bay, Martinhoe, EX31 4QU",
    url: "https://park4night.com/en/place/118480",
    notes: "Six spaces with sea views. Reviewers warn it's very exposed in wind and muddy; levelling blocks needed",
    // A park4night listing is user-reported, not the operator.
    verified: null,
    stay: {
      type: "park4night",
      dogs: null,
      season: "all-year",
      price_per_night: 3,
      price_note: "honesty box or QR code",
    },
  },
  {
    slug: "hunters-inn",
    name: "The Hunters Inn",
    kind: "stay",
    food: { type: "pub" },
    lat: 51.21676, lon: -3.92722,
    address: "Heddon Valley, Parracombe, Barnstaple, EX31 4PY",
    phone: "01598 763230",
    email: "enquiries@thehuntersinnheddonvalley.co.uk",
    url: "https://thehuntersinnheddonvalley.co.uk/",
    notes: "National Trust inn. Ten rooms plus Heddon Lodge; free parking for guests. Not the Hunters Inn at Newton Tracey, which search results mix up with it",
    verified: "2026-09-13",
    stay: {
      type: "inn",
      dogs: true,
      dogs_note: "£15 per dog per stay, up to two; rooms 1–5 and 10 only; not left unattended",
      season: null,
      price_per_night: 100,
      price_note: "room only, £100–£200",
    },
  },
  {
    slug: "south-dean-camping",
    name: "South Dean Camping",
    kind: "stay",
    lat: 51.21866, lon: -3.94778,
    address: "Trentishoe, Parracombe, Barnstaple, EX31 4QD",
    phone: "07397 854413",
    email: "camp@southdeancamping.co.uk",
    url: "https://southdeancamping.co.uk/",
    notes: "The path runs just below the site. Eighteen acres of unmarked, unlit pitches. Closed for 2026; reopens 27 May 2027. Cash or bank transfer; arrivals 9am–9pm; no sign-written vehicles",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      dogs: true,
      dogs_note: "On leads. XL Bully, Pit Bull Terrier, Japanese Tosa, Dogo Argentino and Fila Brasileiro not accepted",
      season: null,
      price_per_night: 35,
      price_note: "from; non-electric campervan pitch, two adults",
      hookup: false,
    },
  },
  {
    slug: "silver-view-campsite",
    name: "Silver View Campsite",
    kind: "stay",
    // Postcode centroid: the farm isn't in OpenStreetMap.
    lat: 51.20668, lon: -4.00610,
    address: "Knapp Down Farm, Shute Lane, Combe Martin, EX34 0PG",
    phone: "07415 122557",
    url: "https://www.silverviewcampsite.co.uk/",
    notes: "Pop-up summer site, booked through campsites.co.uk. 2026 ran 22–31 May, June–July weekends and 24 Jul–30 Aug. Ten touring pitches, units up to 8 m",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      dogs: true,
      dogs_note: "Up to two per pitch",
      season: null,
      price_per_night: 25,
      price_note: "touring pitch, up to six people",
      hookup: false,
    },
  },
  {
    slug: "pack-o-cards",
    name: "Pack o' Cards",
    kind: "stay",
    food: { type: "pub" },
    lat: 51.20206, lon: -4.02914,
    address: "High Street, Combe Martin, EX34 0ET",
    phone: "01271 882300",
    email: "thepackocards@aol.com",
    url: "https://www.packocards.co.uk/",
    notes: "Six en-suite rooms. Free car park with an EV charger; motorhome parking not mentioned",
    verified: "2026-09-13",
    stay: {
      type: "inn",
      dogs: null,
      dogs_note: "Welcome in the bar; nothing said about rooms",
      season: null,
      price_per_night: 95,
      price_note: "from, with breakfast; £95–£115",
    },
  },
  {
    slug: "newberry-valley-park",
    name: "Newberry Valley Park",
    kind: "stay",
    lat: 51.20137, lon: -4.04195,
    address: "Woodlands, Combe Martin, EX34 0AT",
    phone: "01271 882334",
    email: "relax@newberryvalleypark.co.uk",
    url: "https://www.newberryvalleypark.co.uk/",
    notes: "Premier and Large pitches up to 8 m, Classic up to 5 m. Reception closes 10 Oct – 1 Nov, so book late-season stays by 9 Oct",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      dogs: true,
      dogs_note: "Up to two, £3 each per night. On lead except in the fenced dog field; dog wash on site",
      season: { from: "03-20", to: "11-01" },
      price_per_night: 27,
      price_note: "Classic pitch, low season, two people; £30–£51 for larger pitches and peak dates",
      hookup: true,
    },
  },
  {
    slug: "mill-park",
    name: "Mill Park Campsite",
    kind: "stay",
    lat: 51.20572, lon: -4.06362,
    address: "Mill Lane, Berrynarbor, EX34 9SH",
    phone: "01271 882647",
    email: "enquiries@millpark.com",
    url: "https://www.millpark.com/",
    notes: "Minimum two nights; no Sunday arrivals. Motorhome service point",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      dogs: true,
      dogs_note: "Up to two per pitch, £2 each per night",
      // The 2026 tariff runs 1 Mar – 31 Oct; no separate opening dates given.
      season: { from: "03-01", to: "10-31" },
      price_per_night: 30,
      price_note: "grass electric pitch, off-peak; £37–£45 fully serviced hardstanding",
      hookup: true,
    },
  },
  {
    slug: "watermouth-valley",
    name: "Watermouth Valley Camping Park",
    kind: "stay",
    lat: 51.21144, lon: -4.06373,
    address: "Watermouth, Ilfracombe, EX34 9SJ",
    email: "watermouthpark@gmail.com",
    url: "https://www.watermouthpark.co.uk/",
    notes: "Formerly Big Meadow. The postcode takes satnav to Watermouth Castle; the entrance is 300 yards past it. Contact form only, no phone. 2026 bookings closed; 2027 opens for booking 1 Oct. The 301 stops outside",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      dogs: true,
      dogs_note: "Off lead only in the exercise area above the Ocean View field",
      season: null,
      price_per_night: null,
      hookup: true,
    },
  },
  {
    slug: "hele-valley",
    name: "Hele Valley Holiday Park",
    kind: "stay",
    lat: 51.20194, lon: -4.10070,
    address: "Hele Bay, Ilfracombe, EX34 9RD",
    phone: "01271 862460",
    email: "holidays@helevalley.co.uk",
    url: "https://www.helevalley.co.uk/",
    notes: "Small campervan pitches up to 6 m; large touring and motorhome pitches up to 9 m, with grey-water drainage. Choice of pitch only when booking direct",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      dogs: true,
      dogs_note: "On lead on the park; not left alone in your unit",
      season: { from: "04-01", to: "10-31" },
      price_per_night: null,
      hookup: true,
    },
  },
  {
    slug: "hillsborough-car-park",
    name: "Hillsborough car park",
    kind: "stay",
    lat: 51.20687, lon: -4.10695,
    address: "Hillsborough Road, Ilfracombe, EX34 9QJ",
    url: "https://www.northdevon.gov.uk/parking/car-parks/ilfracombe/hillsborough-car-park",
    // North Devon Council's own pages. OSM tags it camping=no, sleeping=no,
    // which the council contradicts.
    notes: "Council car park where motorhomes may stay overnight, subject to space. Up to two nights, no return within 48 hours; 8 m maximum; self-contained with a built-in toilet; 6 m from other motorhomes. No facilities",
    verified: "2026-09-13",
    stay: {
      type: "aire",
      dogs: null,
      season: null,
      price_per_night: 16,
      price_note: "cash, card or RingGo",
    },
  },
  {
    slug: "sandpiper-inn",
    name: "Sandpiper Inn",
    kind: "stay",
    food: { type: "pub" },
    lat: 51.21074, lon: -4.11586,
    address: "Broad Street, Ilfracombe, EX34 9EQ",
    phone: "01271 865260",
    // No owner website; rooms from booking directories.
    notes: "B&B rooms above a harbourside pub, per booking directories",
    verified: null,
    stay: {
      type: "inn",
      dogs: null,
      dogs_note: "Reviews call the pub dog-friendly; nothing on rooms",
      season: null,
      price_per_night: null,
    },
  },
  {
    slug: "warcombe-farm",
    name: "Warcombe Farm Campsite",
    kind: "stay",
    lat: 51.18085, lon: -4.17966,
    address: "Station Road, Mortehoe, EX34 7EJ",
    phone: "01271 870690",
    url: "https://warcombefarm.co.uk/",
    notes: "Serviced, Pitch Plus, Premier, sea-view and fully gated pitches; grass or hardstanding. Fishing lake. Directories give a 15 Mar–31 Oct season, which differs from the owner's tariff dates",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      dogs: true,
      dogs_note: "£3 per night. On lead or tethered, never left unattended. 14-acre off-lead woodland walk; dog wash",
      // The 2026 tariff runs 13 Mar – 30 Oct; no separate opening dates given.
      season: { from: "03-13", to: "10-30" },
      price_per_night: 25.5,
      price_note: "serviced (electric) pitch, low season, two people; £29.50 mid, £44 peak",
      hookup: true,
    },
  },
  {
    slug: "damage-barton",
    name: "Damage Barton",
    kind: "stay",
    lat: 51.18520, lon: -4.18768,
    address: "Mortehoe, Woolacombe, EX34 7EJ",
    phone: "01271 870502",
    email: "enquiries@damagebarton.co.uk",
    url: "https://www.damagebarton.co.uk/",
    // OSM calls it a "Camping Club Site", which is wrong.
    notes: "Family-run on a working farm; affiliated to the Caravan and Motorhome Club but open to all. Direct access to the coast path. Grass or hardstanding, 10 A hookup. Deposit £50",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      dogs: true,
      dogs_note: "Up to two per unit, £2 each per night. Three exercise areas next to the site",
      season: { from: "03-20", to: "11-01" },
      price_per_night: 30,
      price_note: "low season: pitch £10 plus £10 per adult; £3 less without electric. Peak £37 for two",
      hookup: true,
    },
  },
  {
    slug: "north-morte-farm",
    name: "North Morte Farm",
    kind: "stay",
    lat: 51.19046, lon: -4.20086,
    address: "North Morte Farm, Mortehoe, Woolacombe, EX34 7EG",
    phone: "01271 870381",
    email: "info@northmortefarm.co.uk",
    url: "https://www.northmortefarm.co.uk/",
    notes: "Twenty gravel touring pitches, all with hookup. Narrow access. Direct access to the coast path. Walk-ins outside school holidays, 9am–7pm. Open for 2026 but no dates given",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      dogs: null,
      dogs_note: "Not allowed in the holiday homes; nothing said about pitches",
      season: null,
      price_per_night: null,
      hookup: true,
    },
  },
  {
    slug: "easewell-farm",
    name: "Easewell Farm Holiday Park",
    kind: "stay",
    lat: 51.18867, lon: -4.19957,
    address: "Mortehoe Station Road, Woolacombe, EX34 7EH",
    phone: "01271 871400",
    url: "https://www.woolacombe.co.uk/devon-holiday-parks/easewell-farm",
    notes: "Woolacombe Bay Holiday Parks. 309 pitches: grass, hardstanding and gravel Super pitches. Minimum two nights, sometimes longer",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      dogs: true,
      dogs_note: "Up to three per pitch, £1.50 each per night. On lead. Some breeds refused, including XL Bully and Pit Bull types",
      season: { from: "03-20", to: "11-02" },
      price_per_night: null,
      price_note: "touring pitch from £28 for two nights, two people",
      hookup: true,
    },
  },
  {
    slug: "twitchen-house",
    name: "Twitchen House Holiday Park",
    kind: "stay",
    lat: 51.18246, lon: -4.19701,
    address: "Mortehoe Station Road, Woolacombe, EX34 7ES",
    phone: "01271 870848",
    url: "https://www.woolacombe.co.uk/devon-holiday-parks/twitchen-house",
    notes: "Woolacombe Bay Holiday Parks. 252 pitches, hardstanding, some with sea views. Minimum two nights, sometimes longer. OSM names it Twitchen Caravan Park",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      dogs: true,
      dogs_note: "Up to three per pitch, £1.50 each per night. On lead. Some breeds refused, including XL Bully and Pit Bull types",
      season: { from: "03-20", to: "11-02" },
      price_per_night: null,
      price_note: "touring pitch from £32 for two nights, two people",
      hookup: true,
    },
  },
  {
    slug: "lundy-house-hotel",
    name: "Lundy House Hotel",
    kind: "stay",
    lat: 51.18092, lon: -4.21241,
    address: "Chapel Hill, Mortehoe, Woolacombe, EX34 7DZ",
    phone: "07969 723811",
    email: "info@lundyhousehotel.co.uk",
    url: "https://www.lundyhousehotel.co.uk/",
    notes: "Small hotel, eight en-suite rooms, on the path between Mortehoe and Woolacombe. Parking for ten cars",
    verified: "2026-09-13",
    stay: {
      type: "hotel",
      dogs: true,
      dogs_note: "£10 per dog per night. On lead; not on beds; not left in rooms except at breakfast",
      season: null,
      price_per_night: null,
    },
  },
  {
    slug: "woolacombe-sands",
    name: "Woolacombe Sands Holiday Park",
    kind: "stay",
    lat: 51.17020, lon: -4.18571,
    address: "Beach Road, Woolacombe, EX34 7AF",
    phone: "01271 870569",
    url: "https://www.woolacombe-sands.co.uk/",
    notes: "Basic, Standard and Super pitches. High-sided vehicles need prior consent; grass standard pitches take tents and small campervans only. Deposit £30",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      dogs: true,
      dogs_note: "£2.75 per night",
      season: null,
      price_per_night: null,
      price_note: "from £20 a pitch with electric, basic £15, super £25 — the page doesn't say per night",
      hookup: true,
    },
  },
  {
    slug: "willingcott-club-site",
    name: "Willingcott Woolacombe Club Campsite",
    kind: "stay",
    lat: 51.16947, lon: -4.16909,
    address: "Woolacombe, EX34 7HN",
    phone: "01271 870554",
    url: "https://www.caravanclub.co.uk/club-sites/england/devon-and-cornwall/devon/willingcott-woolacombe-club-campsite/",
    notes: "Caravan and Motorhome Club, open to non-members. 151 pitches, 80 hardstanding, 10 m maximum. The Club says not to follow satnav, and not to approach from the south on the B3231",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      dogs: true,
      dogs_note: "Dog walk from the site",
      season: { from: "04-02", to: "10-05" },
      price_per_night: null,
      hookup: true,
    },
  },
  {
    slug: "putsborough-sands-campervans",
    name: "Putsborough Sands campervan parking",
    kind: "stay",
    // Centre of OSM way 55983271, "Puttsborough Car Park".
    lat: 51.14484, lon: -4.22086,
    address: "Putsborough, Georgeham, Braunton, EX33 1LB",
    phone: "01271 890231",
    url: "https://www.putsborough.com/camping-camper-vans/",
    notes: "Run by the landowner, not the council. Overnight on the hardstanding at the top of the beach car park, never at the front. First come, first served; on very busy weekends whole-weekend stays only. Toilets, drinking water, Elsan point and cold beach showers. The caravan parks alongside take touring caravans only",
    verified: "2026-09-13",
    stay: {
      type: "aire",
      dogs: null,
      dogs_note: "The caravan-park terms allow two per pitch; the campervan page doesn't say",
      season: null,
      price_per_night: null,
      price_note: "per van, two adults; varies by season, ring for the tariff. Extra adults £7 each",
      hookup: false,
    },
  },
  {
    slug: "ruda-holiday-park",
    name: "Ruda Holiday Park",
    kind: "stay",
    // Centre of OSM way 830268115. OSM's operator tag (Parkdean) is out of date.
    lat: 51.13487, lon: -4.23512,
    address: "Croyde Bay, EX33 1NP",
    phone: "01271 890671",
    url: "https://www.johnfowlerholidays.com/devon-holiday-park/ruda-holiday-park/accommodation/camping-and-touring-holidays",
    notes: "John Fowler Holidays. Tourer and motorhome pitches are 11 × 7 m grass with 16 A hookup, in the Croyde Burrows field across the road from the main park. Bookings 01271 866766. Directories give a 6 Mar–31 Oct season; the owner's site gives no dates",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      dogs: true,
      dogs_note: "Up to two; a charge, amount not stated",
      season: null,
      price_per_night: null,
      hookup: true,
    },
  },
  {
    slug: "bay-view-farm",
    name: "Bay View Farm Caravan and Camping Park",
    kind: "stay",
    // Centre of OSM way 1154505806.
    lat: 51.12803, lon: -4.22670,
    address: "Croyde, Braunton, EX33 1PN",
    phone: "01271 890501",
    email: "info@bayviewfarm.co.uk",
    url: "https://www.bayviewfarmcampingcroyde.co.uk/",
    notes: "Premier pitches: hardstanding or grass, own tap, grey waste, 16 A. The owner says ignore satnav and turn left at Braunton's main lights. Motorhome arrivals 1–9pm, 11am–5pm in low season. Families and couples only",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      // Recorded as no: one dog is taken in low season only, by prior
      // arrangement, which a summer arrival can't rely on.
      dogs: false,
      dogs_note: "Low season only: one per pitch, by prior arrangement, £5 a night. Not in mid or high season",
      season: null,
      price_per_night: null,
      hookup: true,
    },
  },
  {
    slug: "the-whiteleaf",
    name: "The Whiteleaf",
    kind: "stay",
    // Centre of OSM way 1162801956.
    lat: 51.12868, lon: -4.22803,
    address: "Croyde, Braunton, EX33 1PN",
    phone: "01271 890266",
    email: "bookings@thewhiteleaf.co.uk",
    url: "https://www.thewhiteleaf.co.uk/",
    notes: "Five en-suite rooms",
    verified: "2026-09-13",
    stay: {
      type: "bnb",
      dogs: null,
      season: null,
      price_per_night: 90,
      price_note: "from, double room with breakfast; varies by season",
    },
  },
  {
    slug: "incledon-farm",
    name: "Incledon Farm",
    kind: "stay",
    // OSM node 4366876689. The EX33 1JN postcode centroid is 330 m off.
    lat: 51.14205, lon: -4.19661,
    address: "Incledon Farm, Georgeham, Braunton, EX33 1JN",
    phone: "01271 890200",
    url: "https://incledonfarm.co.uk/camping/",
    notes: "Working farm. Premium pitches have hookup and most are levelled, pre-booking essential; standard pitches are chosen on arrival and gently sloping, ramps lent. The owner calls the Buckland Cross route from Braunton unsuitable for caravans and sends you through Croyde instead. Arrivals midday–6pm. Georgeham village and its bus stop are five minutes' walk",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      dogs: true,
      dogs_note: "£2 a night. On a lead at all times; livestock on the farm",
      season: { from: "04-01", to: "10-31" },
      price_per_night: 28,
      price_note: "standard pitch, two people; premium with hookup £34",
      hookup: true,
    },
  },
  {
    slug: "lobb-fields",
    name: "Lobb Fields Caravan and Camping Park",
    kind: "stay",
    // OSM way 236976548, an unnamed caravan site. The EX33 1HG postcode
    // centroid is 400 m south, on Saunton Road.
    lat: 51.11365, lon: -4.18130,
    address: "Saunton Road, Braunton, EX33 1HG",
    phone: "01271 812090",
    url: "https://lobbfields.com/",
    notes: "180 pitches over three fields: grass, semi-hardstanding and fully serviced hardstanding; suits large motorhomes. Arrivals from midday, no waiting space. Bus stop at the entrance. The pitches page calls the Bottom Field open all year, which the tariff's dates contradict",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      dogs: true,
      dogs_note: "£3 a night. On-site dog walk",
      season: { from: "03-20", to: "11-01" },
      price_per_night: 22,
      price_note: "electric grass pitch, low season, two people; basic grass £16, fully serviced £29; peak £32.50–£47.50",
      hookup: true,
    },
  },
  {
    slug: "george-inn-braunton",
    name: "The George Inn",
    kind: "stay",
    food: { type: "pub" },
    // OSM node 1562108889, where it's named "The George Hotel".
    lat: 51.10791, lon: -4.16116,
    address: "Exeter Road, Braunton, EX33 2JJ",
    phone: "01271 814903",
    email: "info@thegeorgeinnbraunton.com",
    url: "https://thegeorgeinnbraunton.com/",
    notes: "Six en-suite rooms. Check-in 3–10pm. Parking not mentioned. The 303 and 21B stop outside",
    verified: "2026-09-13",
    stay: {
      type: "inn",
      dogs: true,
      dogs_note: "£10 a night, dog-friendly rooms only, so say when booking. Welcome throughout the pub",
      season: null,
      price_per_night: null,
    },
  },
  {
    slug: "thistledene",
    name: "Thistledene",
    kind: "stay",
    // Postcode centroid: not in OpenStreetMap, and the owner gives no street.
    lat: 51.10421, lon: -4.15828,
    address: "Braunton, EX33 2BN",
    phone: "07432 014114",
    url: "https://thistledene.com/",
    notes: "Two en-suite rooms with their own entrance, on the A361 into Braunton. Position is the postcode's, not the building's",
    verified: "2026-09-13",
    stay: {
      type: "bnb",
      dogs: true,
      dogs_note: "Up to two per room",
      season: null,
      price_per_night: null,
    },
  },
  {
    slug: "tarka-trail-camping",
    name: "Tarka Trail Camping",
    kind: "stay",
    // Centre of OSM way 1202350551.
    lat: 51.07039, lon: -4.15422,
    address: "Lower Yelland Farm, Yelland, Barnstaple, EX31 3EN",
    phone: "07944 247417",
    url: "https://tarkatrailcamping.co.uk/",
    notes: "Across the Taw: 3.5 km from Braunton as the crow flies, but the road goes round through Barnstaple. One large level field; takes campervans, motorhomes and caravans",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      dogs: true,
      dogs_note: "On a lead at all times",
      season: { from: "03-28", to: "09-30" },
      price_per_night: 18,
      price_note: "per adult with car; walkers £14; hookup £7",
      hookup: true,
    },
  },
  {
    slug: "north-walk-car-park",
    name: "North Walk car park",
    kind: "stay",
    // Centre of OSM way 29099644. The council's EX31 1DU postcode doesn't
    // resolve on postcodes.io.
    lat: 51.08179, lon: -4.06414,
    address: "North Walk, Barnstaple, EX31 1DU",
    url: "https://www.northdevon.gov.uk/parking/car-parks/barnstaple/north-walk-car-park",
    notes: "Council car park where motorhomes may stay overnight, subject to space. Up to two nights, no return within 48 hours; 8 m maximum; under 3,500 kg; self-contained with a built-in toilet; 6 m from other motorhomes. Beside the route by the Long Bridge",
    verified: "2026-09-13",
    stay: {
      type: "aire",
      dogs: null,
      season: null,
      price_per_night: 16,
      price_note: "cash, card or RingGo (zone 3613)",
    },
  },
  {
    slug: "riverbank-car-park-bideford",
    name: "Riverbank long stay car park",
    kind: "stay",
    // Centre of OSM way 7806591, an unnamed pay car park; the point on
    // Torridge District Council's car park map falls inside it. The EX39 2QS
    // postcode centroid is 490 m north.
    lat: 51.02266, lon: -4.20309,
    address: "Kingsley Road, Bideford, EX39 2QS",
    url: "https://www.torridge.gov.uk/parking/bideford/riverbank-long-stay",
    notes: "Torridge District Council car park between Victoria Park and the river, north of Bideford town centre. Motorhomes overnight 6pm–8am, up to two consecutive nights. No barbecues or fires, awnings, or tables and chairs outside. Some directories still give £11",
    verified: "2026-09-13",
    stay: {
      type: "aire",
      dogs: null,
      season: null,
      price_per_night: 12,
      price_note: "per bay; card, cash or RingGo (location 54524)",
    },
  },
  {
    slug: "churchfields-car-park-appledore",
    name: "Churchfields car park",
    kind: "stay",
    // Centre of OSM way 165326920, matching the point on Torridge District
    // Council's car park map.
    lat: 51.05510, lon: -4.19206,
    address: "The Quay, Appledore, EX39 1RL",
    url: "https://www.torridge.gov.uk/parking/appledore/churchfields",
    notes: "Torridge District Council car park on the estuary. Motorhomes overnight 6pm–8am, up to two consecutive nights. No barbecues or fires, awnings, or tables and chairs outside. EV charging. Across the Torridge from Instow: under a kilometre as the crow flies, round through Bideford by road",
    verified: "2026-09-13",
    stay: {
      type: "aire",
      dogs: null,
      season: null,
      price_per_night: 15,
      price_note: "per bay; card, cash or RingGo (location 54521)",
    },
  },
  {
    slug: "marshford-camping",
    name: "Marshford Camping",
    kind: "stay",
    // OSM node 4326673479. The EX39 1NS postcode centroid is 70 m west.
    lat: 51.04409, lon: -4.20486,
    address: "Marshford Organic Foods, Churchill Way, Northam, EX39 1NS",
    phone: "01237 477160",
    email: "info@marshfordcamping.co.uk",
    url: "https://www.marshfordcamping.co.uk/",
    notes: "Camping and Caravanning Club members only; membership number needed to book. Five grass van pitches and one hardstanding. Organic food shop on site. Booked ahead, minimum 2 nights in medium season and 3 in high; on-the-day pitches may be offered. Check-in from 2pm. Across the Torridge from Instow, round through Bideford by road",
    verified: "2026-09-13",
    stay: {
      type: "cl",
      dogs: true,
      dogs_note: "Two free per pitch, extra £2.50 a night. Lead of 3 m or less; never left unattended",
      // Inferred: the 2026 tariff gives rates only from 16 Apr to 30 Sep.
      season: { from: "04-16", to: "09-30" },
      price_per_night: 22,
      price_note: "per pitch, medium season, two adults; high season £25; hookup £5; solo walker or cyclist tent £11",
      hookup: true,
    },
  },
  {
    slug: "collacott-farm",
    name: "Collacott Farm",
    kind: "stay",
    // Postcode centroid (EX31 3QF). OSM's "Collacott Farm" is the solar farm;
    // the Club gives 51.0524, -4.1234, 170 m away.
    lat: 51.05342, lon: -4.12530,
    address: "Fremington, Barnstaple, EX31 3QF",
    url: "https://www.caravanclub.co.uk/certificated-locations/england/devon/barnstaple/collacott-farm/",
    notes: "Caravan and Motorhome Club CL, members only; directions only shown to members. Five pitches, hardstanding and grass, 16 A. Estuary views; working farm. About 1.5 miles from Fremington's shops and pubs",
    // The Club's listing; the owner has no site of their own.
    verified: null,
    stay: {
      type: "cl",
      dogs: true,
      dogs_note: "Listed as ideal for dogs, with a dog walk from the site",
      season: "all-year",
      price_per_night: null,
      hookup: true,
    },
  },
  {
    slug: "pyewell-farm",
    name: "Pyewell Farm",
    kind: "stay",
    // Postcode centroid (EX39 4LR); the Club gives 51.0383, -4.1389, 380 m
    // south-west.
    lat: 51.04142, lon: -4.13685,
    address: "Holmacott, Instow, Bideford, EX39 4LR",
    url: "https://www.caravanclub.co.uk/certificated-locations/england/devon/bideford/pyewell-farm/",
    notes: "Caravan and Motorhome Club CL, members only. Minimum stay 3 nights, always. Five pitches on a nearly level one-acre field; levelling blocks recommended. 16 A. Working sheep farm. Satnav not recommended; directions sent on booking (what3words multiple.craft.choppers). Arrivals midday–10pm",
    // The Club's listing; the owner has no site of their own.
    verified: null,
    stay: {
      type: "cl",
      dogs: true,
      dogs_note: "Up to two, on a lead on the farm. Dog walking area",
      season: { from: "05-01", to: "10-01" },
      price_per_night: null,
      hookup: true,
    },
  },
  {
    slug: "west-ashford-barton",
    name: "West Ashford Barton",
    kind: "stay",
    // OSM node 1562491077, the hamlet; the Club's GPS is 80 m east. The
    // EX31 4DB postcode centroid is 600 m east.
    lat: 51.09843, lon: -4.11082,
    address: "Ashford, Barnstaple, EX31 4DB",
    url: "https://www.caravanclub.co.uk/certificated-locations/england/devon/barnstaple/west-ashford-barton/",
    notes: "Caravan and Motorhome Club CL, members only. Five pitches, hardstanding and grass, over three fields on 7 acres; some sloping. Estuary views; working farm. Pub within half a mile",
    // The Club's listing; the owner has no site of their own.
    verified: null,
    stay: {
      type: "cl",
      dogs: null,
      dogs_note: "A dog walk is listed; no policy stated",
      season: { from: "04-01", to: "10-01" },
      price_per_night: null,
      hookup: true,
    },
  },
  {
    slug: "wayfarer-inn-instow",
    name: "The Wayfarer Inn",
    kind: "stay",
    food: { type: "pub" },
    // OSM node 3811363174.
    lat: 51.05561, lon: -4.18044,
    address: "Lane End Road, Instow, EX39 4LB",
    phone: "01271 860342",
    email: "info@thewayfarerinstow.co.uk",
    url: "https://www.thewayfarerinstow.co.uk/",
    notes: "Six en-suite rooms, on the Tarka Trail. No parking of its own: public car park by Instow Cricket Club, or limited roadside on Marine Parade. The Boathouse and the Instow Arms are next door",
    verified: "2026-09-13",
    stay: {
      type: "inn",
      // BringFido says £10 per pet per stay; unconfirmed.
      dogs: null,
      dogs_note: "Dogs welcome in the pub; rooms not stated",
      season: null,
      price_per_night: null,
    },
  },
  {
    slug: "instow-barton",
    name: "Instow Barton",
    kind: "stay",
    // Postcode centroid: not in OpenStreetMap.
    lat: 51.05863, lon: -4.16844,
    address: "Rectory Lane, Instow, EX39 4LU",
    phone: "01271 860845",
    email: "contact@instowbarton.co.uk",
    url: "https://www.instowbarton.co.uk/",
    notes: "Farmhouse B&B with a restaurant; five en-suite rooms. Free parking; bike lock-up. Check-in 2–6pm. Position is the postcode's, not the building's",
    verified: "2026-09-13",
    stay: {
      type: "bnb",
      dogs: true,
      dogs_note: "Both room types listed as pets allowed; no conditions given",
      season: null,
      price_per_night: null,
    },
  },
  {
    slug: "westward-ho-main-car-park",
    name: "Westward Ho! Main car park",
    kind: "stay",
    // Centre of OSM way 222045352, an unnamed pay car park; the point on
    // Torridge District Council's car park map falls inside it.
    lat: 51.04088, lon: -4.23667,
    address: "Golf Links Road, Westward Ho!, EX39 1LG",
    url: "https://www.torridge.gov.uk/parking/westward-ho/main",
    notes: "Torridge District Council car park in the centre of the village. Motorhomes overnight 6pm–8am, up to two consecutive nights; a van across two bays pays for both. No barbecues or fires, awnings, or tables and chairs outside. EV charging",
    verified: "2026-09-13",
    stay: {
      type: "aire",
      dogs: null,
      season: null,
      price_per_night: 12,
      price_note: "per bay; card, cash or RingGo (location 54524)",
    },
  },
  {
    slug: "seabreeze-appledore",
    name: "Seabreeze",
    kind: "stay",
    // The Club's GPS. The EX39 1NF postcode centroid is 50 m north; an unnamed
    // OSM caravan_site (way 1203517573) is 60 m north-west.
    lat: 51.04950, lon: -4.20770,
    address: "Long Lane, Appledore, EX39 1NF",
    url: "https://www.caravanclub.co.uk/certificated-locations/england/devon/bideford/seabreeze/",
    notes: "Caravan and Motorhome Club CL, members only. Adults only. Five pitches, hardstanding and grass, on 1.5 acres at the edge of Northam Burrows. Arrivals 1–8pm, leave by 11am",
    // The Club's listing. seabreezecampsite.co.uk no longer resolves.
    verified: null,
    stay: {
      type: "cl",
      dogs: true,
      dogs_note: "Listed as ideal for dogs; no conditions given",
      season: { from: "03-01", to: "01-03" },
      price_per_night: null,
      hookup: true,
    },
  },
  {
    slug: "knotty-corner",
    name: "Knotty Corner Camp Site",
    kind: "stay",
    // The Club's GPS; not in OpenStreetMap, and the Club shows no postcode.
    lat: 51.00417, lon: -4.26244,
    address: "Knotty Corner, Bideford",
    url: "https://www.campingandcaravanningclub.co.uk/campsites/uk/devon/bideford/knottycornercampsite/",
    notes: "Camping and Caravanning Club CS, members only; advance booking essential. Motorhomes up to 7.5 m. Grass and hardstanding pitches on a gently sloping 1.5 acres. Toilets, showers, washing-up",
    // The Club's listing; the owner has no site of their own.
    verified: null,
    stay: {
      type: "cl",
      dogs: true,
      dogs_note: "Listed as pets welcome; no conditions given",
      season: { from: "04-01", to: "10-31" },
      price_per_night: 20,
      price_note: "members, per unit including two adults and two children; up to £25",
      hookup: true,
    },
  },
  {
    slug: "skern-abbotsham",
    name: "Skern Adventure Abbotsham",
    kind: "stay",
    // Centre of OSM way 222161725, "The Ultimate High", tagged Abbotsham Road,
    // EX39 5AP — the activity centre's own address. The postcode centroid is
    // 800 m south-west, in Abbotsham village.
    lat: 51.02047, lon: -4.23897,
    address: "Abbotsham Road, Bideford, EX39 5AP",
    phone: "01237 475992",
    url: "https://www.skernadventure.co.uk/glamping-and-camping",
    notes: "Campsite at an outdoor activity centre: campervan touring pitches and tent pitches. Toilet and shower block, washing-up, waste disposal point, camp shop and café. Book online",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      dogs: null,
      dogs_note: "Directories say dogs allowed; Skern's own pages don't say",
      season: null,
      price_per_night: null,
      hookup: true,
    },
  },
  {
    slug: "seagate-appledore",
    name: "The Seagate",
    kind: "stay",
    food: { type: "pub" },
    // Centre of OSM way 1176460206.
    lat: 51.05432, lon: -4.19132,
    address: "The Quay, Appledore, EX39 1QS",
    phone: "01237 472589",
    email: "seagate@youngs.co.uk",
    url: "https://www.theseagate.co.uk/",
    notes: "Young's pub on the quay; breakfast daily, walk-ins welcome. Dogs welcome in the pub. Seventeen rooms, above the pub and in a converted sail loft. Customer car park, first come first served. Johns deli and café is 180 m along the quay",
    verified: "2026-09-13",
    stay: {
      type: "inn",
      dogs: true,
      dogs_note: "Dog-friendly rooms take up to two; £25 a night for one or two. On a lead in shared areas, never left unsupervised, not on beds or soft furnishings",
      season: null,
      price_per_night: null,
    },
  },
  {
    slug: "waterfront-inn-westward-ho",
    name: "The Waterfront Inn",
    kind: "stay",
    food: { type: "pub" },
    // Centre of OSM way 979335543. OSM gives EX39 1LH; the inn's own site 1LG.
    lat: 51.04139, lon: -4.23687,
    address: "Golf Links Road, Westward Ho!, EX39 1LG",
    phone: "01237 474737",
    url: "https://www.waterfrontinn.co.uk/",
    notes: "Pub with eleven en-suite B&B rooms; rooms are booked through Braddicks Holidays. Dogs welcome in the bar. Free parking. Live music some Friday and Saturday nights carries to the rooms",
    verified: "2026-09-13",
    stay: {
      type: "inn",
      // A 2016 TripAdvisor review describes a dog room (Petrel); the owner's
      // room page now says "No Pets".
      dogs: false,
      dogs_note: "No pets in the rooms",
      season: "all-year",
      price_per_night: null,
    },
  },
  {
    slug: "corner-house-bideford",
    name: "Corner House Guest House",
    kind: "stay",
    // OSM node 48931638.
    lat: 51.02043, lon: -4.20802,
    address: "The Strand, Bideford, EX39 2ND",
    phone: "01237 473722",
    url: "http://cornerhouseguesthouse.co.uk/",
    notes: "Guest house by Victoria Park, north of the Quay; five rooms. Street pay and display, free outside charging hours. Check-in after 4pm; key box for late arrivals",
    verified: "2026-09-13",
    stay: {
      type: "bnb",
      // BringFido lists dogs allowed; unconfirmed.
      dogs: null,
      dogs_note: "Not stated on the owner's site",
      season: "all-year",
      price_per_night: 88,
      price_note: "twin en-suite; king double from £105",
    },
  },
  {
    slug: "royal-hotel-bideford",
    name: "The Royal Hotel",
    kind: "stay",
    // Centre of OSM way 539889358.
    lat: 51.01621, lon: -4.20099,
    address: "Barnstaple Street, Bideford, EX39 4AE",
    phone: "01237 472005",
    url: "https://royalbideford.co.uk/",
    notes: "Hotel at the East-the-Water end of the Long Bridge, on the Tarka Trail. 32 rooms",
    verified: "2026-09-13",
    stay: {
      type: "hotel",
      dogs: true,
      dogs_note: "£20 per dog per night, in a handful of dog-friendly rooms. Dogs allowed in the bar and Merchants Bistro",
      season: null,
      price_per_night: null,
    },
  },
  {
    slug: "durrant-house-hotel",
    name: "Durrant House Hotel",
    kind: "stay",
    // Centre of OSM way 226884254.
    lat: 51.03379, lon: -4.21197,
    address: "Heywood Road, Northam, EX39 3QB",
    phone: "01237 472361",
    url: "https://durranthousehotel.com/",
    notes: "Hotel between Bideford and Northam, with the Olive Tree restaurant and the Appledore bar",
    verified: "2026-09-13",
    stay: {
      type: "hotel",
      dogs: true,
      dogs_note: "£20 per dog per night; ring before booking so a dog room can be chosen. Dogs in the Appledore bar, not the Olive Tree restaurant",
      season: null,
      price_per_night: null,
    },
  },
  {
    slug: "hoops-inn",
    name: "The Hoops Inn & Country Hotel",
    kind: "stay",
    food: { type: "pub" },
    // Centre of OSM way 343083672. The EX39 5DL postcode centroid is 10 m away.
    lat: 50.98464, lon: -4.31682,
    address: "Horns Cross, Bideford, EX39 5DL",
    phone: "01237 451222",
    email: "sales@hoopsinn.co.uk",
    // hoopsinn.co.uk redirects here.
    url: "https://www.hotelsnorthdevon.co.uk/",
    notes: "Part-thatched inn with thirteen en-suite rooms and a restaurant; breakfast included. 2.5 acres of gardens",
    verified: "2026-09-13",
    stay: {
      type: "inn",
      dogs: true,
      dogs_note: "In the family room and all standard doubles and twins. On the floor in bedding you bring; not on beds or furniture",
      season: null,
      price_per_night: null,
    },
  },
  {
    slug: "roeys-retreat",
    name: "Roey's Retreat Campsite",
    kind: "stay",
    // EX39 5RU via postcodes.io. OSM has no campsite here; its "Dyke Green
    // Farm" (node 5792174162), which shares the postcode, is 25 m away.
    lat: 50.98567, lon: -4.40563,
    address: "Clovelly Cross, Higher Clovelly, EX39 5RU",
    phone: "07551 007049",
    url: "https://www.roeysretreatcampsite.co.uk/",
    notes: "At the Clovelly Cross roundabout. 25 grass pitches, 6 × 6 m, all with water; toilets, showers, small shop. Booked through campsites.co.uk; 15% deposit non-refundable",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      dogs: true,
      dogs_note: "Up to two per pitch, on a lead",
      // The site says "April to October"; exact dates not given.
      season: { from: "04-01", to: "10-31" },
      price_per_night: 30,
      price_note: "from, electric pitch (10 A); non-electric from £25",
      hookup: true,
    },
  },
  {
    slug: "red-lion-clovelly",
    name: "The Red Lion Hotel",
    kind: "stay",
    food: { type: "pub" },
    // Centre of OSM way 120698635.
    lat: 50.99892, lon: -4.39805,
    address: "48 The Quay, Clovelly, EX39 5TF",
    phone: "01237 431237",
    url: "https://www.redlion-clovelly.co.uk/rooms/",
    notes: "On the harbour at the foot of the car-free cobbled street; seventeen rooms, all with a sea view. A stay includes entry to the village and Clovelly Court Gardens, and parking. Harbour Restaurant, and the Snug and Harbour bars",
    verified: "2026-09-13",
    stay: {
      type: "hotel",
      dogs: true,
      dogs_note: "Three dog-friendly rooms, £20 or £25 supplement; ring to book one",
      season: null,
      price_per_night: null,
    },
  },
  {
    slug: "stoke-barton-farm",
    name: "Stoke Barton Farm Campsite",
    kind: "stay",
    // OSM node 4326028589, in the camping fields (tagged "Stroke Barton").
    // The farmyard and entrance, opposite Stoke church, are 210 m north-east.
    // EX39 6DU is shared with Hartland Quay, so its centroid is no help.
    lat: 50.99186, lon: -4.51800,
    address: "Stoke, Hartland, Bideford, EX39 6DU",
    phone: "01237 441238",
    url: "https://www.westcountry-camping.co.uk/",
    notes: "Working farm opposite Stoke church. Over 12 acres of camping fields, 30 hookups; laundry, chemical disposal. Larger vans: ignore satnav through Hartland village and follow the site's route via Pengilly Way. No supermarket deliveries; no driving on site after dark. The Hartland Quay car parks send vans here",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      dogs: true,
      dogs_note: "Up to two, £2.50 each a night. On a lead at all times, never left unattended, not in the facilities",
      // 2026 dates: Friday 3 April to Sunday 4 October.
      season: { from: "04-03", to: "10-04" },
      price_per_night: 26,
      price_note: "two adults at £13 each; single occupancy £15; hookup £5.50",
      hookup: true,
    },
  },
  {
    slug: "pitt-farm",
    name: "Pitt Farm Campsite",
    kind: "stay",
    // OSM node 11939912973, an unnamed campsite carrying Pitt Farm's phone
    // number. The EX39 6BZ postcode centroid is 35 m away.
    lat: 51.00607, lon: -4.49302,
    address: "Pitt Farm, Hartland, Bideford, EX39 6BZ",
    phone: "07795 411474",
    url: "https://pittfarmcamping.co.uk/",
    notes: "Working dairy farm near Hartland Point; one flat 5-acre field with sea views. Toilet and shower block, chemical disposal. No wifi. Coming from Bude, don't follow satnav — use the site's directions. Arrive 11am–9pm; later arrivals park in the farmyard until morning. No supermarket deliveries. 01237 441919 also listed",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      dogs: true,
      dogs_note: "£1 a night. Tethered on your own pitch; not left to wander, not in the toilets",
      season: { from: "04-01", to: "09-30" },
      price_per_night: 22,
      price_note: "two adults at £11 each; 50% deposit, or full payment for stays of two nights or less",
      hookup: false,
    },
  },
  {
    slug: "west-titchberry-farm",
    name: "West Titchberry Farm",
    kind: "stay",
    // OSM node 4868049766.
    lat: 51.01627, lon: -4.50825,
    address: "Hartland Point, Hartland, Bideford, EX39 6AU",
    phone: "01237 441287",
    url: "https://www.hartlandpeninsula.co.uk/hotels-inns-bed-breakfast/west-titchberry-farm/",
    notes: "B&B in an 18th-century farmhouse on a working farm by Hartland Point. Evening meals and packed lunches on request",
    // The Hartland Peninsula Association listing. westtitchberryfarm.co.uk
    // no longer resolves.
    verified: null,
    stay: {
      type: "bnb",
      dogs: null,
      dogs_note: "Not stated",
      season: null,
      price_per_night: null,
    },
  },
  {
    slug: "hartland-caravan-camping-park",
    name: "Hartland Caravan & Camping Park",
    kind: "stay",
    // Centre of OSM way 77497859, named "South Lane Caravan Park". The
    // EX39 6DG postcode centroid is 100 m west.
    lat: 50.99135, lon: -4.47467,
    // The owner's site gives Fore Street; the Hartland Peninsula Association
    // listing gives South Lane.
    address: "Hartland, Bideford, EX39 6DG",
    phone: "01237 441876",
    email: "info@hartlandcaravanandcampingpark.co.uk",
    url: "https://www.hartlandcaravanandcampingpark.co.uk/",
    notes: "Four-acre park a few minutes' walk from Hartland village. Grass and hardstanding pitches; shower block, laundry, fishing pond. Holiday caravans on the same site. Buses from the entrance",
    verified: "2026-09-13",
    stay: {
      type: "campsite",
      dogs: true,
      dogs_note: "Free",
      season: null,
      price_per_night: 29.5,
      price_note: "electric pitch for two £27 plus £2.50 for a motorhome; non-electric £23; solo £7.50 less; rates vary by season",
      hookup: true,
    },
  },
  {
    slug: "fosfelle",
    name: "Fosfelle Country House",
    kind: "stay",
    // Centre of OSM way 77497866. The Club's GPS is 130 m south; the EX39 6EF
    // postcode centroid 60 m west.
    lat: 50.98667, lon: -4.47490,
    address: "Hartland, Bideford, EX39 6EF",
    phone: "01237 441273",
    url: "https://fosfelle.co.uk/caravan-camping/",
    notes: "Caravan and Motorhome Club CL, members only. Five hardstanding pitches with water, 12 A and picnic tables; some sloping; 9 m maximum. Token showers and WCs in private pods, grey and green waste disposal, laundry. Alpacas and miniature donkeys roam the paddock. Arrivals midday–10pm. Ten minutes' walk to Hartland",
    verified: "2026-09-13",
    stay: {
      type: "cl",
      dogs: true,
      dogs_note: "The Club listing gives a dog wash and dog runs; on a lead on site because of the animals",
      season: "all-year",
      price_per_night: 24,
      price_note: "per pitch including hookup and water, from the Hartland Peninsula Association listing",
      hookup: true,
    },
  },
  {
    slug: "old-smithy-inn",
    name: "The Old Smithy Inn",
    kind: "stay",
    food: { type: "pub" },
    // OSM node 5124645927, the pub. The rooms building (way 1286111649) is
    // 40 m south; the EX39 6HG postcode centroid 30 m.
    lat: 50.93338, lon: -4.51861,
    address: "Welcombe, Bideford, EX39 6HG",
    phone: "01288 331305",
    email: "theoldsmithyinnltd@gmail.com",
    url: "https://www.theoldsmithyinn.co.uk/",
    notes: "Village pub in Welcombe. Three en-suite double rooms across the beer garden, each with its own entrance; breakfast included, parking on site, check-in from 3pm. Bar 12–11pm daily; food Mon–Sat 12–3pm and 5–8pm, Sun 12–6pm. The Motorhome Stopover Club lists free overnight van parking for diners; the pub's own site doesn't mention it",
    verified: "2026-09-14",
    stay: {
      type: "inn",
      dogs: true,
      dogs_note: "The rooms page says pets welcome; no charge or limit given",
      season: null,
      price_per_night: null,
    },
  },
  {
    slug: "bush-inn-morwenstow",
    name: "The Bush Inn",
    kind: "stay",
    food: { type: "pub" },
    // Centre of OSM way 1076489846. OSM also has a bar node (11066959352)
    // 10 m away.
    lat: 50.90690, lon: -4.54957,
    address: "Crosstown, Morwenstow, Bude, EX23 9SR",
    phone: "01288 331242",
    email: "bushinn.crosstown@gmail.com",
    url: "https://www.thebushinnmorwenstow.com/",
    notes: "13th-century free house at Crosstown, up the combe from Morwenstow church. Camper vans may stay overnight in the car park, and tents in the garden, if you eat or drink at the pub. Food 12–9pm daily; breakfast Sat–Sun 8–11.30am. Four B&B rooms; only Room 4, across the courtyard, is dog-friendly. Live music and quiz nights. The Rectory Tearooms is 350 m away",
    verified: "2026-09-14",
    stay: {
      type: "aire",
      dogs: true,
      dogs_note: "Well-behaved dogs welcome, on leads at all times",
      season: null,
      price_per_night: null,
      price_note: "free if you eat or drink at the pub",
    },
  },
  {
    slug: "rectory-farm-wild-camping",
    name: "Rectory Farm Wild Camping",
    kind: "stay",
    // OSM node 1298693615, "Rectory Farm". OSM has no campsite; park4night's
    // pin for the field is 125 m east.
    lat: 50.90794, lon: -4.55367,
    address: "Rectory Farm, Crosstown, Morwenstow, EX23 9SR",
    url: "https://www.pitchup.com/campsites/England/South_West/Cornwall/Bude/rectory-farm-wild-camping/",
    notes: "Pop-up meadow site on the organic farm by the Rectory Tearooms, a few minutes from the coast path and the Bush Inn. Tents and small campervans. Water, portaloos and a hot shower",
    // Pitchup and park4night listings only; no owner website found.
    verified: null,
    stay: {
      type: "campsite",
      dogs: null,
      dogs_note: "Pitchup and park4night listings say dogs are allowed",
      // park4night gives 4 Jul–31 Aug; Pitchup opens it on 4 July. A pop-up
      // site's dates are set afresh each year.
      season: { from: "07-04", to: "08-31" },
      price_per_night: 15,
      price_note: "per tent or van, from park4night; an older ukcampsite listing gives £10",
      // ukcampsite.co.uk: no electric hookups.
      hookup: false,
    },
  },
  {
    slug: "dunsmouth-farm",
    name: "Dunsmouth Farm cliff field",
    kind: "stay",
    // Centre of OSM way 1472738998, the farmyard; the EX23 9EG postcode
    // centroid is 50 m away. The fields themselves are on the cliff to the
    // south-west: park4night's pin is 430 m from the farmyard, beside the
    // coast path.
    lat: 50.85471, lon: -4.54950,
    address: "Dunsmouth Farm, Bude, EX23 9EG",
    url: "https://park4night.com/en/place/188825",
    notes: "Two large clifftop fields with the coast path alongside. One toilet and a tap by the entrance. The lane is narrow, steep and rocky: manageable in a small van. Just park; the farmer collects in the evening. Reviewers find the one toilet stretched at weekends",
    // A park4night listing is user-reported, not the operator. searchforsites
    // marks it temporarily closed, but park4night reviews run to 29 Aug 2026.
    verified: null,
    stay: {
      type: "park4night",
      dogs: null,
      dogs_note: "park4night lists pets allowed",
      season: null,
      price_per_night: 10,
      price_note: "per van, from 2026 park4night reviews",
    },
  },
  {
    slug: "bryder-farm-camping",
    name: "Bryder Farm Camping",
    kind: "stay",
    // Centre of OSM way 1303981194. The EX23 9HP postcode centroid is 120 m
    // west.
    lat: 50.86901, lon: -4.51966,
    address: "Stibb, Bude, EX23 9HP",
    // From OSM.
    phone: "07765 028322",
    url: "https://www.facebook.com/stibb1972/",
    notes: "Small family site at Stibb, inland from Sandymouth. Eight touring pitches with hookup and water, a tent field, static caravans round the edge. Toilets, showers, laundry, waste disposal",
    // Directories (ukcampsite, park4night, Pitchup) and OSM tags only; the
    // owner has a Facebook page and no website.
    verified: null,
    stay: {
      type: "campsite",
      dogs: null,
      dogs_note: "Directories say dogs are welcome",
      season: null,
      price_per_night: null,
      // OSM power_supply=yes; park4night and ukcampsite agree.
      hookup: true,
    },
  },
  {
    slug: "wildly-camping",
    name: "Wildly Camping",
    kind: "stay",
    // The Google Maps pin linked from the owner's site. OSM has no campsite
    // here, and the EX23 9EE centroid, shared with Bude Holiday Park, is 170 m
    // west.
    lat: 50.84378, lon: -4.54512,
    // The owner's site gives "Maer, Bude"; directories give Maer Lane.
    address: "Maer Lane, Bude, EX23 9EE",
    phone: "07751 164745",
    url: "https://www.wildlycamping.co.uk/",
    notes: "Small field site at Maer, a short walk from Northcott Mouth and Crooklets. Tents and campervans. Two hot showers, two toilets, washing-up sinks, drinking water. No vehicle movement 10pm–7am; reception unmanned after 6pm",
    verified: "2026-09-14",
    stay: {
      type: "campsite",
      dogs: true,
      dogs_note: "On leads and supervised at all times",
      season: null,
      price_per_night: 24,
      price_note: "two people; extra adult £12, under-18 £7",
      // Not stated by the owner. Directories say no electric hookups.
      hookup: null,
    },
  },
  {
    slug: "wooda-farm",
    name: "Wooda Farm Holiday Park",
    kind: "stay",
    // Centre of OSM way 126117203.
    lat: 50.84433, lon: -4.51509,
    address: "Poughill, Bude, EX23 9HJ",
    phone: "01288 352069",
    url: "https://wooda.co.uk/camping/",
    notes: "Large park at Poughill with sea views; 220 touring and camping pitches, grass or hardstanding, some fully serviced. Secure dog exercise field, dog showers and a woodland walk. Farm shop; bar and takeaway March–October. Holiday homes and lodges on the same park",
    verified: "2026-09-14",
    stay: {
      type: "campsite",
      dogs: true,
      dogs_note: "Up to three per touring pitch, for a small nightly charge. On a lead, never left unattended, exercised in the designated areas",
      season: null,
      price_per_night: 35,
      price_note: "from, grass pitch with 16 A hookup; non-electric from £23, hardstanding electric from £41",
      hookup: true,
    },
  },
  {
    slug: "broadclose-park-camping",
    name: "Broadclose Park Camping (Bude Town FC)",
    kind: "stay",
    // Centre of OSM way 1098981036, the football pitch. The EX23 8DR postcode
    // centroid is 100 m away; park4night's pin 50 m.
    lat: 50.83009, lon: -4.53468,
    address: "Broadclose Park, Bude, EX23 8DR",
    // Bude Tourist Information Centre, which takes the bookings.
    phone: "01288 354240",
    url: "https://www.visitbude.info/accommodation/broadclose-park/",
    notes: "Camping field at the football club, a walk from the town centre and Summerleaze; Co-op five minutes, Morrisons ten. Meant for self-contained motorhomes: basic showers, no chemical disposal. Six hookup pitches and 25 unmarked. Training or a match may be on. Book through Visit Bude, or turn up and pay when someone calls round",
    // Visit Bude (the Bude Area Tourist Board) listing. The club's own
    // budetownfc.com now shows a Wix domain error.
    verified: null,
    stay: {
      type: "campsite",
      dogs: null,
      dogs_note: "The Visit Bude listing says on a lead on site, with a public footpath alongside for walks",
      season: null,
      price_per_night: 15,
      price_note: "motorhome and up to three people; hookup pitch £20; extra adult £4",
      hookup: true,
    },
  },
  {
    slug: "crescent-car-park-bude",
    name: "Crescent car park",
    kind: "stay",
    // Centre of OSM way 4877218, unnamed, beside the Tourist Information
    // office (way 176871525). The EX23 8LE postcode centroid is 50 m north-east;
    // park4night's two Crescent entries are within 65 m.
    lat: 50.82709, lon: -4.54597,
    address: "The Crescent, Bude, EX23 8LE",
    url: "https://www.cornwall.gov.uk/transport-parking-and-streets/parking/cornwall-council-car-parks/crescent-bude-ex23-8le/",
    // Rules from Cornwall Council's page and its motorhome parking page. "No
    // return within 48 hours" and "6 m apart, no awnings" are from Visit
    // Bude's page, which reproduces the council's sign. Toilets from OSM.
    notes: "Cornwall Council car park by the Tourist Information Centre and the canal. Self-contained motorhomes with their own toilet may stay overnight in the designated overflow area only: two consecutive nights at most, no return within 48 hours, 6 m apart, no awnings, chairs, BBQs or generators. Overnight tickets from the pay & display machine by the overflow area. Every other council car park in Bude, including Summerleaze, Crooklets and the Wharf, bans motorhomes 11pm–8am. Public toilets by the Tourist Information Centre",
    verified: "2026-09-14",
    stay: {
      type: "aire",
      dogs: null,
      season: "all-year",
      price_per_night: 20,
      price_note: "6pm–9am, April–October; £17.40 November–March",
    },
  },
  {
    slug: "efford-downs-campsite",
    name: "Efford Downs Campsite",
    kind: "stay",
    // Centre of OSM way 1194308228. The EX23 8LJ postcode centroid is 220 m
    // north-east, towards the lane end on Vicarage Road.
    lat: 50.82507, lon: -4.55042,
    address: "Vicarage Road, Bude, EX23 8LJ",
    email: "geddon@effordcamping.co.uk",
    url: "https://effordcamping.co.uk/",
    notes: "No-frills hillside field on Efford Down, the nearest campsite to the town centre, with direct access to the coast path. Sloping, with some flat spots. Water, flushing toilets, hot showers; bring toilet roll. Entrance lane just past the Brendon Arms towards Widemouth. Arrivals 2–9pm; no check-in, display your booking confirmation. Campervans and van conversions welcome; no A-class, twin-axle or over 8 m, and the lane suits nothing over 7 m. Quiet from 9pm",
    verified: "2026-09-14",
    stay: {
      type: "campsite",
      dogs: true,
      dogs_note: "£5 a night, paid on arrival; on a lead on site",
      season: null,
      price_per_night: 27,
      price_note: "two people sharing a pitch; extra adult £12; single walker with a tent £15",
      hookup: null,
    },
  },
  {
    slug: "upper-lynstone",
    name: "Upper Lynstone Caravan & Camping Park",
    kind: "stay",
    // Centre of OSM way 471567786. The EX23 0LP postcode centroid is 230 m
    // south.
    lat: 50.82066, lon: -4.54939,
    address: "Bude, EX23 0LP",
    phone: "01288 352017",
    url: "https://upperlynstone.co.uk/touring-camping/",
    notes: "Family-run park three-quarters of a mile from Bude on the Widemouth road; the coast path adjoins it and the canal towpath leads into town. Touring field of 36 levelled, fenced 10 A pitches, fifteen with hardstandings; more in two camping fields. Heated shower block, chemical disposal, laundry, shop with Calor and Camping Gas. Arrivals noon–9pm. Families and couples only, no groups; single hikers welcome. Holiday caravans for hire",
    verified: "2026-09-14",
    stay: {
      type: "campsite",
      dogs: true,
      dogs_note: "Well-behaved pets; on a lead on site and exercised off the park",
      season: null,
      price_per_night: null,
      hookup: true,
    },
  },
];
